Line 91: [%s][NrCellBlock] BlockList DB Initialized for Stack(%d) to NR
Line 112: [%s][NrCellBlock][WARNING] LteId(%d) or NrId(%d) out of range for Stack(%d)
Line 122: [%s][NrCellBlock] NR Cell blocked Status(%d), UsedFlag(%d) Stack(%d)
Line 128: [%s][NrCellBlock] NR Cell blocked Status(%d), UsedFlag(%d) Stack(%d)
Line 183: [%s][NrCellBlock] The blocked NR Cell(NARFCN%d : PCI%d) for Lte PCell(GlobalId:%d) is cleared Stack(%d)
Line 205: [%s][NrCellBlock] NR Cell(NARFCN%d : PCI%d) for Lte PCell(GlobalId:%d) is unblocked after %d seconds Stack(%d)
Line 217: [%s][NrCellBlock] The unblocked NR Cell(NARFCN%d : PCI%d) for Lte PCell(GlobalId:%d) is cleared Stack(%d)
Line 235: [%s][NrCellBlock] Lte PCell(GlobalId:%d) is cleared Stack(%d)
Line 309: [%s][NrCellBlock] No blocked NR Cell for current Lte PCell(GlobalId:%d) Stack(%d)
Line 326: [%s][NrCellBlock] New Item of Lte PCell(GlobalId:%d) is added Stack(%d)
Line 370: [%s][NrCellBlock] NR Cell(%d : %d) is not blocked for Lte PCell(GlobalId:%d) Stack(%d)
Line 388: [%s][NrCellBlock] New Item of NR Cell(%d : %d) for  Lte PCell(GlobalId:%d) is added Stack(%d)
Line 396: [%s][NrCellBlock] NR Cell(Band%d : NARFCN%d : PCI%d) for Lte PCell(GlobalId:%d) is found Stack(%d)
Line 426: [%s][NrCellBlock][WARNING] LteId(%d) or NrId(%d) out of range Stack(%d)
Line 439: [%s][NrCellBlock][WARNING] NR Cell already blocked when SCG Failure(%d) detected Stack(%d)
Line 478: [%s][NrCellBlock] Issue Detection Claimed(%d failure during %d seconds) Stack(%d)
Line 487: [%s][NrCellBlock] SCG failure count(%d) type(%d) Stack(%d)
Line 516: [%s][NrCellBlock][WARNING] LteId(%d) or NrId(%d) for Stack(%d)
Line 536: [%s][NrCellBlock] NR Cell(NARFCN:%d, PCI:%d) for Lte PCell(GlobalId:%d) is blocked for %d seconds(PoorSig: %d) Stack(%d)
Line 560: [%s][NrCellBlock][WARNING] LteId(%d) or NrId(%d) for Stack(%d)
Line 569: [%s][NrCellBlock] NR Cell(NARFCN:%d, PCI:%d) RSRP: %d, RSRQ: %d Stack(%d)
Line 588: [%s][NrCellBlock] NR Cell(NARFCN:%d, PCI:%d) for Lte PCell(GlobalId:%d) is unblocked due to good signal(RSRP: %d, RSRQ: %d) Stack(%d)
Line 645: [%s][NrCellBlock][WARNING] NR Blocklist to NR-RRC fail due to memory allocation for Stack(%d)
Line 678: [%s][NrCellBlock] Send ENDC_NSA_BLACKLIST_IND (%d) to NR
Line 718: [%s][NrCellBlock][WARNING] DropMeasReportInd to LTE-RRM fail due to memory allocation for Stack(%d)
Line 725: [%s][NrCellBlock] Send DROP_MEAS_REPORT_IND (MeasId: %d) to LTE-RRM
Line 755: [%s][NrCellBlock][WARNING] NULL Pointer for ScgFailInd
Line 764: [%s][NrCellBlock] MeasResult in ScgFailInd, Narfcn(%d)
Line 773: [%s][NrCellBlock] MeasResult in ScgFailInd, PCI(%d)
Line 779: [%s][NrCellBlock] SCG FAIL, PCI(%d) RSRP(%d) RSRQ(%d)
