Line 1118: [MDM] SetMcwGearLevel: abnormal rat[%d]
Line 1123: [MDM] SetMcwGearLevel: rat(%d) gear_sel(%d) gear_options(%d)
Line 1469: [MDM] GetRfCalMode: RAT(%d), Cal_status(%d)
Line 624: [AMMPG] SetVal_2g(%d) SetVal_3g(%d) SetVal_4g(%d) SetVal_nr(%d) SetVal_3g_Hspa(%d)
Line 672: [AMMPG] STATUS(1st) => MBUS(0x%x), FRONT_RX(0x%x), FRONT_TX(0x%x), SYMBPROC_M(0x%x), MCW(0x%x)
Line 685: [AMMPG] STATUS(2nd) => MBUS(0x%x), FRONT_RX(0x%x), FRONT_TX(0x%x), SYMBPROC_M(0x%x), MCW(0x%x)
Line 737: [AMMPG] STATUS(1st) => MBUS(0x%x), FRONT_RX(0x%x), FRONT_TX(0x%x), SYMBPROC_M(0x%x), MCW(0x%x)
Line 750: [AMMPG] STATUS(2nd) => MBUS(0x%x), FRONT_RX(0x%x), FRONT_TX(0x%x), SYMBPROC_M(0x%x), MCW(0x%x)
Line 799: [AMMPG] STATUS(1st) => MBUS(0x%x), FRONT_RX(0x%x), FRONT_TX(0x%x), MCW(0x%x)
Line 805: [AMMPG] STATUS(2nd) => MBUS(0x%x), FRONT_RX(0x%x), FRONT_TX(0x%x), MCW(0x%x)
Line 854: [AMMPG] STATUS(1st) => MBUS(0x%x), FRONT_RX(0x%x), FRONT_TX(0x%x), SYMBPROC_M(0x%x), MCW(0x%x)
Line 860: [AMMPG] STATUS(1st) => DEMOD_MEAS_CSI(0x%x), DEMOD_FDBUF_CE_M(0x%x), DEMOD_DN_POSTCE_M(0x%x), DEMOD_BE_M(0x%x)
Line 867: [AMMPG] STATUS(2nd) => MBUS(0x%x), FRONT_RX(0x%x), FRONT_TX(0x%x), SYMBPROC_M(0x%x), MCW(0x%x)
Line 873: [AMMPG] STATUS(2nd) => DEMOD_MEAS_CSI(0x%x), DEMOD_FDBUF_CE_M(0x%x), DEMOD_DN_POSTCE_M(0x%x), DEMOD_BE_M(0x%x)
Line 934: [AMMPG] STATUS(1st) => MBUS(0x%x), FRONT_RX(0x%x), FRONT_TX(0x%x), SYMBPROC_M(0x%x), MCW(0x%x)
Line 940: [AMMPG] STATUS(1st) => DEMOD_MEAS_CSI(0x%x), DEMOD_FDBUF_CE_M(0x%x), DEMOD_DN_POSTCE_M(0x%x), DEMOD_BE_M(0x%x)
Line 947: [AMMPG] STATUS(2nd) => MBUS(0x%x), FRONT_RX(0x%x), FRONT_TX(0x%x), SYMBPROC_M(0x%x), MCW(0x%x)
Line 953: [AMMPG] STATUS(2nd) => DEMOD_MEAS_CSI(0x%x), DEMOD_FDBUF_CE_M(0x%x), DEMOD_DN_POSTCE_M(0x%x), DEMOD_BE_M(0x%x)
Line 965: [AMMPG][%s] SetAmmpgMode: RAT(%d), mode(%d)
Line 1372: [MDM] SetActiveRatInfo: RAT(%d -> %d), reset(%d)
Line 1413: [Debug] NrFullResetFlag(%d)
Line 1443: [MDM] ChangePrevratInfo: RAT(%d -> %d)
Line 1523: [MDM] SetClockGating: Wrong RAT(%d)
Line 1561: [MDM] PowerDomain(%d) Status(%d)
Line 1564: [MDM] SetClockGating: RF cal mode, RAT(%d)
Line 1609: [MDM][WARNING] PowerDomain(%d) clock is areadly '0x0', However tried to write again with '0x0'
Line 1632: [MDM] PowerDomain(%d) Status(%d)
Line 1636: [MDM] SetClockGating: RAT(%d), mode(%d -> %d)
Line 1693: [RFD_MCMU] RfdClockGatingMode: RAT(%d), mode(%d -> %d)
Line 1699: [RFD_MCMU] Don't touch the RFD clock, MDM_FRONT_RX(%d), MARCONI_HPCM_STATE(%d), RF_VRF(0x%x), RAT(%d)
Line 1716: [RFD_MCMU][%s] RFD_MCMU_SW_CLK_ON%d : Write(0x%08X) ?= Read(0x%08X)
Line 1718: [RFD_MCMU] RfdClockGatingMode: RF cal mode, RAT(%d)
Line 1749: [RFD_MCMU] HALDEVMNG.checkMarconiStatus() == TRUE / RFD_OUT_DATA_SEL Blocked
Line 1756: [RFD_MCMU][%s] RFD_MCMU_SW_CLK_ON%d : Write(0x%08X) ?= Read(0x%08X)
Line 1760: [RFD_MCMU] RfdClockGatingMode: RAT(%d), mode(%d -> %d)
Line 1779: HALMODEM_GetClockGatingMode : rat(%d) prev_cgm(%d)
Line 1891: SetPllDsmValue : offset[0x%08X], mwpll_offset[0x%08X], MWPLL_CON5[0x%08X]
Line 1917: SetPllDsmValue: offset(%d) RF[0x%08X] BB[0x%08X]
Line 1987: [HALMODEM] HALMODEM_SetNbNtnMode: NbNTN Mode(%d)
