Line 1538: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1545: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1748: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1757: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1764: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1817: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1902: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1933: [MDFS] [%d][dbg] fromCaller: rat(0x%x) oneLevDown(0x%x) scs(0x%x) ccIdxUl(0x%x)
Line 1981: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1982: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1993: [MDFS] [%d]ChangeRsearch: rat(%d), onoff(%d) req_clkRate_prev(%d)cur(%d)
Line 2003: [MDFS] [%d]ChangeRsearch: rat(%d), onoff(%d) req_clkRate_prev(%d)cur(%d)
Line 2042: [MDFS][WARNING] %s: Wrong %s(%d)
Line 2053: [MDFS] [%d]Update DiffScsCclist: cc0(%d)cc1(%d)cc2(%d)cc3(%d)cc4(%d)
Line 2697: [MDFS][WARNING] %s: Wrong %s(%d)
Line 2698: [MDFS][WARNING] %s: Wrong %s(%d)
Line 2762: [MDFS] [%d]ModemDvfsNv(0x%X), WbCeNv(%d), DFS/DVS_En(%03X), LPM/CpuCpSkew/SudWakeup/NtnDvfs/EnhancedSlo_En(%05X), RtRstdRestrictEnable(%d) LogLev(%d), Chip/Version(%X)
Line 2765: [MDFS] [%d]CP Vout Hex(Volt) [0x%02X(%duV), 0x%02X(%duV), 0x%02X(%duV), 0x%02X(%duV)]
Line 2767: [MDFS] [%d]CP Vout Delta(Delay) [OD-NM: %duV(%duS), NM-UD: %duV(%duS), UD-SUD: %duV(%duS)]
Line 2771: [MDFS] [%d]DfsMinlock[RT/M/S/C/B](%d,%d,%d,%d,%d), manualDfsMinlock_En/Run(%d/%d), ForcedOD(%d)
Line 2775: [MDFS] [%d]DvsMinlock[CP](%d), manualDvsMinlock_En/Run(%d/%d)
Line 4775: [MDFS][WARNING] %s: Wrong %s(%d)
Line 5379: [MDFS][WARNING] %s: Wrong %s(%d)
Line 5908: [MDFS] [%d]SendDfsValueToSymProc: rat(%d) freqRateCore0(%x) freqRateCore1(%x) rateMode0(%d) rateMode1(%d) lpmFlag0(%d) lpmFlag1(%d), lpm_NRTP0(%d), lpm_NRTP1(%d)
Line 5998: [MDFS] [%d] Skip LPM : coreIdx(%d) NR numCC(%d)
Line 6129: [MDFS] [%d]NrSpTti: idx:core/cc(%x) st:prv/cur(%x) tp(%d) th(%d)  k1/upd/up(%x) dropCnt(%d) lpmFlag/lpm_NRTP(%x) timer(%d) flag256QAM(%d)
Line 6165: [MDFS][WARNING] %s: Wrong %s(%d)
Line 6224: [MDFS] [%d]NrSpDci: idx:core/cc(%x) st:prv/cur(%x) iterFlg(%d) upd/up(%x) dropCnt(%d) lpmFlag(%x) lpm_NRTP(%d) cond_K1_lev(%d) cond_Advance(%d) 
Line 6246: [MDFS][WARNING] %s: Wrong %s(%d)
Line 6296: [MDFS] [%d]NrSpHarq: idx:core|cc(%x) st:prv|cur(%x) crc(%d) upd|up(%x) dropCnt(%d) lpmFlag(%x) lpm_NRTP(%d)
Line 6435: [MDFS] [%d]GenTxFilterClkOnOff: INFRA_SW_CLK_ON1(0x%x)INFRA_DYN_CLK_ON_EN1(0x%x) TXFILTER_DYN_CLK_ON_EN0(0x%x)1(0x%x)
Line 6439: [MDFS] [%d] skip GenTxFilterClkOnOff (due to PD_MDM_FRONT OFF)
Line 6540: [MDFS] [%d]LteSpTti: Idx:core(%d) st:prv/cur(%x) tp(%d) th(%d) upd/up(%x) dropCnt(%d) lpmFlag(%x) timer(%d)  flag256QAM(%d)
Line 6619: [MDFS] [%d]LteSpDci: coreIdx(%d) st:prv/cur(%x) iterFlag(%d) upd/up(%x) dropCnt(%d) lpmFlag(%x) 
Line 6665: [MDFS] [%d]LteSpHarq: coreIdx(%d) ltevalid(%d) flag(%d) 
Line 6696: [MDFS] [%d]LteSpHarq: coreIdx(%d) st:prv/cur(%x) crc(%d) upd/up(%x) dropCnt(%d) lpmFlag(%x) 
Line 1416: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1422: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1437: [MDFS] [%d][dbg] fromLteCsiConfig: opIdx(%d/%d), r_csi_tmp(%d) += tbl(%d)[bw(%d)]
Line 1444: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1477: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1483: [MDFS] [%d][dbg] fromNrCsiConfig: opIdx(%d/%d) r_csi_tmp(%d) += A*N_pmi(%d) + B*N_pmi*numRB(%d) + C
Line 1487: [MDFS] [%d][dbg] fromNrCsiConfig: cur_CC_Idx(%d) R_nrt_csi_nr_cc(%d)
Line 1511: [MDFS] [%d]CalcRcsi: rat(%d), numOper_Lte(%d)Nr(%d), r_csi_Lte(%d) + Nr(%d) = r_csi(%d) clkRateIdx_csi_prev(%d)cur(%d)
Line 1593: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1608: [MDFS] [%d][dbg] fromLteMeasConfig: RSSI/RSRP OFF : lte_numCell(%d) r_nrt_rstd_lte(%d)
Line 1617: [MDFS] [%d][dbg] fromLteMeasConfig: rstd(%d), rstdIc(%d), samefftcore(%d), r_nr_rssi_lte(%d) = numCell(%d)*numRx(%d)*1000/ lteDiv(%d)
Line 1627: [MDFS] [%d][dbg] fromLteMeasConfig: RSTD OFF : lte_numCell(%d) r_nrt_rstd_lte(%d)
Line 1639: [MDFS] [%d][dbg] fromLteMeasConfig: cellCnt(%d/%d), rstd(%d), rstdIc(%d), samefftcore(%d), r_nrt_rstd_lte(%d) += numRx(%d)*bw(%d)/200M
Line 1646: [MDFS] [%d][dbg] fromLteMeasConfig: RSTD IC is ON (full clock) : r_nrt_rstd_lte(%d)
Line 1664: [MDFS] [%d][dbg] fromNrMeasConfig: RSSI/RSRP OFF : nr_numCell(%d) r_nrt_rssi_nr(%d)
Line 1675: [MDFS] [%d][dbg] fromNrMeasConfig: cellCnt(%d/%d), samefftcore(%d), r_nrt_rssi_nr(%d) += tbl(%d)[bw(%d)]*ceil(#rx(%d)/2)
Line 1687: [MDFS] [%d][dbg] fromNrMeasConfig: RSTD OFF : nr_numCell(%d) r_nrt_rstd_nr(%d)
Line 1700: [MDFS] [%d][dbg] fromNrMeasConfig: cellCnt(%d/%d), samefftcore(%d), r_nrt_rstd_nr(%d) += rx(%d)
Line 1707: [MDFS] [%d][dbg] fromNrMeasConfig: RSTD IC is ON (full clock) : r_nrt_rstd_nr(%d)
Line 1722: [MDFS] [%d]CalcRmeas: rat(%d), numOper_Lte(%d)Nr(%d), r_meas(%d) clkRateIdx_meas_prev(%d)cur(%d)
Line 1050: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1061: [MDFS] [%d][dbg] fromCCalloc: VDD%d : LTE CcCnt(%d) numCC(%d) bw(%d) numRx(%d) procSum(%d) isSLO(%d) measCellInd(%d)
Line 1068: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1071: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1097: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1111: [MDFS] [%d][dbg] fromCCalloc: Core%d : FR%d CcCnt(%d) numCC(%d) bw(%d) numRx(%d) procSum(%d) ccIdxDemod(%d) isSLO(%d) measCellInd(%d)
Line 1119: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1161: [MDFS] [WARNING] fromCCalloc(core%d): procSum(%d) is high, set to (%d)
Line 1225: [MDFS] [%d]UpdateDB: isOC[1/1]procSum[3/3](%d) reduced_procSum[3/3](%d) ratFlag(core0(LTE/FR1/FR2)core1(LTE/FR1/FR2)(%x)) (BW/numCC/servCC/numRx/numL[3/1/1/1/2]):core0(LTE(%d)FR1(%d)FR2(%d))core1(LTE(%d)FR1(%d)FR2(%d))
Line 998: [MDFS] [%d][dbg] UpdateNumDiffScsCc: core(%d) ratidx(%d) ccCnt(%d) ccIdx(%d) valid(%d) numDiffScsCC(%d) += numCC(%d)
Line 1266: [MDFS] [%d][WARNING] fromCCalloc: LTE UL coreIdx(%d) numCC(%d => 1) 
Line 1277: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1282: [MDFS] [%d][dbg] fromCCalloc: LTE UL coreIdx(%d) numCC(%d) bwIdx(%d) bwValue(%d) ccIdxDemod(%d)
Line 1308: [MDFS] [%d][WARNING] fromCCalloc: FR1 UL coreIdx(%d) numCC(%d => 1) 
Line 1319: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1334: [MDFS] [%d][dbg] fromCCalloc: FR1 UL coreIdx(%d) numCC(%d) bwIdx(%d) bwValue(%d) duplex(%d) ccIdxDemod(%d) scs(%d) ofdmscheme(%d)
Line 1347: [MDFS] [%d][WARNING] fromCCalloc: FR2 UL coreIdx(%d) numCC(%d => 1) 
Line 1358: [MDFS][WARNING] %s: Wrong %s(%d)
Line 1363: [MDFS] [%d][dbg] fromCCalloc: FR2 UL coreIdx(%d) numCC(%d) bwIdx(%d) bwValue(%d) ccIdxDemod(%d) 
Line 1385: [MDFS] [%d][dbg] fromChangeRtUl: FR1 UL coreIdx(%d) numCC(%d) bwIdx(%d) bwValue(%d) duplex(%d) ccIdxDemod(%d) scs(%d) ofdmscheme(%d)
Line 5060: [MDFS] [%d]ResetPrevPrams
Line 5085: [MDFS] [WARNING]ResetNumCC: numRat is minus(-), set to Zero(0x0)
Line 5106: [MDFS] [WARNING]ResetNumCC: numRat is minus(-), set to Zero(0x0)
Line 5124: [MDFS] [%d]ResetNumCC for Rat[%d](0:LTE,1:FR1,2:FR2)
Line 5156: [MDFS] [%d]ResetNumCCUl for Rat[%d](0:LTE,1:FR1,2:FR2)
Line 2334: [MDFS] [WARNING] iratGap[%d] is bigger than 0x1, set to 0x1
Line 2448: [MDFS] [WARNING] SpecialModeNRT[%d] is minus(-), set to Zero(0x0)
Line 2451: [MDFS] [WARNING] iratGap[%d] is minus(-), set to Zero(0x0)
Line 2672: [MDFS] [%d]CheckRatAfterEvent: ActRat(%d), update(%d)
Line 2489: [MDFS] [WARNING] reqRat(%d) : RT_UL exception is not supported
Line 2514: [MDFS] [WARNING] EXCEPT_RT_DL_1_2 : no change (cur RT clkRate 1) 
Line 2529: [MDFS] [WARNING] EXCEPT_RT_DL_1_4 : no change (cur RT clkRate > 1/4) 
Line 2563: [MDFS] [WARNING] SpecialModeRT[%d] is minus(-), set to Zero(0x0)
Line 3043: [MDFS] [%d]GetVolt: highestclk(%X), Minlock[CPU/RSTRCT/NR](%d,%d,%d, Max(%d)), ManualMinlock(%d), Result[prev(%x) -> cur(%x=>%x)]
Line 3233: [MDFS] MPLL_NRT On (%d => %d)
Line 3249: [MDFS] [%d]Skip Drop(voltDn) rat(%d) coreIdx(%d) clk:prev(%d)cur(%d) isWaitingForDrop:(%d) DropCnt:(%d)
Line 3271: [MDFS] MPLL_NRT Off (%d => %d)
Line 3114: [MDFS] [%d]Do Drop: rat(%d) coreIdx(%d) clk:prev(%d)cur(%d) isWaitingForDrop:(%d) DropCnt:(%d)
Line 3130: [MDFS] [%d]Skip Drop: rat(%d) coreIdx(%d) clk:prev(%d)cur(%d) isWaitingForDrop:(%d) DropCnt:(%d)
Line 4307: [MDFS][WARNING] %s: Wrong %s(%d)
Line 4316: [MDFS] [DBG] ReqLev(0x%02X,0x%02X), MuxSel(0x%02X,0x%02X)
Line 4330: [MDFS] [DBG][DN] wait_time: %d, idx: %d, delay: %d
Line 4344: [MDFS] [DBG][UP] wait_time: %d, idx: %d, (idx-1): %d, delay: %d
Line 4349: [MDFS] [%d]Set VDD_CP(No Change)
Line 4357: [MDFS] [%d]Set VDD_CP(0x%02X), diff(%d), wait_time(%d)
Line 3728: [MDFS] [%d]CheckModeUl: highestCore(%d) rateMode_RtUl0/1(%4d) rateMode_RtDl0/1(%4d) numCC(core0/core1/LTE/FR1/FR2(%05x)) bw(LTE(%dM)FR1(%dM)FR2(%dM)) highestFR1(scs/duplex/ofdmScheme(%03x))
Line 3836: [MDFS] [DUMP] clkRate[NRT_M](%d => %d), HwDbg(%X)
Line 3839: [MDFS] [NRT_M][WARNING] BreakCnt[0](%d) BreakCnt[1](%d) 
Line 3944: [MDFS] [DUMP] clkRate[NRT_S](%d => %d), HwDbg(%X)
Line 3948: [MDFS] [NRT_S][WARNING] BreakCnt[0](%d) BreakCnt[1](%d) 
Line 4053: [MDFS] [DUMP] clkRate[NRT_C](%d => %d), HwDbg(%X)
Line 4056: [MDFS] [NRT_C][WARNING] BreakCnt[0](%d) BreakCnt[1](%d) 
Line 4161: [MDFS] [DUMP] clkRate[NRT_B](%d => %d), HwDbg(%X)
Line 4164: [MDFS] [NRT_B][WARNING] BreakCnt[0](%d) BreakCnt[1](%d) 
Line 4213: [MDFS] [WARNING] clkRate[RT] rate is too low (%d => %d)
Line 4255: [MDFS] [WARNING] clkRate[RT] fidx valuse is minus (%d)
Line 4273: [MDFS] [%d] skip GenTxFilterClkOnOff (due to PD_MDM_FRONT OFF)
Line 4277: [MDFS] [DUMP] clkRate[RT](%d => %d), HwDbg(%X)
Line 4280: [MDFS] [RT][WARNING] BreakCnt[0](%d) BreakCnt[1](%d) 
Line 4442: [MDFS] InterDfs: [Step1][0] (%d)(%d)(%d)(%d)(%d)(%d)(%d)(%d)
Line 4446: [MDFS] InterDfs: [Step1][1] (%d)(%d)
Line 4474: [MDFS] InterDfs: [Step2][SYMB_M] (%d)(%d)(%d)(%d)(%d)(%d)(%d)(%d)(%d)
Line 4494: [MDFS] InterDfs: [Step2][TX] (%d)(%d)(%d)(%d)(%d)
Line 4569: [MDFS] [%d]InterDfs: Rat(%d), SubCoreStatus(%d => %d)
Line 4571: [MDFS] InterDfs: BreakCnt(%d/%d/%d/%d)
Line 4575: [MDFS] [WARNING]InterDfs: Worng RAT(%d)
Line 5032: [MDFS] [%d]ResetAllPrams
Line 4686: [MDFS] [WARNING]The volt_cp(%x) volt_emcp(%x), but is not allowed frequency setting detection, DropStep1(0x%05X)
Line 4718: [MDFS][WARNING] %s: Wrong %s(%d)
Line 4738: [MDFS] [WARNING][DFS] MCW OFF
Line 5520: [MDFS] [WARNING]SetDfsApi: LteSum is minus(-), set to Zero(0x0)
Line 5525: [MDFS] [WARNING]SetDfsApi: NrSum is minus(-), set to Zero(0x0)
Line 6735: [MDFS] [%d]%s: rat/owner(0x%04x), actMode(0x%02x)[%s], V_RT/M/S/C/B(%08X), ratemode0/1/UL(%06d), st/upd/r_maxmin0/1/LPM0/1/slo/1levDn(0x%08x), special_Irat/NRT/RT/Sum(0x%07x) Called by '%s()'
Line 6755: [MDFS] [%d]SetDvsMinLock: wrong cpuVoltLvl(%d), DvsMinLock set to NM
Line 6760: [MDFS] [%d]cpuVoltLvl(%d) => cpuCpDvsMinLock(%d)
Line 6815: [MDFS] [%s]: Isr Ignored, Already clock down
Line 6838: [MDFS] [%s]: Isr Ignored, Already clock up
Line 6859: [MDFS][WARNING]Worng parameter: clk_control(%d)!!
Line 6798: [MDFS] [%s]: Ignored, LTE Act(%d), NrSum(%d), NrSpecialMode(%d)
Line 6902: [MDFS] [%d]ltetxMod_1d4change_prohibited(%d)
