Line 136: [SLEEP5G] InitSleep: MifWakeUpTime(%d)
Line 181: [SLEEP5G][WARNING] EnableDrxIntr: Unexpected Intr(%d)
Line 186: [SLEEP5G] EnableDrxIntr: Intr(%d)
Line 239: [SLEEP5G][WARNING] DisableDrxIntr: Unexpected Intr(%d)
Line 244: [SLEEP5G] DisableDrxIntr: Intr(%d), Pend(%d)
Line 284: [SLEEP5G][WARNING] ClearDrxIntr: Unexpected Intr(%d)
Line 289: [SLEEP5G] ClearDrxIntr: Intr(%d)
Line 405: [SLEEP5G] ForceSwSysValidEnable: ReqSleep(%d), Status(0x%X), XfrRefCnt(0x%x)
Line 432: [SLEEP5G] AbortSleep: ReqSleep(%d), Status(0x%X), SlpCnt(%d), Remained Time(%d)
Line 456: [SLEEP5G] StartSleep: SleepTime(%d), Status(%d)
Line 474: [SLEEP5G] SetOvrRcValue: OvrRcValue(%d), RefCnt(Ini: %d, Gat: %d)
Line 501: [SLEEP5G] SetFreqErrAccPeriod: Enable(%d), Period(%d)
Line 697: [SLEEP5G] UpdateSleepTime: SleepTime(%d) Remained Time(%d -> %d) SlpCtl(0x%x), SlpStatus(0x%x), SlpCnt(%d)
