Line 758: hCLP_SINR_Calc_4_detailLog0: cur_cfg=(i_rx<<12)|(i_fa<<8)|(i_tx<<4)|i_it 0x%08X, rscp_pwr_acc %d, iscp_pwr_acc %d, ml_rscp_i_acc %d, ml_rscp_q_acc %d, sinr %d
Line 759: hCLP_SINR_Calc_4_detailLog1: cur_cfg=(i_rx<<12)|(i_fa<<8)|(i_tx<<4)|i_it 0x%08X, sym0 %d, sym1 %d, sym2 %d, sym3 %d, sym4 %d
Line 760: hCLP_SINR_Calc_4_detailLog2: cur_cfg=(i_rx<<12)|(i_fa<<8)|(i_tx<<4)|i_it 0x%08X, mtg0 %d, mtg1 %d, mtg2 %d, mtg3 %d, mtg4 %d, mtg_sum %d
Line 866: hCLP_SINR_Calc_7_detailLog: cur_cfg=(i_rx<<12)|(i_fa<<8)|(i_tx<<4)|i_it 0x%08X, cpich_I_iir_val %d, cpich_Q_iir_val %d, cnt_pack %d, o_rscp %d, o_iscp_iir_val %d, o_sinrdB_iir_val %d
Line 890: hCLP_SINR_Calc_8_defaultLog: cur_cfg=(i_fa<<8)|(i_tx<<4) 0x%08X, sinr_cqi %d, sinr_cmb %d, sinr_rx0 %d, sinr_rx1 %d, sinr_rx2 %d, sinr_rx3 %d
Line 897: hCLP_SINR_Calc_8_defaultLog: cur_cfg=(i_fa<<8)|(i_tx<<4) 0x%08X, sinr_mode %d, sinr_lk_cmb %d, sinr_lk_rx0 %d, sinr_lk_rx1 %d, sinr_lk_rx2 %d, sinr_lk_rx3 %d
Line 906: hCLP_SINR_Calc_8_defaultLog: cur_cfg=(i_fa<<8)|(i_tx<<4) 0x%08X, sinr_cqi %d, sinr_cmb %d, sinr_rx0 %d, sinr_rx1 %d, sinr_rx2 %d
Line 912: hCLP_SINR_Calc_8_defaultLog: cur_cfg=(i_fa<<8)|(i_tx<<4) 0x%08X, sinr_mode %d, sinr_lk_cmb %d, sinr_lk_rx0 %d, sinr_lk_rx1 %d, sinr_lk_rx2 %d
Line 920: hCLP_SINR_Calc_8_defaultLog: cur_cfg=(i_fa<<8)|(i_tx<<4) 0x%08X, sinr_cqi %d, sinr_cmb %d, sinr_rx0 %d, sinr_rx1 %d
Line 925: hCLP_SINR_Calc_8_defaultLog: cur_cfg=(i_fa<<8)|(i_tx<<4) 0x%08X, sinr_mode %d, sinr_lk_cmb %d, sinr_lk_rx0 %d, sinr_lk_rx1 %d
Line 932: hCLP_SINR_Calc_8_defaultLog: cur_cfg=(i_fa<<8)|(i_tx<<4) 0x%08X, sinr_cqi %d, sinr_cmb %d, sinr_rx0 %d
Line 936: hCLP_SINR_Calc_8_defaultLog: cur_cfg=(i_fa<<8)|(i_tx<<4) 0x%08X, sinr_mode %d, sinr_lk_cmb %d, sinr_lk_rx0 %d
Line 1044: hCLP_SINR_ReCfg i_lms %d, cur_cfg=(i_rx<<12)|(i_fa<<8)|(i_tx<<4)|i_it 0x%08X, config_lms_clusters %d, i_pCPICH_Buf %d, i_pMTG %d, addr_parent_sinr_blk %d
