Line 133: ##[NR_POS] Send_L1C_L1C_POSCTRLR_MEAS_CNF: Tid(%d), InternalResult(%d)
Line 180: ##[NR_POS] Send PATH_CONFIG_REQ:: req_type(%d) num_of_cfg_cell(%d), scell_idx(%d), freq_info(%d, %d, %d), bw(%d)
Line 199: ##[NR_POS] SendSCCPathRelease: num_rel_cell(%d), cell_info_idx(%d), skip_rf_path_off(%d)
Line 214: ##[NR_POS]  Send_L1C_L1C_SCCCTRLR_RESOURCE_REQ to SCCCTRLR: Mode(%d)
Line 232: ##[NR_POS] Send_L1C_L1C_POSCTRLR_MEAS_IND: Tid(%d), LbsErrorCause(%d) CurrentSfn(%d)
