Line 107: ##[NR_MEAS] %s, MeasRatType(%d) Lte.MeasMode(%d) Utra.MeasMode(%d)
Line 111: ##[NR_MEAS] %s MeasMode(%d) StopbyDrxStatusInd(%d)
Line 142: ##[NR_MEAS] %s earfcn(%d) numOfCells(%d) AGC1(%d) AGC2(%d)
Line 154: ##[NR_MEAS] %s cellId(%d) cpType(%d) rsrp(%d) rsrq(%d) sinr(%d) TimingOffset(%d)
Line 170: ##[NR_MEAS] %s MeasRatType(%d) MeasMode(%d) ObjectId(%d) CarrierFreq(%d) NumResult(%d)
Line 180: ##[NR_MEAS] %s CellId(%d) Rssi(%d) Rscp(%d) EcNo(%d) TimingOffset(%d)
Line 246: ##[NR_MEAS] %s, #%d: CorrEnergy(%d), BeamTimingOffset(%d), CellId(%d) RxBeamIdx(%03x) lowEnCell(%d)
Line 264: ##[NR_MEAS]DSIFP] %d: %u, %u, %u, %u
Line 274: ##[NR_MEAS] Fail CNF for MeasMode(%d)!!
Line 401: ##[NR_MEAS] %s : msgSrcId(%d), module_meas_ongoing(%d), MeasStopType(%d)
Line 455: ##[NR_MEAS] PathConfig : RxBeamIdx(0x%03x)
Line 474: ##[NR_MEAS][TMS] TargetBand(%d) is TMS_Enabled Case!
Line 600: ##[NR_MEAS][3ABB][CONFIG] ConfigRxBeamIdx(0x%03x) vh_path(%d) //[MAP] module_map(%x) beam_map(%x) vh_map(%x)
Line 612: ##[NR_MEAS] gapStartRemainTime (%d) MinMeasUseTime (%d)
Line 626: ##[NR_MEAS] Send PATH_CONFIG_REQ:: req_type(%d) num_of_cfg_cell(%d), scell_idx(%d), freq_info(%d, %d, %d), bw(%d)
Line 656: ##[NR_MEAS] (ReleaseModule) module_op_type(%d) rx_beam_idx(0x%03x) vh_path(%d0 trig_mask_en(%d)
Line 662: ##[NR_MEAS][TMS] meas_4rx(%d) selected_module(%d) to SCC
Line 680: ##[NR_MEAS] SendSCCPathRelease: num_rel_cell(%d), cell_info_idx(%d), skip_rf_path_off(%d)
Line 699: ##[NR_MEAS][Multi-Meas] Send PathRelease path_count(%d)/configured_path_num(%d) alloc_freq(%d)
Line 704: ##[NR_MEAS][Multi-Meas] (%d)Path-Release for the all path!
Line 739: ##[NR_MEAS] SendModuleSwitchReq : SwType(%d) OpType(%d) RxbeamIdx(0x%03x) vh_path(%d)
Line 747: ##[NR_MEAS] Skip Send_L1C_L1C_SCCCTRLR_PATH_CONFIG_REQ_FOR_N2X, PathConfigForN2X(%d)
Line 770: ##[NR_MEAS] Send_L1C_L1C_SCCCTRLR_PATH_CONFIG_REQ_FOR_N2X, num_of_cfg_cell(%d) num_of_rel_cell(%d) CfgPurpose(%d)
Line 803: ##[NR_MEAS] %s, Send: Send_L1C_L1C_SCCCTRLR_RESOURCE_REQ to SCCCTRLR: Mode(%d), IsCoShedPossible(%d)
Line 819: ##[NR_MEAS] %s, Send: Send_L1C_L1C_SCCCTRLR_RESOURCE_REQ to SRCHCTRLR: Mode(%d)
Line 870: ##[NR_MEAS][SMTC_OPT] Update Smtc with estimated_value : Duration(%d) Offset(%d)
Line 885: ##[NR_MEAS][RBS] RBSType(%d), CandidateBeamMap(0x%x) RxBeamIdx(%03x)
Line 894: ##[NR_MEAS] Schedule_Sfn(%d), stmc_schedule_sfn(%d), Offset(%d), Duration(%d)
Line 906: ##[NR_MEAS] MeasMode(%d), NumCell(%d), Band(%d), Arfcn(%d), Numerology(%d), Period(%d), PathIdx(%d)
Line 918: ##[NR_MEAS] <MEAS_STOP> during the rxbeam_sweeping Prev_rbs(%d) -> INIT with BeamMap(%x)
Line 1031: ##[NR_MEAS] N2LMeas Timing Calc: mgta(%d) GapStartSfn(%d) GapStartSubframe(%d) GapStartOffset(%d) GapDurationSubframe(%d) serv_scs(%d)
Line 1087: ##[NR_MEAS] N2XMeas Schedule! Send: MEAS_REQ to MMCIFCTRLR, MeasMode(%d) MeasRatType(%d) CarrierFreq(%d) NumLteMeasInput(%d) ScellIdx(%d) MeasMethod(%d) N2XMeasStartIdx(%d)
Line 1102: ##[NR_SCC] Send_L1TUNNEL_L1C_4G_NR_INFO_REQ : gap_start_time(%d), gap_length(%d), rtg_diff(%d), gapstartinpaltime(%d)
Line 1152: ##[NR_MEAS] CalcCsiMeasBw PtA_arfcn(%u) PtA_Freq(%u) CsiRs_Scs(%d)
Line 1174: ##[NR_MEAS] CalcCsiMeasBw CellIdx[%d]: StartPRB(%u) nPRB(%u) FreqStart(%u) FreqEnd(%u)
Line 1189: ##[NR_MEAS] CalcCsiMeasBw INVALID! CellIdx[%d]: StartPRB(%u) nPRB(%u)
Line 1194: ##[NR_MEAS] CalcCsiMeasBw MeasBWFreqStart(%u) MeasBWFreqEnd(%u) BwInFreq(%u)
Line 1199: ##[NR_MEAS] CalcCsiMeasBw MeasBW_ceiled(%u) CenterFreq(%u) CenterArfcn(%u)
Line 1204: ##[NR_MEAS] Invalid CSI RS SCS (%d)
Line 1391: ##[NR_MEAS] Send PATH_CONFIG_REQ:: req_type(%d) num_of_cfg_cell(%d), scell_idx(%d), freq_info(%d, %d, %d), bw(%d)
