Line 149: Diablo Stationary FALSE: RSRP(%d)(%d) (Diff:%d,Threshold:%d), CINR(%d) (Threshold:%d)
Line 185: Diablo stationarycounter (%d)
Line 197: Not stationary Diablo(%d)
Line 205: High stationary Diablo(%d)
Line 212: Full stationary Diablo(%d)
Line 217: High stationary Diablo(%d)
Line 231: Diablo Stationary Mode Reset
Line 273: Diablo Stationary Mode Backoff
Line 306: Diablo Low Mobility FALSE: RSRP(%d)(%d) (Diff:%d,Threshold:%d)
Line 344: Diablo low mobility counter (%d)
Line 356: Not low mobility Diablo(%d)
Line 367: Light stationary Diablo(%d)
Line 372: Deep stationary Diablo(%d)
Line 381: Deep stationary Diablo(%d)
Line 390: Light stationary Diablo(%d)
Line 420: Diablo RobustDetection: stackId is invalid!
Line 454: Diablo Stationary FALSE: stored Pcell (%d), current Pcell (%d), SINR (%d)
Line 459: Diablo Stationary SCONE mobility = (%d), wifi_state = (%d)
Line 503: Diablo Stationary State(%d), Diablo RRC state(%d)
Line 510: Diablo Deep Stationary Disabled
Line 520: Diablo Overwrite Lassen's Stationary State(%d)
Line 533: Diablo Full Stationary Timer Expired (%d)
Line 559: (Diablo Stationary) feature Control(%d)
Line 577: (Diablo Stationary) init: fullStationaryEnable(%d), fullStationaryCounterThreshold(%d), fullStationaryTimerThreshold(%d), sinrThreshold(%d), deepEnable(%d), deepStationaryMultiplier(%d)
Line 608: Diablo Invalid DrxConfig(%d)
Line 611: Diablo Stationary Drx step(%d)
Line 655: Lte Rrm Stationary Qms flag is (%d)
Line 674: Invalid stackId (%d), return false directly in LteRrm_IsDiabloStationaryModeEnabled()
Line 683: Overall LTE Stationary Status is TRUE in LteRrm_IsDiabloStationaryModeEnabled()
