Line 96: [NRUECAPA] Registry Band.BwpSameNumerology(%d)
Line 110: [NRUECAPA] Registry Band.BwpDiffNumerology(%d)
Line 120: [NRUECAPA] Registry Band.MaxNumMimoLayersCbPusch(%d)
Line 130: [NRUECAPA] Registry Band.MaxNumSrsResourcePerSet(%d)
Line 140: [NRUECAPA] Registry Band.MaxNumSrsPortsPerResource(%d)
Line 157: [NRUECAPA] Registry Gen.SrsTxSwitch(%d)
Line 186: [NRUECAPA] HPUE for n%d is uncertified in current MCC %d
Line 191: [NRUECAPA] HPUE for n%d is certified in current MCC %d
Line 198: [NRUECAPA] Band(%d) cc(%d) PowerClassPerBand(%d)
Line 211: [NRUECAPA] Registry Fsdl.AddDmrsDlAlt(%d)
Line 222: [NRUECAPA] Registry Band.RateMatchLteCrs(%d)
Line 242: [NRUECAPA] Registry Switch.DssFeature(%d)
Line 254: [NRUECAPA] Registry NRSM.RQosSupport (%d)
Line 264: [NRUECAPA] Registry Gen.VoiceOverNrFrx (%d)
Line 280: [NRUECAPA] Registry Gen.DynamicPowerSharing (%d)
Line 290: [NRUECAPA] Registry Gen.OnDemandSIBConnected (%d)
Line 300: [NRUECAPA] Registry Gen.McgRLFRecoveryViaSCG (%d)
Line 311: [NRUECAPA] Registry HCOMMON.GCFMODE (%d)
Line 323: [NRUECAPA] Registry LTEL1.SAFEDV_ENABLE (%d)
Line 348: [NRUECAPA] Registry NR.CONFIG.MODE (%d), Stack Id (%d)
Line 373: [NRUECAPA] Registry NR.CONFIG.DEFAULT.PREF.MODE (%d), Stack Id (%d)
Line 381: [NRUECAPA] Registry LTENR.NSA.UECAPA.NR.GEN.DRX.CYCLE (%d)
Line 390: [NRUECAPA] Registry NRCAPA_DB_SETTING_MODE (%d)
Line 403: [NRUECAPA] Registry NRCAPA_DSDS_CHECKMODE (%d)
Line 424: [NRUECAPA] Registry %s.BASED.DSS.PLMN.ENABLE (%d)
Line 445: [NRUECAPA] Registry %s.DSS.PLMN.LIST.MODE (NSA)ALLOW=0x1/BLOCK=0x2, (SA)ALLOW=0x4/BLOCK=0x8 (0x%X)
Line 487: [NRUECAPA] Registry %s.DSS.PLMN.LIST.COUNT 'NSA'(%d)
Line 529: [NRUECAPA] Registry %s.DSS.PLMN.LIST 'NSA'List # %d MCC(%X%X%X) MNC(%X%X%X)
Line 568: [NRUECAPA] Registry %s.NR.SA.DSS.PLMN.LIST.COUNT 'SA' (%d)
Line 611: [NRUECAPA] Registry %s.NR.SA.DSS.PLMN.LIST 'SA' List # %d MCC(%X%X%X) MNC(%X%X%X)
Line 633: [NRUECAPA] Registry %s.BASED.NSA.NRCA.PLMN.ENABLE (%d)
Line 651: [NRUECAPA] Registry %s.NSA.NRCA.PLMN.LIST.MODE ALLOW=0x1/BLOCK=0x2  (0x%X)
Line 677: [NRUECAPA] Registry %s.BASED.SA.NRCA.PLMN.ENABLE (%d)
Line 695: [NRUECAPA] Registry %s.SA.NRCA.PLMN.LIST.MODE ALLOW=0x1/BLOCK=0x2  (0x%X)
Line 734: [NRUECAPA] Registry %s.NSA.NRCA.PLMN.LIST.COUNT 'NSA'(%d)
Line 780: [NRUECAPA] Registry %s.NSA.NRCA.PLMN.LIST.DATA 'NSA'List # %d MCC(%X%X%X) MNC(%X%X%X)
Line 815: [NRUECAPA] Registry %s.SA.NRCA.PLMN.LIST.COUNT 'SA'(%d)
Line 861: [NRUECAPA] Registry %s.SA.NRCA.PLMN.LIST.DATA 'SA'List # %d MCC(%X%X%X) MNC(%X%X%X)
Line 872: [NRUECAPA] Registry NRCAPA_SUPERSET_BANDCOMB_MODE (%d)
Line 882: [NRUECAPA] Registry Gen.IdleInactiveMeas (%d)
Line 893: [NRUECAPA] Registry NRCAPA_BANDTYPE_SETTING_MODE (%d)
Line 910: [NRUECAPA] Registry Write NRCAPA_TMOUSA_IS_SA_NRCA_SUPPORTED (%d)
Line 918: [NRUECAPA] Registry NRCAPA_TMOUSA_IS_SA_NRCA_SUPPORTED (%d)
Line 929: [NRUECAPA] Registry FEATURE_TMO_CARRIER_CONFIG is not defined (%d)
Line 940: [NRUECAPA] Registry TCS voiceOverNR (%d)
Line 950: [NRUECAPA] Registry TCS CRSRateMatching (%d)
Line 958: [NRUECAPA] FEATURE_TMO_CARRIER_CONFIG is not defined, Registry TCS %s (%d)
Line 971: [NRUECAPA] FEATURE_TMO_CARRIER_CONFIG is not defined, Registry TCS %s (%d)
Line 984: [NRUECAPA] FEATURE_TMO_CARRIER_CONFIG is not defined, Registry TCS %s (%d)
Line 997: [NRUECAPA] FEATURE_TMO_CARRIER_CONFIG is not defined, Registry TCS %s (%d)
Line 1010: [NRUECAPA] FEATURE_TMO_CARRIER_CONFIG is not defined, Registry TCS %s (%d)
Line 1026: [NRUECAPA] Registry SRVCC_ENABLED (%d)
Line 1043: [NRUECAPA] Registry GetSpType (0x%X)
Line 1060: [NRUECAPA] Registry GetMakeType (0x%X)
Line 1070: [NRUECAPA] Registry !LTENR.NSA.DRB.UL.SPLIT.SUPPORT (%d)
Line 1226: [NRUECAPA] Registry GetFciInfo (%d)
Line 1237: [NRUECAPA] Registry !NRCAPA_INACTIVE_STATE (%d)
Line 1247: [NRUECAPA] Registry !NRRRC_R17_BCS5 (%d)
Line 1251: [NRUECAPA] Registry !NRRRC_R17_BCS5 (%d) is ignored since rel is under 17
Line 1273: [NRUECAPA] Registry NRCAPA.Gen.VoiceFallbackInd (%d)
Line 1282: [NRUECAPA] Registry !NRCAPA_NON_SHARED_SPECTRUM_CH_ACCESS (%d)
Line 1291: [NRUECAPA] Registry !NRCAPA_SHARED_SPECTRUM_CH_ACCESS (%d)
Line 1301: [NRUECAPA] Registry !NRCAPA_NSA_HPUE_SUPPORTED (%d)
Line 1320: [NRUECAPA] IsNsaBandHpueSupportedBand: Band (%d)
Line 1358: [NRUECAPA] Registry !NRCAPA_NSA_HPUE_BANDS[%d] = (%d)
Line 1375: [NRUECAPA] Registry !NRCAPA_NRCA_SUPPORT_CHECK (%d)
Line 1385: [NRUECAPA] FEATURE_NR_R16_AGAP:: state(%d) var(%d)
Line 1400: [NRUECAPA] Registry !NRRRC.R16_T312_FAST_RECOVERY (%d)
Line 1412: [NRUECAPA] Registry FEATURE_NR_R16_UL_SEG (%d)
Line 1424: [NRUECAPA] Registry NRCAPA_MAX_UPLINK_DUTY_CYCLE_PC2_FR1 (%d)
Line 1432: [NRUECAPA] [NRFC] SUBFEATURE_NR_R15_SUB_BAND_N77 (%d)
Line 1442: [NRUECAPA] [NRFC] FEATURE_NR_R15_EXTENDED_BAND_N77 (%d)
Line 1452: [NRUECAPA] Registry NRCAPA_TEST_RESTRICT_FR1_TO_MAXCC (%d)
Line 1462: [NRUECAPA] Registry NRCAPA_TEST_RESTRICT_FR2_TO_MAXCC (%d)
Line 1472: [NRUECAPA] Registry NRCAPA_TEST_RESTRICT_TOTAL_MAXCC_FOR_TE (%d)
Line 1482: [NRUECAPA] Registry !NRRRC_R16_REDIRECT_AT_RESUME_BY_NAS_SUPPORT (%d)
Line 1499: [NRUECAPA] Registry NRRRC_R16_TX_DIVERSITY (%d)
Line 1509: [NRUECAPA] Registry NRRRC_R16_TWOSTEP_RACH (%d)
Line 1519: [NRUECAPA] Registry NRRRC_R16_HIGH_SPEED_TRAIN (%d)
Line 1530: [NRUECAPA] Registry NRCAPA_MAX_UPLINK_DUTY_CYCLE_PC1DOT5_MPE_FR1_R16 (%d)
Line 1549: [NRUECAPA] Registry PSS.LBS.NR_AGNSS_Profile (%d)
Line 1559: [NRUECAPA] Registry ds_PSS.LBS.NR_AGNSS_Profile (%d)
Line 1578: [NRUECAPA] Registry !NRCAPA.Gen.BwpSwitch (%d)
Line 1588: [NRUECAPA] Registry PSS.LBS.NR_Pos_Profile (%d)
Line 1598: [NRUECAPA] Registry NRCAPA_skipUplinkTxDynamic (%d)
Line 1609: [NRUECAPA] Registry NR_SUB6RF.TX.POWER_BOOSTING_PI2BPSK_BAND_LIST NUM(%d)
Line 1619: [NRUECAPA] Registry NR_SUB6RF.TX.POWER_BOOSTING_PI2BPSK_BAND_LIST #%d: n(%d)
Line 1631: [NRUECAPA] Registry NRRRC_R16_MEASUREMENT_REPORT (%d)
Line 1646: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxConfigNumberNZP_CSI_RS_PerCC (%d)
Line 1660: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxConfigNumberPortsAcrossNZP_CSI_RS_PerCC (%d)
Line 1675: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxConfigNumberCSI_IM_PerCC (%d)
Line 1690: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxNumberSimultaneousNZP_CSI_RS_PerCC (%d)
Line 1705: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_totalNumberPortsSimultaneousNZP_CSI_RS_PerCC (%d)
Line 1718: [NRUECAPA] Registry for fr1-fr2-Add/CSI-RS-IM-ReceptionForFeedback is DISABLED
Line 1727: [NRUECAPA] Registry for fr1-fr2-Add/CSI-RS-IM-ReceptionForFeedback is ENABLED
Line 1741: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxNumberPeriodicSRS_AssocCSI_RS_PerBWP (%d)
Line 1755: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxNumberAperiodicSRS_AssocCSI_RS_PerBWP (%d)
Line 1770: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxNumberSP_SRS_AssocCSI_RS_PerBWP (%d)
Line 1785: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_simultaneousSRS_AssocCSI_RS_PerCC (%d)
Line 1798: [NRUECAPA] Registry for fr1-fr2-Add/csi-RS-ProcFrameworkForSRS is DISABLED
Line 1806: [NRUECAPA] Registry for fr1-fr2-Add/csi-RS-ProcFrameworkForSRS is ENABLED
Line 1820: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxNumberPeriodicCSI_PerBWP_ForCSI_Report (%d)
Line 1835: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxNumberAperiodicCSI_PerBWP_ForCSI_Report (%d)
Line 1850: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxNumberSemiPersistentCSI_PerBWP_ForCSI_Report (%d)
Line 1865: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxNumberPeriodicCSI_PerBWP_ForBeamReport (%d)
Line 1880: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxNumberAperiodicCSI_PerBWP_ForBeamReport (%d)
Line 1895: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxNumberAperiodicCSI_triggeringStatePerCC (%d)
Line 1910: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_maxNumberSemiPersistentCSI_PerBWP_ForBeamReport (%d)
Line 1925: [NRUECAPA] Registry NRCAPA_FR1FR2ADD_simultaneousCSI_ReportsPerCC (%d)
Line 1938: [NRUECAPA] Registry for fr1-fr2-Add/csi-ReportFramework is DISABLED
Line 1950: [NRUECAPA] Registry for fr1-fr2-Add/csi-ReportFramework is ENABLED
Line 1960: [NRUECAPA] Registry NRRRC_maxLayersMIMO_Adaptation_R16 (%d)
Line 1971: [NRUECAPA] Registry NRCAPA_MEASUREMENT_ENHANCEMENT (%d)
Line 1981: [NRUECAPA] Registry NRCAPA_GEN_SUPPORTEDNUMBERTAG_NRDC (%d)
Line 1991: [NRUECAPA] Registry NRRRC_PDCP_SDU_MAX_SIZE (%d)
Line 2000: [NRUECAPA] Registry NRCAPA_TEST_BAND_COMB_MODE (%d)
Line 2008: [NRUECAPA] Registry NRRRC_R16_SCELL_DORMANCY_WITHIN_ACTIVETIME (%d)
Line 2016: [NRUECAPA] Registry NRRRC_R16_SCELL_DORMANCY_OUTSIDE_ACTIVETIME (%d)
Line 2024: [NRUECAPA] Registry NRRRC_PDSCH_MONITORING_ANY_OCCASION_WITH_SNAPGAP (%d)
Line 2032: [NRUECAPA] Registry !NRRRC_MPS_PRIORITY_INDICATION_R16 (%d)
Line 2041: [NRUECAPA] Registry !NRRRC_TMOUSA_ROAMING_SKIP (%d)
