Line 36: [RF ET] 3G mode(%d) PS mode(%s)
Line 57: [RF ET][RF SAPT] %s : ps-mode : (%d)
Line 96: [RF ET] PS mode(%s)
Line 114: [RF ET][RF SAPT] %s : Unknown ps-mode : %d
Line 142: [RF ET] RF_Drv_Init_ET_SAPT : %s CC(%d) Calmode(%d)
Line 147: [RF Drv] %s :: CC Struct -> CC_Type(%s), RAT(%s), Band(%s), ul_freq(%d), BW(%s), RFFE_PATH(%d) 
Line 149: [RF Drv] %s :: Parameter -> CC_Type(%s), RAT(%s), Band(%s), ul_freq(%d), BW(%s)
Line 151: [RF Drv] %s :: ET ver :  %d.%03d(0x%X)
Line 160: [RF Drv] %s :: UL_FREQ is not valid!! 
Line 178: [RF Drv] %s :: 3G ET Band num change : band_num(%d -> %d)
Line 200: [RF Drv] %s :: Parameter -> CC_Type(%d), RAT(%d), Band(%d), ul_freq(%d), uarfcn (%d) 
Line 231: [RF ET] RF_Drv_Set_ET_SAPT_Gaintable_To_DSP : %s CC(%d) %s Calmode(%d)
Line 248: [RF Drv] %s :: 3G ET Band num change : band_num(%d -> %d)
Line 300: [RF ET] RF_Drv_Clear_ET_SAPT_Init_Info : %s CC(%d)
Line 309: [RF ET] RF_Drv_Clear_DPD_Opeation_Mode : %s CC(%d)
Line 324: [RF ET] ET_S-APT_Active : %s CC(%d) Calmode(%d)
Line 331: [RF ET] ET/SAPT_Active : RF Cal mode
Line 355: [RF ET] ET/SAPT_Active : Check PA Range map of band(%d)
Line 408: [RF ET] ERROR :Get TX RFIC Gaintable ET_Mode : spi value err(%x)
Line 418: [RF ET] ERROR : Invalid TX Path (cc->txpath:%d, tx path:%d)
Line 441: [RF ET] ERROR :Set TX RFIC Gaintable ET_Mode : spi value err(%x)
Line 447: [RF ET] Set TX RFIC Gaintable ET_Mode : spi value addr (%03X) data (%08X)
Line 460: [RF ET] ERROR : Invalid TX Path (cc->txpath:%d, tx path:%d)
Line 482: [RF ET] ERROR :Set TX RFIC Gaintable ET_Mode : spi value err(%x)
Line 495: [RF ET] Set TX RFIC Gaintable ET_Mode : spi value addr (%03X) data (%08X)
Line 508: [RF ET] ERROR : Invalid TX Path (cc->txpath:%d, tx path:%d)
Line 524: [RF ET] ERROR :Set TX RFIC Gaintable ET_Mode : spi value err(%x)
Line 535: [RF ET] Set TX RFIC Gaintable ET_Mode : tx_path(%d), address(%x)
Line 569: [RF ET] Set TX Filter Path : rat(%d) cc_type(%d) tx_filter_path(%d)
