Line 185: [LTE_PATH] SetPathInfo: skip allocation for path modification procedure(CC%d)
Line 213: [LTE_PATH] SetPathInfo: cc(%d) pHdlr NULL early return, ST(%d)
Line 221: [LTE_PATH] SetPathInfo: CC(%d) path already allocated in MRA. Early return
Line 280: [LTE_PATH] SetPathInfo: CC(%d) Main Path allocation failed, ST(%d)
Line 315: [LTE_PATH] SetPathInfo: ERROR !!! CC(%d) MAIN_CC(%d) pHdlr of MAIN_CC is NULL
Line 330: [LTE_PATH] SetPathInfo: CC(%d) Div Path allocation failed, ST(%d)
Line 353: [LTE_PATH] SetPathInfo: mode(%d), cc(%d), mxr(%d), tdbuf(%d), output(%d), rtg(%d), demod(%d)
Line 379: [LTE_PATH] ReleasePathInfo: skip deallocation for path modification procedure(CC%d)
Line 415: [LTE_PATH] ReleasePathInfo: mode(%d), cc(%d), mxr(%d), td_buf(%d), output(%d), rtg(%d), demod(%d)
Line 453: [DEBUG_LOG] release_path(0x%X), skipBitMap(0x%X)
Line 470: [DEBUG_LOG] release_path(0x%X), skipBitMap(0x%X)
Line 490: [LTE_PATH] PartialReleasePathInfo: mode(%d), cc(%d), release_path(0x%X), td_buf(%d), output(%d), rtg(%d), demod(%d)
Line 513: [LTE_PATH] HALSC_ActDeactPathInfo: Mode(%d), registry_en(%d)
Line 549: [LTE_PATH] UpdatePathInfo: CC(%d) pHdlr NULL, invalid case
Line 554: [LTE_PATH_DEBUG] MRA_BW(%d), BW(%d)
Line 557: [LTE_PATH] UpdatePathInfo: skip path update since bw info is not changed 
Line 560: [LTE_PATH] Update pHdlr earfcn info bef(%d) -> aft(%d)
Line 591: [LTE_PATH] UpdatePathInfo: CC(%d) Main Path info update failed, stackID(%d)
Line 605: [LTE_PATH] UpdatePathInfo: mode(%d), cc(%d), bw(%d)
Line 655: [LTE_PATH] FindCcIdxFromPathMngr: mode(%d), earfcn(%d), MXR_CC(%d), ST(%d)
Line 732: [LTE_PATH] AllocCcIdxFromPathMngr: Mxr Path allocation failed, ST(%d)
Line 757: [LTE_PATH] AllocCcIdxFromPathMngr: ERROR !!! HALSC_PATH_4RX pHdlr of main_cc(%d) is NULL, ST(%d)
Line 773: [LTE_PATH] AllocCcIdxFromPathMngr: Div Mxr Path allocation failed, ST(%d)
Line 787: [LTE_PATH] AllocCcIdxFromPathMngr: Div Mxr Path already allocated, ST(%d)
Line 802: [LTE_PATH] AllocCcIdxFromPathMngr: mode(%d), earfcn(%d), MXR_CC(%d), ST(%d)
Line 852: [LTE_PATH] HALSC_UpdateDvfsInfo: on_off(%d)
Line 930: [SC] CC%d: earfcn(%d), resv/type(%02d), pair_cc(0x%04x), tdp_state(%d), pair_num/rf_path/rx_mode(%x), slo_pair(%x), tdbuf/output/rtg/demod(0x%x)
Line 952: Abnormal dmxr_freq_value!! [SC] CC%d: pair_num(%d), dmxr_freq_value(%d)
Line 996: [LTE_PATH] PathModificationByNr before: MXR(%d), DEMOD(%d), BB_RTG(%d), TDBUF(%d), OUTPUT(%d)
Line 998: [LTE_PATH] PathModificationByNr before: DIV MXR(%d), DEMOD(%d), BB_RTG(%d), TDBUF(%d), OUTPUT(%d)
Line 1016: [LTE_PATH] slo_config_cc(%d), slo_cell_num (%d)
Line 1059: [LTE_PATH] PathModificationByNr after: MXR(%d), DEMOD(%d), BB_RTG(%d), TDBUF(%d), OUTPUT(%d)
Line 1061: [LTE_PATH] PathModificationByNr after: DIV MXR(%d), DEMOD(%d), BB_RTG(%d), TDBUF(%d), OUTPUT(%d)
