Line 162: L2LMACTXENC_L2LMACTX_ENCODE_IND EncIdx[%d] MacEntity[%d]
Line 168: [L2LMACTXENC][E] L2LMACTXPROXY_L2LMACTXENC_TIMER_IND_T - AllocMsg Fail MacEntity[%d]
Line 181: skip L2LMACTXPROXY_L2LMACTXENC_TIMER_IND MacEntity[%d]
Line 214: [E] Full UL Retx AckNack WD[%d] RD[%d]
Line 235: [L2LMACTXENC][E] L2HRLCRETX_L2LMACTXENC_PROC_ACKNACK_IND - AllocMsg Fail
Line 252: [L2LMACTXENC][E] L2HRLCRETX_L2LMACTXENC_PROC_ACKNACK_IND - SendMsg Fail
Line 78: [L2LMACTXENC][E] L2LMACTXPROXY_L2LMACTXENC_TIMER_IND_T - SendMsg Fail
