Line 78: ##[NR_SCC] NR RF INFO : idx(%d), bitmask(0x%x), band(%d), freq(%d), bw(%06d), prx_bitmask(0x%x), rx_beam_idx(0x%x)
Line 146: ##[NR_SCC][WARNING] InitPath : Abnormal rf_path_idx(%d)
Line 150: ##[NR_SCC] InitPath : rf_path_idx(%d)
Line 196: ##[NR_SCC] ReadRegModuleSwitchMode : set m_module_switch_mode(%d -> %d)
Line 211: ##[NR_SCC] GetDrxMeasMode(%d)
Line 217: ##[NR_SCC] SetDrxMeasMode(%d -> %d)
Line 235: ##[NR_SCC][WARNING] CheckRfPathIdxBoundary : Abnormal rf_path_idx(%d)
Line 250: ##[NR_SCC][WARNING] CheckRfOn : Abnormal rf_path_idx(%d)
Line 261: ##[NR_SCC] CheckRfOn(%d)
