Line 150: [NR IPC] PHY_L1C_IPC_IF_TEST_IND, core(%d), cmd(%d)
Line 222: [NR IPC] PHY_L1C_LCPU_INIT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx_bmp(%d), processor_idx_bmp(%d), hw_demod_idx_bmp(%d), NrStatus(%d), StackId(%d)/CellGroup(%d)/PcellCc(%d)
Line 258: [Debug] [ST0]valid/coreId(%d/%d/0x%x), [ST1]valid/coreId/PcellCcBitBap(%d/%d/0x%x)
Line 262: not matched core id bitmap(0x%x)
Line 293: [NR IPC] PHY_L1C_LCPU_INIT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx_bmp(%d), processor_idx_bmp(%d), hw_demod_idx_bmp(%d), NrStatus(%d), StackId(%d)/CellGroup(%d)/PcellCc(%d)
Line 302: (I)Received CcInfoBitmap Table in HEX (CC_Idx_bmp/Processor_Idx_bmp/Demod_Idx_bmp) 0:(0x%X), 1:(0x%X), 2:(0x%X), 3:(0x%X), 4:(0x%X), 5:(0x%X), 6:(0x%X)
Line 306: (I)Received CcInfoBitmap Table in HEX (CC_Idx_bmp/Processor_Idx_bmp/Demod_Idx_bmp) 7:(0x%X), 8:(0x%X)
Line 320: Skip to update CC Info Table. cc_idx_bmp(%d)
Line 338: (F)Fail to update CC Info Table(CC_%d), cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 348: (I)CC Info table : ccIdx(%d), processorIdx(%d/%d), hwDemodIDx(%d), cCoffset(%d), CcBitMapInProcessor(0x%x), GetNrCcOn_Bitmap(0x%x), enableCcBitmap(0x%x)
Line 392: =====[NR_IPC]===== NrLcpuInit REQ: Pid(%d), CcOffset(%d), CcIndex(%d), MsgId(%d) %d
Line 423: [Debug] [ST0]valid/coreId(%d/%d/0x%x), [ST1]valid/coreId/PcellCcBitBap(%d/%d/0x%x)
Line 427: not matched core id bitmap(0x%x)
Line 445: SetNrScellStackInfo CcIdx: %d, stackInfo: %d, GetNrCcOn_Bitmap:0x%x, SetNrSwRecoveryManageCc: %d
Line 456: SW_RESET Sub core -  LteCoreOneActiveStatus(%d) NrCcOn_Bitmap (0x%x)
Line 474: [NR IPC] L1C_PHY_LCPU_INIT_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d), cc_idx(%d)
Line 500: (F)Error in SetShmInfo: ShmIndex%d
Line 515: [MDFS]LcpuInitReq, MdfsNrFlag(%d)
Line 525: [DEBUG] enableCcBitmap %d cc_offset %d GetCcBitmapHandledOn %d
Line 568: [NR IPC] PHY_L1C_LCPU_RELEASE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 672: [NR IPC] IPC_NR_STATUS_IND_REQ Initialize(to LTE), BM_SrcCcForCnfMsg(%d)
Line 729: [NR IPC] PHY_L1C_LCPU_STORE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 780: [NR IPC] PHY_L1C_LCPU_RESTORE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 857: [NR IPC] PHY_L1C_CELLGROUP_COMMON_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 890: [NR IPC] L1C_PHY_CELLGROUP_COMMON_CONFIG_CNF, BM_SrcCcForCnfMsg(%d) BM_StackId(%d) BM_CellGroupId(%d)
Line 932: [NR IPC] NR_ServingCellConfig_csi_MeasConfig is OFF
Line 962: [DEBUG] SysParamChangeReqToProc: cc_offset(%d) CMD_INFO(%d) EVENT_INFO(%d) changeval(%d) isRestore(%d)
Line 1066: [NR IPC] PHY_L1C_CELLGROUP_PCELL_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1096: [NR IPC] L1C_PHY_CELLGROUP_PCELL_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
Line 1134: [NR IPC] SKIP NrRcvIpcHndlr_CellGroupScellConfigReq LCPU CORE: 0x%x, NR status: 0x%x 
Line 1144: [NR IPC] PHY_L1C_CELLGROUP_SCELL_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1213: [NR IPC] PHY_L1C_SCELL_ACTDEACT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1229: [NR IPC] Force to change BW from over NUM_NR_SYS_BW ->(%d)
Line 1298: [NR IPC] PHY_L1C_OHC_MAX_TX_ANT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1310: =====[NR_IPC]===== PHY_L1C_OHC_MAX_TX_ANT_REQ: CcIndex(%d), MsgId(%d)
Line 1364: [NR IPC] PHY_L1C_OHC_SCC_CQI0_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1432: [NR IPC] PHY_L1C_SIB1_PCELL_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1458: [NR IPC] L1C_PHY_SIB1_PCELL_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
Line 1500: [NR IPC] PHY_L1C_TDP_CONFIG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1544: [NR IPC] PHY_L1C_RXMODE_CHANGE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1645: [NR IPC] PHY_L1C_DATA_INACTIVE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1715: [NR IPC] PHY_L1C_UL_ACTIVATION_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1740: [NR IPC] skip carrierFreqUL=%d, carrierBandwidthUL = %d
Line 1775: [NR IPC] PHY_L1C_TX_SWAP_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1835: [NR IPC] PHY_L1C_DL_NTM_MEASURE, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1886: [NR IPC] IPC_NR_GAP_CTRL_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1936: [NR IPC] PHY_L2_MAC_RESET_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 1980: [MDFS]MacResetInd, Exception OFF, MdfsNrFlag(%d)
Line 2061: [NR IPC] PHY_L2_MAC_RACH_CONTROL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2080: [NR IPC] PHY_L2_MAC_RACH_CONTROL_IND, cmd(%d), rach cause(%d)
Line 2127: [NR IPC] IPC_NR_RNTI_CONTROL_IND_t, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2179: [NR IPC] PHY_PHY_RNTI_CFG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2231: [NR IPC] PHY_PHY_RACH_TX_INFO_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2279: [NR IPC] PHY_PHY_RA_CrTimerStop_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2326: [NR IPC] PHY_PHY_RA_CrStateUpdate_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2376: [NR IPC] PHY_PHY_RA_CFG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2425: [NR IPC] PHY_PHY_RA_CrStateReport_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2477: [NR IPC] PHY_PHY_RA_CrStateReport_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2520: [NR IPC] PHY_PHY_SPS_CLEAR_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2570: [NR IPC] PHY_L2_TA_CONTROL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2621: [NR IPC] PHY_L2_TA_Timer_Ind, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2674: [NR IPC] PHY_L1C_DRX_CMD_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2726: [NR IPC] PHY_L1C_CHECK_TIME_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), timerType(%d)
Line 2849: [NR IPC] PHY_L2_PUCCH_SPATIAL_REL_ACT_DEACT_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2900: [NR IPC] PHY_L2_SP_SRS_ACT_DEACT_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 2952: [NR IPC] PHY_L2_SP_CSIRS_CSIIM_ACT_DEACT_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3004: [NR IPC] PHY_L2_A_CSI_TRG_SUBSET_SUBSEL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3105: [NR IPC] PHY_L2_PDSCH_TCI_STATES_ACT_DEACT_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3154: [NR IPC] PHY_L2_PDCCH_TCI_STATE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3203: [NR IPC] PHY_L2_PUCCH_SRS_RELEASE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3255: [NR IPC] PHY_L2_UE_BEAMLOCK_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3330: [NR IPC] PHY_L1C_MIB_ACQ_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3401: [NR IPC] PHY_L1C_QSLEEP_CTRL_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3457: [NR IPC] PHY_L1C_QSLEEP_CTRL_REQ BY DCI K0, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d) QsleepCtrl:%d 
Line 3505: [NR IPC] PHY_L1C_SYS_PARAM_CHANGE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3529: [NR IPC](CC_%d) L1C_PHY_SYS_PARAM_CHG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d) : Fast CNF at special case
Line 3580: [NR IPC] PHY_L1C_BWP_CHANGE_DONE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3642: [NR IPC] PHY_L1C_SIB1_ACQ_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), cmd(%d)
Line 3688: [NR IPC] L1C_PHY_SIB1_ACQ_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
Line 3731: [NR IPC] PHY_L1C_SIBX_ACQ_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3767: [NR IPC] L1C_PHY_SIBX_ACQ_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
Line 3808: [NR IPC] PHY_L1C_MEAS_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3854: [NR IPC] PHY_L1C_MTC_INFO_IND, FreqRange(%d) RsType(%d) SmtcSfn(%d) RxBeamIdx(0x%x) smtc_duration(%d) ssbbit[0/1](0x%x/0x%x)
Line 3903: [NR IPC] NrRcvSelfIpcHndlr_MtcInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 3953: [NR IPC] PHY_L1C_DRX_CFG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4045: [NR IPC] PHY_L1C_DRX_WAKEUP_INIT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4212: [NR IPC] PHY_L1C_SET_TIMING_UPDATE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4265: [NR IPC] PHY_PHY_NR_LTE_TXPOWER_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4316: [NR IPC] PHY_L1C_SAR_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4367: [NR IPC] PHY_L1C_NTM_MODE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4425: [NR IPC] PHY_L1C_NTM_SET_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4480: [NR IPC] PHY_L1C_NTM_TX_POWER_SWEEP_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4528: [NR IPC] PHY_L1C_PHY_TEST_MODE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4581: [NR IPC] PHY_L1C_TMU_CTRL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4630: [NR IPC] PHY_L1C_VONR_STATUS_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 4677: [NR NTM] NrRcvSelfIpcHndlr_NtmMeasureReport: PHY_PHY_NTM_MEASURE_REPORT
Line 4685: [NR NTM] NrRcvSelfIpcHndlr_NtmMeasureReport: cc_offset = %d cc_idx = %d TARGET_CC_BITMAP.cc_idx = 0x%x, 
Line 4691: [NR NTM] =====[NR_IPC]===== PHY_PHY_NTM_MEASURE_REPORT: CcIndex(%d), MsgId(%d)
Line 4905: =====[NR IPC_SELF]===== (RCV) PHY_PHY_UPDATE_CC_TPUT_RATIO_IND: CcIndex(%d), MsgId(%d)
Line 4950: =====[NR_IPC_SELF]===== (RCV) PHY_PHY_UPDATE_CC_TPUT_RATIO_IND_CNF: CcIndex(%d), MsgId(%d)
Line 4986: [NR IPC] PHY_PHY_ServingSSBChangeInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 5119: [NR IPC] PHY_PHY_ThermalLevelMeasure, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), level(%d)
Line 5973: [NR IPC] PHY_L1C_STORE_PHY_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), validflag(%d), drxType(%d), targetCcIdx(%d)
Line 5988: [NR IPC] Change Target CC indx : drxType(%d), targetCcIdx(%d)
Line 6007: [NR IPC] L1C_PHY_STORE_PHY_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
Line 6054: [NR IPC] PHY_L1C_RESTORE_PCELL_PHY_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d) validflag_bmp(%d)
Line 6158: [NR IPC] L1C_PHY_RESTORE_PCELL_PHY_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
Line 6203: [NR IPC] PHY_L1C_TX_SUSPEND_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 6254: [NR IPC] PHY_L1C_TX_RESUME_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 6304: [NR IPC] PHY_L1C_CONN_PRIO_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 6353: [NR IPC] PHY_L1C_PHY_RESUME_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 6415: [NR IPC] PHY_L1C_SSB_PATHCTRL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), Cmd : %d
Line 6448: [NR IPC] PHY_L1C_NR_EVENT_REPORT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), Type(%d)
Line 6480: Error in NrRcvIpcHndlr_NrEventReportReq: type(%d)
Line 6497: [NR IPC] L1C_PHY_NR_EVENT_REPORT_CNF, BM_SrcCcForCnfMsg(%d) BM_StackId(%d) BM_CellGroupId(%d)
Line 6547: NrDrEventReqToProc hit(DS mode) in pcell, DrDsState = %d 
Line 6550: NrDrEventReqToProc DrDsState = %d 
Line 6832: [NR IPC] PHY_PHY_RACH_ASLOT_INFO2HBF_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 6864: [NR IPC] PHY_PHY_PCELL_SSB_IDX_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 6911: [NR IPC] PHY_PHY_LCPU_RELEASE_READY, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 6965: [NR IPC] releaseReady disable CC Interrupt cc:%d 
Line 6978: [NR IPC] L1C_PHY_LCPU_RELEASE_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
Line 6991: [MDFS]LcpuRelease, MdfsNrFlag(%d), isPcellMcg(%d) cell_group(%d)
Line 7007: [MDFS]LcpuRelease, Exception OFF, MdfsNrFlag(%d)
Line 7026: [NR IPC] releaseReady clear Ccinfo coreID:A%d cc:%d ccbitmap:0x%x 
Line 7046: [Debug] [ST0]valid/coreId(%d/%d/0x%x), [ST1]valid/coreId/PcellCcBitBap(%d/%d/0x%x)
Line 7061: [NR IPC] IPC_NR_STATUS_IND_REQ Release (to LTE), BM_SrcCcForCnfMsg(%d)
Line 7086: corePowerDown = %d, %d, ccBitmapforCoreId = %d
Line 7089: powerDown coreId = %d
Line 7164: =====[NR_IPC_SELF]===== (RCV) PHY_PHY_NR_HBUF_UPDATE_REQ: MsgId(%d)
Line 7240: [NR IPC] PHY_PHY_BWP_SWITCHING_CTRL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 7288: [NR IPC] PHY_PHY_BWP_TIMER_STOP_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 7376: [NR IPC] PHY_PHY_CE_SCRAMBSEQ_CALC_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 7419: [NR IPC] PHY_PHY_CCH_RECONFIG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 7462: [NR IPC] NrRcvSelfIpcHndlr_DciLengthCalculationInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 7504: [NR IPC] NrRcvSelfIpcHndlr_HashCalculationInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 7761: =====[NR_IPC_SELF]===== NrRcvSelfIpcHndlr_MeasDoneInd, cc_idx: %d
Line 7796: [NR IPC] NrRcvSelfIpcHndlr_SysParamchgCfgdone, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 7852: [NR IPC] NrRcvSelfIpcHndlr_ScellStatusUpdateInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 7904: [NR IPC] NrRcvSelfIpcHndlr_ScellTxStatusUpdateInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 7950: [NR IPC] NrRcvSelfIpcHndlr_ScellDciLengUpdateInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 7991: [NR IPC] NrRcvSelfIpcHndlr_PrachStartInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8036: [NR IPC] NrRcvSelfIpcHndlr_PrachTransInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8083: [NR IPC] NrRcvSelfIpcHndlr_ScellSlotConfigInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8129: [NR IPC] NrRcvSelfIpcHndlr_PostProcSysParamChangeInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8175: [NR IPC] NrRcvSelfIpcHndlr_PostProcScellConfigInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8219: [NR IPC] NrRcvSelfIpcHndlr_PostProcScellActInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8302: [NR IPC] NrRcvSelfIpcHndlr_StrSettlingInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8348: [NR IPC] PHY_L1C_PLL_JITTER_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8398: [NR IPC] NrRcvIpcHndlr_NrMeasModeCtrlReq, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8452: [NR IPC] PHY_L1C_NTM_ETSM_DISABLE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8503: [NR IPC] PHY_L1C_NTM_DPS_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8552: [NR IPC] PHY_L1C_TX_DB_CLEAR_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8603: [NR IPC] PHY_L1C_TX_DB_UPDATE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8655: [NR IPC] NrRcvSelfIpcHndlr_SibxSchedChange, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8754: [NR IPC] PHY_PHY_CalStartN0, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8852: [NR IPC] NrRcvSelfIpcHndlr_SiDrxCnf, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8896: [NR IPC] NrRcvSelfIpcHndlr_SiReadInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 8995: [NR IPC] NrRcvSelfIpcHndlr_TciSsbMappingInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9038: [NR IPC] NrRcvSelfIpcHndlr_Cdrx_storeInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9118: [NR IPC] NrRcvSelfIpcHndlr_MdSwitchInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9167: [NR IPC] NrRcvSelfIpcHndlr_ClAitStartReq, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9207: [NR IPC] NrRcvSelfIpcHndlr_AitFailInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9248: ###[TSIC][NR IPC] NrRcvIpcHndlr_TsicInitReq, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9366: [NR IPC] GrantSkip NrRcvSelfIpcHndlr_GrantSkipInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9406: [NR IPC] GrantSkip NrRcvSelfIpcHndlr_GrantSkipCnf, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9451: [NR IPC] SW_RESET NrRcvSelfIpcHndlr_SwResetInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9519: [NR IPC] SW_RESET PHY_PHY_LTE_EVENT_REPORT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9561: [NR IPC] PHY_PHY_TCI_DISABLE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9603: [NR IPC] PHY_PHY_PDP_RESET_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9653: [NR IPC] NrRcvIpcHndlr_NrMonitorInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9704: [NR IPC] PHY_PHY_CLEANING_OPERATION_FOR_BWP_SWITCHING, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), EventType(%d)
Line 9772: [NR IPC] PHY_PHY_DCI_QSLEEP_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), pdsch_without_dci(%d)
Line 9820: [NR IPC] PHY_PHY_AGAP_MIBCFG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), AgapFlag(%d)
Line 9874: [NR IPC] PHY_PHY_AGAP_SIB1CFG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9879: AgapFlag(%d) // Target[syscmd(%d), sysevent(%d), chgVal(%d)] // Serving[syscmd(%d), sysevent(%d), chgVal(%d)]
Line 9959: [NR IPC] NrRcvSelfIpcHndlr_EarlyDrxConfirmInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 9996: [NR IPC] NrRcvSelfIpcHndlr_SpsDciCheckReq, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
Line 10043: [NR IPC] PHY_L1C_TX_SYSTEM_INIT_IND
Line 10080: [NR IPC] PHY_L1C_TX_PARAM_UPDATE_IND
Line 10116: [NR IPC] PHY_L1C_TX_MAXPOWER_REQ
Line 10138: [NR IPC] NrRcvSelfIpcHndlr_NrCdrxDciInfoInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
