Line 56: SMPF Timer(m_pTimer) null. (0x%x)
Line 74: SMPF Timer invalid SrcType req on create. (0x%x, SrcType:%u)
Line 92: SMPF Timer Created. (0x%x)
Line 122: FT is deleting. no need remove expired timer message
Line 149: SMPF Timer Warning: Stop on other OT. (0x%x)
Line 152: SMPF Timer Exception: AutoDelTmr shared-obj is not allowed. (0x%x)
Line 161: SMPF Timer Stop requested on ISR context. (0x%x)
Line 210: SMPF Timer State(After Stop): %u->%u. (0x%x)
Line 222: SMPF Timer Warning: Start on other OT. (0x%x)
Line 225: SMPF Timer Exception: AutoDelTmr shared-obj is not allowed. (0x%x)
Line 233: SMPF Timer no operation with 0 repetiton (0x%x)
Line 241: SMPF Timer Start is requested on ISR context. (0x%x)
Line 291: SMPF Timer Started. (0x%x), (%u->%u), Duration = %u, IsUs = %u, pPara = 0x%x, NumRepeat = %u
Line 477: SMPF Timer State(Before Delete): %u. (0x%x, 0x%x)
Line 491: SMPF Timer(Context) null. (0x%x)
Line 513: SMPF Timer(Context) null. (0x%x)
Line 693: Error!! SMPF Timer SetUsRunDuration Failed. (0x%x, ostimer:0x%x)
Line 735: Error!! SMPF Timer CalculateExpiryTime Failed. (0x%x, ostimer:0x%x)
Line 768: SMPF Timer(MSG) Created. (0x%x)
Line 817: SMPF Timer(CB) Created. (0x%x)
Line 825: SMPF Timer(ISR) Created. (0x%x)
Line 833: SMPF Timer State(Before Delete): %u. (0x%x)
Line 876: call back timer test function!!!!!!!!!!!!!!!!!!!!!!!!
