Line 132: [GL1 Error] Unsupported cipher algorithm (%d)
Line 193: [CipLdTds] command(%x), key0(%x), key1(%x), key2(%x), key3(%x)
Line 195: [CipLdTds] key4(%x), key5(%x), key6(%x), key7(%x)
Line 307: [cipherGoTds] command(%x), T1(%d), T2(%d), T3(%d), cdHandle(%x), frameNumber(%d)
Line 350: [SqIniCipherInitialise] l1DownlinkCpHandle(0x%x) l1UplinkCpHandleb(0x%x)
Line 358: [SqIniCipherBufferRelease] l1DownlinkCpHandle(0x%x) l1UplinkCpHandleb(0x%x)
