Line 97: [IRAT U2L] uphy_CEutraMeasureStepFsm_step: EARFCN (%d), numOfEutraCells (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
Line 97: [IRAT U2L] uphy_CEutraMeasureStepFsm_step: EARFCN (%d), numOfEutraCells (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
Line 110: [IRAT U2L] uphy_CEutraMeasureStepFsm_step: cellId=%d, start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
Line 110: [IRAT U2L] uphy_CEutraMeasureStepFsm_step: cellId=%d, start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
Line 175: S0  ### Critical Error UmtsMessagePtr mMsg = NULL (%d)
Line 175: S0  ### Critical Error UmtsMessagePtr mMsg = NULL (%d)
Line 241: [IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d), RSRP (%d), RSRQ (%d)
Line 241: [IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d), RSRP (%d), RSRQ (%d)
Line 248: S0  ### Critical Error eutraCellMeasResultsList = NULL (%d)
Line 248: S0  ### Critical Error eutraCellMeasResultsList = NULL (%d)
Line 258: [IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
Line 258: [IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
