Line 101: [IRAT U2L] uphy_CEutraCellSearchStepFsm_step: EARFCN (%d), start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
Line 101: [IRAT U2L] uphy_CEutraCellSearchStepFsm_step: EARFCN (%d), start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
Line 105: [IRAT U2L] uphy_CEutraCellSearchStepFsm_step: EARFCN (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
Line 105: [IRAT U2L] uphy_CEutraCellSearchStepFsm_step: EARFCN (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
Line 172: S0  ### Critical Error UmtsMessagePtr mMsg  = NULL (%d)
Line 172: S0  ### Critical Error UmtsMessagePtr mMsg  = NULL (%d)
Line 239: [IRAT U2L] uphy_CEutraCellSearchStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d)
Line 239: [IRAT U2L] uphy_CEutraCellSearchStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d)
Line 246: S0  ### Critical Error eutraCellSearchResultsList  = NULL (%d)
Line 246: S0  ### Critical Error eutraCellSearchResultsList  = NULL (%d)
Line 258: [IRAT U2L] uphy_CEutraCellSearchStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
Line 258: [IRAT U2L] uphy_CEutraCellSearchStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
