Line 131:  NORMAL Initialisation of <GmmCellIndicationt> 
Line 170:  GSM to UMTS Initialisation of <GmmCellIndicationt> 
Line 176:  UMTS to GSM Initialisation of <GmmCellIndicationt> 
Line 183:  Unknown Initialisation Type (%x) in mm_InitGmmCellIndication 
Line 214: UMTS Moved from No PS service to In PS serviec
Line 229: UMTS Current and Sim RAI are same ChangeinRai : False
Line 233: UMTS Current and Sim RAI are different ChangeinRai : TRUE
Line 339: CnCommonNasInfo Absent !!!! PLMN Changed without LAC changing?! Msg ignored in  mm_UpdateAndProcessGmmCellData 
Line 375: SIB derived CN information does not include PS domain specific SI (i.e. RAC and network mode)...assuming PS domain currently unavailable in selected cell
Line 388: Network sourced CN information does not include PS domain specific SI (i.e. RAC and network mode)...assuming PS domain currently unavailable in selected cell
Line 445: PLMN identity not included - using previously stored value
Line 470: CN Common SI (LAC) not included - using previously stored value
Line 475: SIB derived CN information does not include CN common GSM-MAP NAS SI (i.e. LAC)...
Line 503: PLMN identity not included - using previously stored value
Line 526: CN Common SI (LAC) not included - using previously stored value
Line 568:  Setting GMM_RAI_CHANGED_FLG_...
Line 637:  URRC_MM_NO_CELL_IND....
Line 675: Moved from PS no service to PS in Service
Line 682: GSM Current and Sim RAI are same ChangeinRai : False
Line 686: GSM Current and Sim RAI are different ChangeinRai : TRUE
Line 718: mm_GmmCellData.CellChange is set to FALSE.
Line 723: mm_GmmCellData.CellChange is set to TRUE.
Line 744: NwExtUtbf= %d
Line 775: EncodedSizeinBits -> %d 
Line 776: Access Technology changed...
Line 780: Access Technology did not change...
Line 798:  CR 98 :Set : mm_SetGmmFlag....
Line 804:  CR 98 :Clear : mm_SetGmmFlag....
Line 840:  ....cell does not support PS.
Line 846: ....ignored as DataResumption == GRR_GMM_NO_RESUMPTION.
Line 865:  GRR_MM_NO_CELL_IND....
Line 893: Because of Power off detach or PS detach PS off and  GMM Deregistered we skip GmmCellData process.
Line 944:  ERROR: unknown TypMsg 0x%02X in MM_UMTS_RAT_MODE 
Line 989:  ERROR: unknown TypMsg 0x%X in MM_GSM_RAT_MODE 
Line 1012: discard GMM SM EST REQ
Line 1040: SameRrConnexFailAction = %d, ProcessCellInfo =%d 
Line 1067: Current serving cell is not supportting PS services(or barred), GMM_GPRS_ATTACH_FLG = FALSE
Line 1071: LAI is not changed, so send Registration ind to NS for PS barred status
Line 1076: NO CELL IND, keep GMM_GPRS_ATTACH_FLG == TRUE
Line 1082: Current serving cell is supporting PS services and UE GMM REG/UPDATED, GMM_GPRS_ATTACH_FLG = TRUE
Line 1086: Send reg status ind(PS not supported -> supported) on recovery to prev reg RAI
Line 1123: GMM shall process new cell details now...
Line 1129: GMM shall process new Unit Data Ind details now...
Line 1136: NMO-1 GMM shall process new cell details now. Received GSM CELL IND ..
Line 1158: GMM shall not process new cell details now...shall process on completion of MM location updating procedure
Line 1170: GMM shall not process new cell details...CSFB call about to initiated
Line 1178: In MM_WAIT_FOR_RR_CON_LOC_UPD state LAI changed, After Cell indication LAU should be initiated..GMM shall not process new cell details now till Perform LAU procedure
Line 1193: GMM shall not process new cell details...URRC_MM_CELL_IND received in while a PS signalling connection exists
Line 1200: GMM shall process new cell details now...
Line 1229: GMM processing of new cell details in %s in mm_ProcessGmmCellInformation
Line 1324: Attempting to go back to GMM State before Supension...mm_GmmStateBeforeSuspension = %s
Line 1330: Abort any ongoing GMM procedure and later Trigger  GPRS detach procedure in GMM state= %s
Line 1350: GMM state was GMM_SERVICE_REQUEST_INITIATED but have moved to GSM RAT, reverting to GMM_REGISTERED
Line 1399: ERROR: Invalid mm_GmmState....
Line 1466: CLEARING Gmm Regist status Cause
Line 1471: NOT CLEARING Gmm Regist status Cause, Cause %d
Line 1552: GMM_NO_IMSI -> Should Never Have Got Here !!! 
Line 1560: ERROR: Unexpected mm_GmmServiceState....
Line 1571: GPRS attach (re)initiation...
Line 1600: RAI Changed
Line 1616: Cell Changed & Must Retry in New Cell
Line 1623: GMM_T3302 had expired while GMM was suspended
Line 1636: Cell changed and Att req action is GMM_NO_ATT_ACTION under attemping to attach / dereg state, need to do attach again.
Line 1737:  Need to do GPRS Attach UE is in NMO1 So try Combined Attach to establish the Gs association in the MSC/VLR.
Line 1746: GMM is in LIMITED and PS domain barred... So nothing done here... 
Line 1849: Change of Cell into New Routing Area....
Line 1860: New RAI before Est Cnf has been received. Must Break RR Con and start Again. Please Wait...
Line 1877: GPRS Attach Procedure Following Intersystem Change Between Cells Belonging to the Same RA....
Line 1892: Change of cell within the same RA => Perform Cell Update [24.008]-4.7.3.1.5.e....
Line 1907: Access barred Due to Access Class Control....
Line 1919: Must Break RR Con. .
Line 1932: Lower Layer Failure....
Line 1949: Loss of coverage during Signalling, end the signalling
Line 2026: GMM_REGISTERED.mm_GmmCellData.NetworkService = %d 
Line 2059: ISR is activated but RAI is changed after L2U Rat Change. RRC Est Cause is set to InterRAT Cell Reselection.
Line 2088: RAU recovery procedure is performed..
Line 2162: change of cell into new routing area....
Line 2182: change of cell in same routing area having received cause 'Retry upon entry into a new cell'....
Line 2201: GMM CELL DATA RAI != SIM RAI and No timer for retrying RAU, Here RAU is necessary. 
Line 2209: RAU procedure as GMM_T3302 expired in GMM_SUSPENDED state...
Line 2222: RAU procedure should be triggered due to NMO change (not periodic)
Line 2270: change of cell into new routing area....
Line 2281: RAU needed flag is set
Line 2320: access no longer barred....
Line 2374: Change of Cell into New Routing Area....
Line 2390: Network mode change during GPRS detach procedure for CS services
Line 2407: IMSI Detach Procedure After RAU Procedure Following Intersystem Change Between Cells Belonging to the Same RA....
Line 2420: Change of Cell in Same Routing Area....
Line 2432: Lower Layer Failure....
Line 2481: MO/MT Call was attempted in NMO1. This should be stopped before RAU Procedure ....
Line 2510: RAU will be pended while MO/MT call is in progress....
Line 2528: Initiating RAU Procedure .... after WFRAU timer is expired
Line 2535: Initiating RAU Procedure .... if Quick Rollback is over
Line 2564: Initiating RAU Procedure ....
Line 2581: RAU procedure not initiated due to access class barred....
Line 2598: SM Informed of 'Lost' Radio Coverage....
Line 2603: SM Informed of Regained Radio Coverage....
Line 2661: SM Informed of 'Lost' Radio Coverage....
Line 2667: SM Informed of Regained Radio Coverage....
Line 2673: Resumed Again on UMTS Rat So no need to Do Anything 
Line 2825:  ERROR: mm_GmmState and mm_GmmServiceState incompatible! 
Line 2869: Change of Cell into New Routing Area. Starting RAU...
Line 2878: New RAI before Est Cnf has been received. Must Break RR Con and start Again. Please Wait...
Line 2901: RAT Change Detected During RAU Procedure...RAU Procedure Following Intersystem Change Between Cells Belonging to the Same RA
Line 2915: Change of Cell in Same Routing Area....
Line 2927: Access Barred Due to Access Class Control....
Line 2939: Must Break RR Con. .
Line 2964: Gmm cell data. network service exceeds the limit
Line 2988: SM informed of 'Lost' Radio Coverage....
Line 3028: Change of Cell into New Routing Area....
Line 3035: Change of RAC Detected, during Detach for PS Switching
Line 3078: New RAI before Est Cnf has been received. Must Break RR Con and start Again. Please Wait...
Line 3098: RAT Change Detected During Detach -> RAU Procedure then Normal GPRS Detach Following Intersystem Change Between Cells Belonging to the Same RA....
Line 3119: change of cell within the same RA....
Line 3164: .... lower layer failure
Line 3202: Change of cell into new RA...
Line 3236: RRC requested to 'release' PS signalling connection before RAU procedure initiation...
Line 3246: PMM_CONNECTED: RRC requested to 'release' PS signalling connection before RAU procedure initiation...%d
Line 3253: RAU procedure 'interupts' service request procedure...
Line 3334: Loss of coverage during service request procedure...
Line 3346: Temp_GmmCellIndDb->mm_GmmCellData.NetworkService exceeds the limit
Line 3356: SM informed of 'lost' radio coverage....
Line 3373: RRC requested to 'release' PS signalling connection Because Lost Coverage Before Moving to Conn Mode
Line 3413: GCF Mode is Enabled
Line 3416: In UMTS RAT, PMM connected Mode and Network mode 1
Line 3420: Current and SIM data PLMNs are not same and PLMN Found in Equivalent Plmn List
Line 3423: LA and RA of the SIM and the current cell data are same.
Line 3538: GRR_GMM_SUSPEND_IND received in state %s 
Line 3586: mm_EncodedDrxParam = 0x%02X 0x%02X
Line 3712: ---------------------Current GMM cell details---------------------
Line 3715:  RAT mode -> %s
Line 3720:  Access tech type -> %s
Line 3724:  RAT mode -> %s,          Network service -> %s
Line 3729:  Forbidden PLMN
Line 3735:  Forbidden PLMN for GPRS services
Line 3741:  Forbidden LA
Line 3747:  Forbidden LA for roaming
Line 3753:  PLMN selection has been started by MM
Line 3757:  Network access -> %s,         Network mode -> %s 
Line 3763:  RAI -> %02X %02X %02X %02X %02X %02X,          Cell identity -> %07X
Line 3768: Cell change -> %s, Data resumption -> %s
Line 3773:  Cell change -> %s
Line 3788: ---------------------Previous GMM cell details---------------------
Line 3791:  RAT mode -> %s,          Network mode -> %s
Line 3796:  Access tech type -> %s
Line 3803:  RAI -> %02X %02X %02X %02X %02X %02X,          Cell identity -> %07X
Line 3868: Even though Band is changed in NMO1, we don't have anything to send again! 
Line 3898: RAU recovery procedure is performed..
Line 3910: RAT Change to UMTS Detected -> GSM to UMTS Intersystem Change Between Cells Belonging to Same RA...GPRS Functional State was %s on Intersystem Change....
Line 3914:  => Initiate RAU Procedure Immediately....
Line 3927: Normal RAU Procedure on Intersystem Handover from GSM to UMTS during CS Connection....
Line 3936: RAU Procedure Not Required Until Uplink Signalling or Data Transmission. [24.008]-4.7.1.7 (b)...
Line 3943: RAT Change to GSM Failed, Now Back in UMTS again -> MS in Same Access Network as when last sent user data or signalling, normal procedures shall be followed.....
Line 3968: mm_RauForGprsResumeReEntryFlag is RESET as RauNeeded is Set....
Line 3981: RAU Procedure Initiation Required for GPRS Resumption in the Network....DataResumption=%d, mm_RauForGprsResumeReEntryFlag=%d
Line 3993: RAU Procedure Initiation as GMM_T3302 Expired in GMM_SUSPENDED state....
Line 4001: RAU recovery procedure is performed..
Line 4011: Cell update procedure will be blocked during Manual PLMN searching.
Line 4018: Change of Cell in Same Routing Area....
Line 4035: RAT Change to GSM Detected -> UMTS to GSM Intersystem Change Between Cells Belonging to Same RA....PMM functional state was %s on intersystem change....
Line 4039:  => Initiate RAU Procedure Immediately....
Line 4048: RAU procedure not required until uplink signalling or data transmission. [24.008]-4.7.1.7 (b)...
Line 4067:  => Initiate RAU Procedure due to MM_AUTO_PLACEMENT_IN_QUEUE....
Line 4077: RAT Change to UMTS Failed, Now Back in GSM again -> MS in same access network as when last sent user data or signalling, normal procedures shall be followed.....
