Line 191: ProtDisc: %d
Line 218: LLGMM_TRIGGER_IND received in GMM_SUSPENDED state...
Line 220: ...processing according to pre-suspension state of %s
Line 254: No specific actions on transmission of %s...
Line 262: LLGMM_TRIGGER_IND containing unmatched PduId in GMM_DEREGISTERED
Line 292: READY timer is deactivated and shall run without expiry
Line 299: Network has forced MS to STANDBY state -> READY timer not started
Line 312: PDP Context Status is %d %d
Line 321: READY timer (re)started
Line 368: No specific actions on transmission failure of %s...
Line 376: LLGMM_STATUS_IND containing unmatched PduId in GMM_DEREGISTERED...
Line 402: Resetting values in mm_GmmProcessLlGmmStatusIndMsgInRegInitState
Line 432: LLGMM_STATUS_IND containing unmatched PduId, GPRS attach fail actions not performed...
Line 454: Lower layer failure during GPRS detach procedure for IMSI only...
Line 466: LLGMM_STATUS_IND indicating GMM PDU transmission failure before DETACH_REQUEST transmission attempt, no actions performed...
Line 472: LLGMM_STATUS_IND containing unmatched PduId or corresponds to a non-GMM SAPI-1 PDU, no actions performed...
Line 507: Resetting values in mm_GmmProcessLlGmmStatusIndMsgInRauInitState
Line 514: Reject UE Pending Req because RAU Failed due to Lower Layer Failure.
Line 540: LLGMM_STATUS_IND containing unmatched PduId, RAU fail actions not performed...
Line 560: Lower layer failure during GPRS detach procedure...
Line 603: LLGMM_STATUS_IND indicating GMM PDU transmission failure before DETACH_REQUEST transmission attempt, no actions performed...
Line 609: LLGMM_STATUS_IND containing unmatched PduId, no actions performed...
Line 635: Cause = %s
Line 663: LLGMM_STATUS_IND received for authenticaiton or identity message, do not abort the complete procedure
Line 689: LLGMM_STATUS_IND received in GMM_SUSPENDED state...
Line 692: ...processing according to pre-suspension state of %s
Line 721: Perform TbfRelAction, MM_COORD_TBF_REL_ACTION
Line 740: Perform TbfRelAction, MM_COORD_TBF_REL_ACTION
Line 812: mm_PerformLlGmmGmmMsgTxActions  in GMM_SUSPENDED state...
Line 814: ...processing according to pre-suspension state of %s
Line 826: GPRS attach / RAU procedure completed, start DRX and resume LLC...
Line 858: Received ACK For RAU/ATTACH COMPLETE So Stop Timer and Set the State
Line 925: Performing actions following DETACH_REQUEST transmission (or failure)...
Line 955: Indication of GPRS detach procedure completion delayed until reception of RLC_GMM_SAPI_ONE_TX_COMPLETE...
Line 988: GMM_DETACH_TRY_TIMER not running on LLC indication of DETACH_REQUEST transmission, no actions performed...
Line 1007: Performing actions following DETACH_ACCEPT transmission (or failure)...
Line 1063: SAPI-1 Tx table entry %d has been reserved with PduId %04X...
Line 1068: ...for transmission of %s message
Line 1073: ...for transmission of a non-GMM message
Line 1079: ERROR: Table is already full...
Line 1107: PduId %04X confirmed as entry %d in SAPI-1 Tx table
Line 1117: ERROR: PduId %04X does NOT match appropriate table entry...
Line 1123: ERROR: PduId submitted for confirmation has the value NOT_SAPI1_PDU...
Line 1147: Checking SAPI-1 Tx table for PduId match...
Line 1151: PduId 0x%04X matched...
Line 1161: ...corresponding to %s
Line 1165: ...corresponding to a non-GMM SAPI-1 PDU
Line 1170: ERROR: PduId 0x%04X does not match that of first active entry...
Line 1176: PduId 0x%04X matched...
Line 1185: ...corresponding to %s
Line 1190: ...corresponding to a non-GMM SAPI-1 PDU
Line 1198: PduId -> NOT_SAPI1_PDU
Line 1220: First active entry removed from the SAPI-1 Tx table...
Line 1232: PduId %04X does not match first active entry in the SAPI-1 Tx table...
Line 1238:  active entry matched in  the SAPI-1 Tx table at %d
Line 1296: %s currently occupies position %d in the SAPI-1 Tx table...
Line 1323: Flushing the following %d active entries from the SAPI-1 submit table...
Line 1325: -------------
Line 1341: No active entries to flush from the SAPI-1 submit table...
Line 1357: mm_AssignNewTlli:
Line 1400: mm_AssignNewAndOldTlli:
Line 1419: mm_UnassignTlli:
Line 1571: ERROR: Invalid NewTlliType in mm_SetNewTlli....
Line 1619: ERROR: ReqdTlliType is not GMM_LOCAL_TLLI or GMM_FOREIGN_TLLI...
Line 1627: TLLI change reqd for RAU procedure as P-TMSI has changed since previous TLLI assignment to LLC...
Line 1639: TLLI assignment/change reqd for RAU procedure as TLLI assigned to LLC not of reqd type...
Line 1667: mm_DecodeLlGmmUnitDataIndMsg:
Line 1683: 
Displaying Separate Buffer in DATA IND Received From LLC Layer in  mm_DecodeLlGmmUnitDataIndMsg
Line 1733: Invalid SMS Protocol Discriminator. No SMS Msg in GSM / GPRS to GMM !
Line 1741: Invalid ProtocolDisc (0x%x) in mm_DecodeLlGmmUnitDataIndMsg
Line 1754: No action required in this State in mm_DecodeLlGmmUnitDataIndMsg
Line 1762: Invalid mm_GmmState in mm_DecodeLlGmmUnitDataIndMsg
Line 1831: GS31(SM/SMS/SS): ucTransactionID = 0x%02X, ucProtocol =%s, ucSendSeqNum =0x%02X
Line 1832: GS31(SM/SMS/SS): ucMessageType =0x%02X, ucChannel =0x%02X
Line 1833: GS31(SM/SMS/SS): Raw data length =%d
Line 1848: 
Displaying Message Contents: %s
Line 1850: Cipher = %s
Line 1852: PduId = 0x%04X
Line 1921: 
Displaying Message Contents: %s
Line 1976: LLC requested to suspend....
Line 1984: LLC is already suspended....
Line 2031: LLC Resumption is avoided as current Operating mode is MM_MOBILE_CLASS_C_CS
Line 2039: LLC requested to resume....
Line 2052: Cant Resume LLC At this Time Ignored
Line 2057: LLC is not suspended....
Line 2119: 
%s contents:
Line 2242: Cause -> %s
