Line 84: L1LC_InitDb for ST-%d
Line 100: L1LC_InitCommDb for ST- %d
Line 196: [gL1LC_DrxState] (%d) -> (%d)
Line 207: [gL1LC_DRXinSibFlag] (%d) -> (%d)
Line 213: [gL1LC_ConnDrxConfigFlag] (%d) -> (%d)
Line 230: [gL1LC_ReInitDrxTriggered] (%d) -> (%d)
Line 243: [gL1LC_SleepProcOngoing] (%d) -> (%d)
Line 260: [IscurSleepTimeforSib] (%d) -> (%d)
Line 273: [gDrx_isPagingDoneForMeas] (%d) -> (%d)
Line 284: [gL1LC_isFirstDrxReq] (%d) -> (%d)
Line 295: [gDrxServingTimeOOSFlag] (%d) -> (%d)
Line 306: [L1LC_SetNextPagingInstance] (PF: %d  PO: %d)
Line 318: [gL1LC_PagingPalTime] (%u)
Line 334: [gL1LC_IdleConnDRXStatus] (%d) -> (%d)
Line 341: [L1LC_GetSatModeEnableFlag] (%d)
Line 347: [L1LC_SetSatModeEnableFlag] (%d)->(%d)
Line 380: [gL1LC_DrxBplmnEnable] (%d) -> (%d)
Line 391: [bplmn_spare_tmr_duration] (%d) -> (%d)
Line 404: [gDrx_BplmnStarted] (%d) -> (%d)
Line 510: [gL1LC_IratUmtsMeasState] (%d) -> (%d)
Line 525: [gL1LC_IratGsmMeasState] (%d) -> (%d)
Line 540: [gL1LC_IratGsmVerifyState] (%d) -> (%d)
Line 555: [gL1LC_IratCdmaMeasState] (%d) -> (%d)
Line 570: [gL1LC_IratNrMeasState] (%d) -> (%d)
Line 576: [gL1LC_IratStopPending] (%d) -> (%d)
Line 587: [gL1LC_IratStopbeforeLatchCnf] (%d) -> (%d)
Line 593: [gL1LC_IratNrMeasConfigRelease] (%d) -> (%d)
