Line 181: [NR][TTI_DBDEV][INIT] m_CcIdx(%d), system_info_systime(0x%X), SCS(DL/UL)=(%d/%d)
Line 193: [NR][TTI_DBDEV][CFG] Force holding (FR2): %d, CC(%d)
Line 202: [NR][TTI_DBDEV][CFG] SCS(PREV/NEXT)(%d/%d) FLG_HOLDING/BYSCS(%d/%d), CC(%d)
Line 288: [NR][TTI_DBDEV][CFG] TtiSiListInfo is updated : sibxState(%d), numSiList(%d)
Line 387: [NR][TTI_DBDEV][CFG] Update default CFG: m_CcIdx:%d  prvFrontCcIdx(%d) frontCcIdx(%d) rf_idx(%d), rf_idx_div(%d), rxMode(%d) ue_ant_num(%d), scs_ssb(%d) scs_default(%d) flag_wakeup/holding_skip(%d)
Line 399: [NR][TTI_DBDEV][CFG]  m_CcIdx:%d , dl_scs(%d) updated
Line 704: [NR IPC] L1C_PHY_MIB_ACQ_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d) ipc(%d), cmd(%d)
Line 722: [NR IPC] Skip the L1C_PHY_SYS_PARAM_CHG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d), ipc(%d)
Line 729: [NR IPC] L1C_PHY_SYS_PARAM_CHG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d), ipc(%d)
Line 767: [NR IPC] L1C_PHY_SYS_PARAM_CHG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d), ipc(%d) : CC(%d), CC_Offset(%d)
Line 784: [NR IPC] Skip L1C_PHY_SYS_PARAM_CHG_CNF: CC info is invalid : CC(%d), CC_Offset(%d)
Line 793: [NR IPC] PHY_PHY_LCPU_RELEASE_READY, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d), ipc(%d)
Line 814: [NR IPC] L1C_PHY_DRX_WAKEUP_INIT_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d), ipc(%d)
Line 832: [NR IPC] L1C_PHY_RESTORE_PCELL_PHY_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d), ipc(%d)
Line 852: [NR IPC] L1C_PHY_RESTORE_PCELL_PHY_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d), ipc(%d)
Line 925: [NR][TTI_DBDEV][EVT] state change done: event(%d) flag_event_statechange(0x%X)
Line 935: [NR][TTI_DBDEV][EVT] state change counter expired: event(%d) flag_event_statechange(0x%X) DC(0x%X)DF(0x%X)TX(0x%X) CC(%d)
Line 1010: [NR][TTI_DBDEV][State] Hoding State change: CNT(%d) CC(%d)
Line 1031: [NR][TTI_DBDEV][State] Hoding by SCS change State change: CNT(%d), CC(%d)
Line 1095: (F) Error in StateChange: cause(%d) current_state(%d) CC(%d)
Line 1102: (I) [TTI_DBDEV] STATE CHANGE TO idle2idle current_state(d%)/CC(%d)
Line 1111: [NR][TTI_DBDEV][EVT] cause(%d) current_state(%d) next_state(%d) isStateChangeOccured(%d) Flag_txDevActivate(%d) CC(%d)
Line 1146: (F)INVALID event(%d) CC(%d)
Line 1165: (F)INVALID event(%d) CC(%d)
Line 1185: (F)INVALID event(%d) CC(%d)
Line 1282: (F)INVALID STATE!! (%d) CC(%d)
