Line 103: Uhal Stops PCCPCH Phych %d (type=%d, RlsStr=%x)
Line 106: Uhal Stops SCCPCH Phych %d (type=%d, RlsStr=%x)
Line 109: Uhal Stops DL DPCH Phych %d (type=%d, RlsStr=%x)
Line 112: Uhal Stops PICH Phych %d (type=%d, RlsStr=%x)
Line 115: Uhal Stops AICH Phych %d (type=%d, RlsStr=%x)
Line 118: Uhal Stops MICH Phych %d (type=%d, RlsStr=%x)
Line 121: Uhal Stops SCCPCH_MBMS_RL0 Phych %d (type=%d, RlsStr=%x)
Line 124: Uhal Stops SCCPCH_MBMS_RL1 Phych %d (type=%d, RlsStr=%x)
Line 127: Uhal Stops SCCPCH_MBMS_RL2 Phych %d (type=%d, RlsStr=%x)
Line 130: Uhal Stops SCCPCH(0) for CBS Phych %d (type=%d, RlsStr=%x)
Line 133: Uhal Stops SCCPCH(1) for CBS Phych %d (type=%d, RlsStr=%x)
Line 136: Uhal Stops SCCPCH(2) for CBS Phych %d (type=%d, RlsStr=%x)
Line 139: Uhal Stops ??? Phych %d (type=%d, RlsStr=%x)
Line 200: activeStackId %d PhychType = %d
