Line 156: [HTTP] Warn >> "[HTTP Module] Failed to add to HTTP session DB "
Line 169: [HTTP] Warn >> "[HTTP Module] Failed to allocate SessId as no session are free "
Line 249: [HTTP] Flow >> "(pHTTPInitInfo_t is NULL "
Line 271: [HTTP] Flow >> "[STLS] isSessResumable : %d,isCertValidationRequired : %d,  clientProfile : %d"
Line 272: [HTTP] Flow >> "[STLS] minVer : %d,maxVer : %d, transport : %d, extensions : %d"
Line 302: [HTTP] Flow >> "[HTTP Module]  [ STLS ] %s(), sockId : %d, Type : %d, Event : %d, ErrorCode : %d, EventInfo : %p"
Line 308: [HTTP] Flow >> "[HTTP Module] [STLS] pHTTPClient_Interface SessionIndex :%x"
Line 309: [HTTP] Flow >> "[HTTP Module] [STLS] pHTTPClient_Interface Address :%x"
Line 310: [HTTP] Flow >> "[HTTP Module] [STLS] pHTTPClient_Interface->tls_state:%d"
Line 311: [HTTP] Flow >> "[HTTP Module] [STLS] pHTTPClient_Interface->tls_SocketID:%d"
Line 312: [HTTP] Flow >> "[HTTP Module] [STLS] pHTTPClient_Interface->tlsIF_id:%d"
Line 315: [HTTP] Flow >> "[HTTP Module]  [ STLS ] Call Back From TLS Socket Id:%d , Event:%d"
Line 320: [HTTP] Flow >> "[HTTP Module] [ STLS ] Call Back From HTTPClient_AccessSocket:%d , Event:%d"
Line 326: [HTTP] Flow >> "[HTTP Module] HTTP_STLSAsyncCallback event --> Socket Id:%d , Event:%d, tls_enabled : %d"
Line 339: [HTTP] Flow >> "[HTTP Module]  [ STLS ] Received Null Read Event Info"
Line 346: [HTTP] Flow >> "[HTTP Module]  [ STLS ] readData->reqBufferSize : %d"
Line 369: [HTTP] Warn >> "[HTTP Module] ERROR - No Call back registered for  PSK sessId:%d"
Line 391: [HTTP] Flow >> "[HTTP Module] - PSK received from client"
Line 398: [HTTP] Flow >> "[HTTP Module] - PSK NOT received from client - wait for API invoke from client"
Line 404: [HTTP] Warn >> "[HTTP Module] HTTP Module Not registered event called from TCP/IP %d "
Line 411: [HTTP] Warn >> "[HTTP Module] HTTP Module closed or call back function called wrongly "
Line 441: [HTTP] Flow >> "[HTTP Module] [TLS] pHTTPClient_Interface SessionIndex :%x"
Line 442: [HTTP] Flow >> "[HTTP Module] [TLS] pHTTPClient_Interface Address :%x"
Line 443: [HTTP] Flow >> "[HTTP Module] [TLS] pHTTPClient_Interface->tls_state:%d"
Line 444: [HTTP] Flow >> "[HTTP Module] [TLS] pHTTPClient_Interface->tls_SocketID:%d"
Line 457: [HTTP] Flow >> "[HTTP Module] HTTP_TCPAsyncCallback event --> Socket Id:%d , Event:%d"
Line 486: [HTTP] Warn >> "[HTTP Module]  Received CONNECT EVENT :%d "
Line 493: [HTTP] Flow >> "[HTTP Module] [ TLS ] Changing TLS state to TLS_STATE_HANDSHAKE_SUCCESS"
Line 496: [HTTP] Flow >> "[HTTP Module] [ TLS ] Enabled TLS for %d Socket"
Line 503: [HTTP] Warn >> "[HTTP Module] HTTP Module Not registered event called from TCP/IP %d "
Line 507: [HTTP] Warn >> "[HTTP Module] HTTP Module closed or call back function called wrongly "
Line 536: [HTTP] Flow >> "[HTTP Module] %s(), Failed to allocate memory to tcpip_msg"
Line 540: [HTTP] Flow >> "[HTTP Module] %s() called for SockId: [%d] and event [%d] "
Line 547: [HTTP] Flow >> "[HTTP Module] [HTTP_PostStlsAsyncCallBackEventToApp] SessionIndex: [%d] and SockId: [%d]"
Line 557: [HTTP] Warn >> "[HTTP Module] Incorrect Socket Id "
Line 570: [HTTP] Warn >> "[HTTP Module] Failed to sent message unknown mailbox (%d) "
Line 584: [HTTP] Flow >> "[HTTP Module] Msg MbxDst:%d MbxSrc :%d TypMsg:0x%x Length:%d"
Line 589: [HTTP] Flow >> "[HTTP Module] Msg SockID:%d Event :%d eventInfo:0x%x SessId:%d"
Line 594: [HTTP] Warn >> "[HTTP Module] Failed to sent message"
Line 623: [HTTP] Flow >> "[HTTP Module] [HTTP_PostAsyncCallBackEventToApp Function] called for SockId: [%d] and event [%d] "
Line 649: [HTTP] Warn >> "[HTTP Module] Incorrect Socket Id "
Line 671: [HTTP] Warn >> "[HTTP Module] Failed to sent message unknown mailbox (%d) "
Line 686: [HTTP] Flow >> "[HTTP Module] Msg MbxDst:%d MbxSrc :%d TypMsg:0x%x Length:%d"
Line 691: [HTTP] Flow >> "[HTTP Module] Msg SockID:%d Event :%d ErrorCode:%d SessId:%d"
Line 696: [HTTP] Warn >> "[HTTP Module] Failed to send message"
Line 732: [HTTP] Flow >> "(pHTTPInitInfo_tor cfg is NULL "
Line 737: [HTTP] Flow >> "(pHTTPInitInfo_t->HTTP_IpInfo_UE_t.IpAddress is NULL "
Line 742: [HTTP] Flow >> "pHTTPInitInfo_t->HTTP_ServerIpInfo_t.IpAddress is NULL "
Line 765: [HTTP] Warn >> "[HTTP Module] [STLS]  Received Server name is Null"
Line 773: [HTTP] Flow >> "[HTTP Module] [STLS]  SERVER IP is HTTP_TPC_IPV6"
Line 779: [HTTP] Flow >> "[HTTP Module]  [STLS] SERVER IP is HTTP_TPC_IPV4 "
Line 786: [HTTP] Flow >> "[HTTP Module] [STLS]  CLIENT IP is HTTP_TPC_IPV6"
Line 792: [HTTP] Flow >> "[HTTP Module] [STLS]  CLIENT IP is HTTP_TPC_IPV4 "
Line 804: [HTTP] Flow >> "[HTTP Module] [STLS] Resuming TLS Session"
Line 810: [HTTP] Flow >> "[HTTP Module] [STLS] ReasonCode : %d, AppSessId : %d"
Line 845: [HTTP] Flow >> "[HTTP Module] HTTPInitialise Function --> pHTTPInitInfo_t values "
Line 846: [HTTP] Flow >> "pHTTPInitInfo_t->HTTP_ServerIpInfo_t->IpType: %d "
Line 847: [HTTP] Flow >> "pHTTPInitInfo_t->HTTP_ServerIpInfo_t->IpLen: %d "
Line 849: [HTTP] Flow >> "pHTTPInitInfo_t->HTTP_IpInfo_UE_t->IpType: %d "
Line 850: [HTTP] Flow >> "pHTTPInitInfo_t->HTTP_IpInfo_UE_t->IpLen: %d "
Line 852: [HTTP] Flow >> "pHTTPInitInfo_t->HTTP_ServerPortInfo_t->localPort: %d "
Line 853: [HTTP] Flow >> "pHTTPInitInfo_t->HTTP_ServerPortInfo_t->remotePort: %d "
Line 854: [HTTP] Flow >> "pHTTPInitInfo_t->SupportedTransport: %d "
Line 855: [HTTP] Flow >> "pHTTPInitInfo_t->contextid: %d "
Line 856: [HTTP] Flow >> "pHTTPInitInfo_t->SessionType: %d "
Line 857: [HTTP] Flow >> "pHTTPInitInfo_t->sessHashKey: %x"
Line 858: [HTTP] Flow >> "pHTTPInitInfo_t->serverName: %s"
Line 859: [HTTP] Flow >> "pHTTPInitInfo_t->serverNameLen: %x"
Line 860: [HTTP] Flow >> "pHTTPInitInfo_t->clientProfile: %d"
Line 868: [HTTP] Flow >> "[STLS] [ERROR] Failed to Create STLS Session - appSessId : %d "
Line 871: [HTTP] Flow >> "[STLS] STLS Session Created with appSessId : %d "
Line 877: [HTTP] Flow >> "[HTTP Module] HTTPInitialise"
Line 891: [HTTP] Flow >> "[HTTP Module] [STLS] tlsIF_id:%d"
Line 892: [HTTP] Flow >> "[HTTP Module] [STLS] pHTTPClient_Interface Address :%x"
Line 893: [HTTP] Flow >> "[HTTP Module] [STLS] pHTTPClient_Interface->tls_state:%d"
Line 894: [HTTP] Flow >> "[HTTP Module] [STLS] pHTTPClient_Interface->tls_SocketID:%d"
Line 898: [HTTP] Flow >> "[HTTP Module] SessId:%d"
Line 903: [HTTP] Warn >> "[HTTP Module] Failed to sent message to xcapm "
Line 908: [HTTP] Flow >> "[HTTP Module] HTTP-ReInitialise"
Line 920: [HTTP] Flow >> "[HTTP Module] [STLS] tlsIF_id:%d"
Line 921: [HTTP] Flow >> "[HTTP Module] [STLS] pHTTPClient_Interface Address :%x"
Line 922: [HTTP] Flow >> "[HTTP Module] [STLS] pHTTPClient_Interface->tls_state:%d"
Line 923: [HTTP] Flow >> "[HTTP Module] [STLS] pHTTPClient_Interface->tls_SocketID:%d"
Line 926: [HTTP] Flow >> "[HTTP Module] SessId:%d"
Line 935: [HTTP] Flow >> "[HTTP HTTPInitialise] No HTTP client object present for session ID: %d"
Line 941: [HTTP] Warn >> "[HTTP Module] pHTTPInitInfo_t Pointing to NULL "
Line 1114: [HTTP] Flow >> "[HTTP Module] HTTPClose : INVALID session ID %d'"
Line 1121: [HTTP] Flow >> "[HTTP Module] HTTPClose : Client DB not initialized for session ID %d'"
Line 1130: [HTTP] Flow >> "[HTTP Module] HTTPClose for sessionID %d For STLS socket'"
Line 1167: [HTTP] Flow >> "[HTTP Module] HTTP_CreateSocket Function  "
Line 1171: [HTTP] Flow >> "[HTTP Module] AP Server socket creation error"
Line 1173: [HTTP] Flow >> "[HTTP Module] AP Server socket created with ID: %d"
Line 1193: [HTTP] Warn >> "[HTTP Module] AP Server socket not created"
Line 1198: [HTTP] Flow >> "[HTTP Module] AP Server socket created with ID: %d"
Line 1219: [HTTP] Flow >> "[HTTP Module] HTTP_CloseSockReq Function"
Line 1230: [HTTP] Flow >> "[HTTP Module] [STLS] %s() : Failed to Close STLS Session"
Line 1232: [HTTP] Flow >> "[HTTP Module] [STLS] %s() : Close STLS Session Success"
Line 1243: [HTTP] Flow >> "[HTTP Module] SessId : %d, SockId : %d"
Line 1261: [HTTP] Flow >> "[HTTP Module] HTTP_MethodHandlerReq Function --> Method Id:%d "
Line 1352: [HTTP] Func >> "START --------	%s	-------"
Line 1370: [HTTP] Func >> "START --------  %s  -------"
Line 1389: [HTTP] Warn >> "[HTTP Module] HTTP request Header Formation Error "
Line 1396: [HTTP] Flow >> "[HTTP Module] HTTP_GET_MethodReq Function --> HTTP_Request:%s"
Line 1399: [HTTP] Warn >> "[HTTP Module] HTTP request Header Formation Error "
Line 1418: [HTTP] Func >> "START --------  %s  -------"
Line 1436: [HTTP] Warn >> "[HTTP Module] HTTP request Header Formation Error "
Line 1443: [HTTP] Flow >> "[HTTP Module] HTTP_PUT_MethodReq Function --> HTTP_Request:%s"
Line 1446: [HTTP] Warn >> "[HTTP Module] HTTP request Header Formation Error "
Line 1463: [HTTP] Func >> "START --------  %s  -------"
Line 1481: [HTTP] Warn >> "[HTTP Module] HTTP request Header Formation Error "
Line 1488: [HTTP] Flow >> "[HTTP Module] HTTP_POST_MethodReq Function --> HTTP_Request:%s"
Line 1491: [HTTP] Warn >> "[HTTP Module] HTTP request Header Formation Error "
Line 1508: [HTTP] Func >> "START --------  %s  -------"
Line 1527: [HTTP] Warn >> "[HTTP Module] HTTP request Header Formation Error "
Line 1534: [HTTP] Flow >> "[HTTP Module] HTTP_DELETE_MethodReq Function --> HTTP_Request:%s"
Line 1537: [HTTP] Warn >> "[HTTP Module] HTTP request Header Formation Error "
Line 1549: [HTTP] Func >> "START --------  %s  -------"
Line 1568: [HTTP] Warn >> "[HTTP Module] HTTP request Header Formation Error "
Line 1575: [HTTP] Flow >> "[HTTP Module] HTTP_Authentication_SupplementaryServices Function --> HTTP_Request:%s"
Line 1578: [HTTP] Warn >> "[HTTP Module] HTTP request Header Formation Error "
Line 1596: [HTTP] Func >> "START --------  %s  -------"
Line 1615: [HTTP] Warn >> "[HTTP Module] HTTP request Header Formation Error "
Line 1622: [HTTP] Flow >> "[HTTP Module] HTTP_Authentication_SupplementaryServices Function --> HTTP_Request:%s"
Line 1625: [HTTP] Warn >> "[HTTP Module] HTTP request Header Formation Error "
Line 1734: [HTTP] Func >> "START --------	%s	-------"
Line 1743: [HTTP] Warn >> "[HTTP Module] pHTTPResponseHeaderInfo_t is NULL "
Line 1752: [HTTP] Warn >> "[HTTP Module] HTTP_body is NULL.."
Line 1755: [HTTP] Flow >> "[HTTP Module] HTTPClient_Readfromsocket status:%d, socket : %d"
Line 1792: [HTTP] Warn >> "[HTTP Module] Failed to sent message to xcapm "
Line 1796: [HTTP] Warn >> "[HTTP Module] Sent read event to  XCAPM "
Line 1808: [HTTP] Warn >> "[HTTP Module] HTTPClient_Readfromsocket returns no message size:0 "
Line 1820: [HTTP] Func >> "START --------  %s  -------"
Line 1832: [HTTP] Func >> "START --------  %s  -------"
Line 1846: [HTTP] Func >> "START --------  %s  -------"
