Line 416: [HTTP] Func >> "START --------  %s  -------"
Line 419: [HTTP] Warn >> "[HTTP Module] URI or pHTTPRequestHeaderInfo_t is NULL"
Line 423: [HTTP] Flow >> "[HTTP Module] HTTP_method_id is: %d"
Line 430: [HTTP] Flow >> "[HTTP Module] HTTP_method_id is: %d"
Line 452: [HTTP] Warn >> "[HTTP Module] Method ID not Supported : %d"
Line 484: [HTTP] Warn >> "[Generate_HTTP_Request_Packet] Authorization is NULL"
Line 654: [HTTP] Warn >> "[HTTP Module] Content Type not Supported : %d"
Line 685: [HTTP] Warn >> "[HTTP Module] message_body memory not allocated"
Line 721: [HTTP] Func >> "START --------  %s  -------"
Line 785: [HTTP] Warn >> "[HTTP Module] QOP not supported : %d"
Line 809: [HTTP] Flow >> "[HTTP Module] Algorithm : %d"
Line 824: [HTTP] Warn >> "[HTTP Module] Invalid Algorithm : %d"
Line 881: [HTTP] Warn >> "[Extract_HeaderIE] Param Pos is Invalid "
Line 885: [HTTP] Func >> "START --------  %s  -------"
Line 890: [HTTP] Warn >> "[Extract_HeaderIE] Decoding Last Parameter"
Line 900: [HTTP] Warn >> "[Extract_HeaderIE] Extracted Param is NULL "
Line 939: [HTTP] Func >> "START --------	%s	-------"
Line 944: [HTTP] Warn >> "[Extract_Authenticate_InfoHeader] Authenticate_Info is NULL"
Line 951: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 979: [HTTP] Flow >> "Decoding NonceCount"
Line 989: [HTTP] Warn >> "nc points to NULL"
Line 1011: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 1021: [HTTP] Warn >> "[HTTP Module] field_value is NULL"
Line 1067: [HTTP] Warn >> "[HTTP Module] Received NULL Content_Type"
Line 1075: [HTTP] Warn >> "[HTTP Module] HTTP_GetContentType() value not found in map"
Line 1078: [HTTP] Flow >> "[HTTP Module] HTTP_GetContentType() Type : %d"
Line 1111: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 1120: [HTTP] Warn >> "[HTTP Module] Date is NULL"
Line 1153: [HTTP] Warn >> "[HTTP Module] Content_Type is NULL "
Line 1185: [HTTP] Warn >> "[HTTP Module] Content_Type is NULL "
Line 1217: [HTTP] Warn >> "[HTTP Module] Content_Length is NULL "
Line 1250: [HTTP] Warn >> "[HTTP Module] Retry_After is NULL "
Line 1285: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 1295: [HTTP] Warn >> "[HTTP Module] E_Tag is NULL "
Line 1330: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 1340: [HTTP] Warn >> "[HTTP Module] Set_Cookie is NULL "
Line 1375: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 1385: [HTTP] Warn >> "[HTTP Module] Server is NULL "
Line 1420: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 1430: [HTTP] Warn >> "[HTTP Module] Expires is NULL "
Line 1463: [HTTP] DumpStr >> "[HTTP Module] Location: "
Line 1466: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 1476: [HTTP] Warn >> "[HTTP Module] Location is NULL "
Line 1508: [HTTP] Warn >> "[HTTP Module] WWW_Authenticate is NULL "
Line 1541: [HTTP] Warn >> "[HTTP Module] Authentication_Info is NULL "
Line 1577: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 1586: [HTTP] Warn >> "[HTTP Module] Connection is NULL "
Line 1609: [HTTP] Func >> "START --------  %s  -------"
Line 1632: [HTTP] Warn >> "[HTTP Module] tmp is NULL"
Line 1665: [HTTP] Warn >> "[HTTP Module] need to update structure with more fields"
Line 1693: [HTTP] Func >> "START --------  %s  -------"
Line 1698: [HTTP] Warn >> "[HTTP Module][Extract_WWW_AuthenticateHeader] WWW_Authenticate is NULL"
Line 1705: [HTTP] Warn >> "[HTTP Module][Extract_WWW_AuthenticateHeader]Failed to allocate memory"
Line 1710: [HTTP] Warn >> "[HTTP Module]pHTTP_WWW_AUTHENTICATE_t->Auth_Scheme : %d"
Line 1744: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 1754: [HTTP] Warn >> "[HTTP Module] field_value is NULL"
Line 1800: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 1810: [HTTP] Warn >> "[HTTP Module] field_value is NULL"
Line 1839: [HTTP] Warn >> "Receiced response_status_line is NULL"
Line 1873: [HTTP] Warn >> "No Valid HTTP status code"
Line 1891: [HTTP] Func >> "START --------  %s  -------"
Line 1898: [HTTP] Warn >> "No Valid HTTP Response"
Line 1912: [HTTP] Warn >> "response_status_line is NULL"
Line 1921: [HTTP] Warn >> "HTTP Message Invalid"
Line 1931: [HTTP] Warn >> "[HTTP Module] pHTTPResponseHeaderInfo_t is NULL"
Line 1937: [HTTP] Warn >> "[HTTP module] MALLOC FAILED"
Line 1944: [HTTP] Warn >> "[HTTP module] received_header is NULL"
Line 1965: [HTTP] Flow >> "[HTTP Module] HTTP_Message_Body->GetStringLength()  value --> %d"
Line 1966: [HTTP] Flow >> "[HTTP Module] pHTTPResponseHeaderInfo_t->Content_length value --> %d"
Line 1970: [HTTP] Warn >> "HTTP Message - Did Not Receive Content-Length Field in HTTP Header. Updated Content Length from Msg Body Length"
Line 1971: [HTTP] Flow >> "[HTTP Module] pHTTPResponseHeaderInfo_t->Content_length value --> %d"
Line 1974: [HTTP] Warn >> "HTTP Message - HTTP_Message_Body is NULL"
Line 1992: [HTTP] Func >> "START --------  %s  -------"
Line 2000: [HTTP] DumpStr >> "[GET_Extracted_HTTP_MessageBody]XCAP Contents: "
Line 2002: [HTTP] Warn >> "pal_Malloc returned NULL"
Line 2007: [HTTP] Warn >> "No Valid HTTP Message Body"
Line 2053: [HTTP] Warn >> "[HTTP Module] [HTTP_GetRealm] Received NULL parameters"
Line 2085: [HTTP] Warn >> "[HTTP Module] field_value is NULL"
Line 2095: [HTTP] Flow >> "Realm Field is not found!! continue with remaining fields"
Line 2098: [HTTP] Flow >> "[HTTP Module][%s] ret : %d"
Line 2118: [HTTP] Flow >> "[HTTP Module] [HTTP_GetQop] Received NULL QopValue"
Line 2125: [HTTP] Flow >> "[HTTP Module] qop : QOP_TYPE_AUTH_AND_AUTH_INT"
Line 2128: [HTTP] Flow >> "[HTTP Module] qop : QOP_TYPE_AUTH_INT"
Line 2131: [HTTP] Flow >> "[HTTP Module] qop : QOP_TYPE_AUTH"
Line 2133: [HTTP] Flow >> "[HTTP Module] qop : QOP_TYPE_UNSPECIFIED"
Line 2180: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 2190: [HTTP] Warn >> "[HTTP Module] field_value points to NULL"
Line 2199: [HTTP] Flow >> "Rspauth Field is not found!! continue with remaining fields"
Line 2202: [HTTP] Flow >> "[HTTP Module][%s] ret : %d"
Line 2221: [HTTP] Func >> "START --------  %s  -------"
Line 2233: [HTTP] Flow >> "Nonce Field is not found!! continue with remaining fields"
Line 2254: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 2264: [HTTP] Warn >> "[HTTP Module] field_value is NULL"
Line 2274: [HTTP] Flow >> "Nonce Field is not found!! continue with remaining fields"
Line 2277: [HTTP] Flow >> "[HTTP Module][%s] ret : %d"
Line 2322: [HTTP] Warn >> "[HTTP Module] pal_Malloc failed to allocate bytes for receive buffer"
Line 2332: [HTTP] Warn >> "[HTTP Module] field_value is NULL"
Line 2341: [HTTP] Flow >> "Cnonce Field is not found!! continue with remaining fields"
Line 2344: [HTTP] Flow >> "[HTTP Module][%s] ret : %d"
Line 2371: [HTTP] Warn >> "[HTTP Module] Authentication Algorithm not supported"
Line 2626: [HTTP] Warn >> "Receiced response_status_line is NULL"
Line 2655: [HTTP] Warn >> "Receiced response_status_line is NULL"
Line 2694: [HTTP] Warn >> "Receiced response_status_line is NULL"
Line 2735: [HTTP] Warn >> "Receiced response_status_line is NULL"
Line 2792: [HTTP] Warn >> "Receiced response_status_line is NULL"
