Line 86:    >>IDLE_INTER FREQ NULL
Line 104: [SLOTINFO] NO UPDATED. LAST_MEASTYPE (%d) RECEIVE_MEASTYPE (%d)
Line 116:    >>[SLOTINFO] INTER SRCH OBJID %d removed
Line 121: [SLOTINFO] NO UPDATED. LAST_MEASTYPE (%d) RECEIVE_MEASTYPE (%d)
Line 132:    >>[SLOTINFO] INTER MEAS OBJID %d removed
Line 137: [SLOTINFO] NO UPDATED. LAST_MEASTYPE (%d) RECEIVE_MEASTYPE (%d)
Line 174:    >>TriggerInterMeas FREQ %d ONGOING %d, PBCH %d, ALLMEAS %d, LOW_SRCH %d
Line 183:    >>IDLE_INTER SRCH_I
Line 190:       ::AddNCellT amount (%d)
Line 196:    >>IDLE_INTER MEAS_I
Line 201: 	>>IDLE_INTER MEAS_I RESOLVE.
Line 207:    >>IDLE_INTER MEAS_I RESOLVE.
Line 219:       ::AddNCellT amount (%d)
Line 233:    >>IDLE_INTER MEAS_T MeasType (enum)%d
Line 253:    >>IDLE_INTER FREQ %d ONGOING.
Line 277:    >>MATCH FREQ PRIORITY.
Line 286:    >>NOT MATCH FREQ PRIORITY. FAIL VALIDATION
Line 299:    >>INVALID EARLY MEASURE FREQ %d SIB_FREQ %d, EM_FREQ %d, EM_ISPERFORM %d
Line 320: ResolveRescheduleInfo for INTER_FREQ
