Line 143: [NbPhyTxNpuschCtrlr][RequestTimeCtrlr] type[%d], harqId[%d], repeatNum[%d], targetTime[%d/%d/%d], subcrSpacing[%d], stSubCarrier[%d], nrOfNumSubcarrier[%d]
Line 166: [NbPhyTxNpuschCtrlr][RequestTxDev] (F) No UL Grant Cnf from L2. Not request process to Tx Dev. status[%d]
Line 170: [NbPhyTxNpuschCtrlr][RequestTxDev] (F) Abnormal Status. Not request process to Tx Dev. status[%d]
Line 243: [NbPhyTxNpuschCtrlr][RequestTxDev] format[%d], harqId[%d], NB_TX_CODEBK_LEN[%d], RM_OFFSET[%d], rv_val[%d], TTI_CNT[%d]
Line 264: (F) Repetition Count Mismatch with TimeCtrlr crtUlTtiNum[%d], repCnt[%d]
Line 314: [NbPhyTxNpuschCtrlr][HandleMsg3Grant] Discard MSG3 Grant. cause[%d]
Line 338: [NbPhyTxNpuschCtrlr][HandleMsg3Grant] Send UL Grant IPC to L2. grant_type[%d], hid[%d], tb_sz[%d], ph[%d], delay[%d], taReportVal:%d
Line 379: [NbPhyTxNpuschCtrlr][HandleUlGrant] Discard UL Grant. cause[%d]
Line 399: [NbPhyTxNpuschCtrlr][HandleUlGrant] Send UL Grant IPC to L2. grant_type[%d], hid[%d], tb_sz[%d], ph[%d], delay[%d]
Line 406: [NbPhyTxNpuschCtrlr][HandleUlGrant] NPUSCH retransmission
Line 485: [NbPhyTxNpuschCtrlr][HandleDlGrant] harqId[%d], harqAckIdx[%d], ANHarqState[%d], subcrIdx[%d], repetition[%d], decSkip[%d], delay[%d], dlEndTime[%d/%d/%d]
Line 503: [NbPhyTxNpuschCtrlr][HandleNpdschAckNack] crcRes[%d], harqId[%d], ackNackRnti[%d], relAckState[%d], relAckHarqId[%d]
Line 525: [NbPhyTxNpuschCtrlr][HandleUlGrantCnf] Request process to Tx Dev for UL Grant CNF, harqAddress[0x%x], harqId[%d], CODEBK_LEN[%d], I_RU[%d], I_TBS[%d]
Line 573: [NbPhyTxNpuschCtrlr][CalcMsg3Grant] Invalid Subcarrier Index Value[%d]
Line 616: [NbPhyTxNpuschCtrlr][CalcM3Grant] SubcrSpacing[%d], subcarInd[%d], subcrIdx[%d], subcrNum[%d], slotNum[%d], delay[%d], rep[%d], MCSInd[%d], mod[%d], ruNum[%d]
Line 662: [NbPhyTxNpuschCtrlr][CalcUlGrant] Invalid Subcarrier Index Value[%d]
Line 676: [NbPhyTxNpuschCtrlr][CalcUlGrant] Invalid MCS Index[%d], subcrNum[%d]
Line 689: [NbPhyTxNpuschCtrlr][CalcUlGrant] Invalid RuAssignIdx[%d]
Line 705: [NbPhyTxNpuschCtrlr] Different with previous TBS. prev[%d], cur[%d]
Line 717: [NbPhyTxNpuschCtrlr][CalcUlGrant] SubcrSpacing[%d], subcarInd[%d], subcrIdx[%d], subcrNum[%d], slotNum[%d], delay[%d], rep[%d], MCSInd[%d], mod[%d], ruNum[%d]
Line 720: [NbPhyTxNpuschCtrlr][CalcUlGrant2] tbsIdx[%d], n0Rnti[%d], newDataFlag[%d], ndi[prv/crt][%d/%d], flagFalseAlarm[%d]
Line 764: [NbPhyTxNpuschCtrlr] Schedule NPUSCH. TotalTTINum[%d], TotalIdtTTINum[%d], IdtRep[%d], dlEndTime[%d/%d/%d], ulTargetTime[%d/%d/%d], diffTime[%d]
Line 773: [NbPhyTxNpuschCtrlr][CheckMsg3Rnti] connectFlag[%d], msg4Rnti[%d]
Line 819: [NbPhyTxNpuschCtrlr] CalcPowerHeadRoom. powerHeadRoom[%d], p0npusch[%d], alpha[%d], pathloss[%d], p0nominal[%d], p0ue[%d], maxPower[%d]
Line 863: [NbPhyTxNpuschCtrlr][ManageRepetition] crtUlTtiNum[%d], idtTtiNum[%d], idtRuTtiNum[%d], ruIdx[%d], ruCrt[%d], ruStartNum[ruCrt][%d], slotNum[%d], identicalRepBundle[%d], AllSymbols[%d], srsFlag[%d]
Line 923: [NbPhyTxNpuschCtrlr][ManageLastRep] Request Process to RX Proc. harqId[%d], format[%d], dataType[%d], crcRes[%d], scsFlag[%d], RntiType[%d], currProc[%d], EndPos[%d/%d/%d]
Line 930: [NbPhyTxNpuschCtrlr][ManageLastRep] L2_PHY_NBIOT_NPUSCH_TRANS_DONE_IND
Line 988: [NbPhyTxNpuschCtrlr][ConfigSingleCarrierDmrs][Format2] slotNum[%d], ocPrbs[%d/%d], uIdx[%d/%d], DMRS_F2_OC[%d/%d], W_N[%d/%d]
Line 1004: [NbPhyTxNpuschCtrlr][ConfigSingleCarrierDmrs] SubcrSpacing[%d], crtSlot[%d], prbs0/1[%d/%d], uIdx0/1[%d/%d], w_n0/1[%d/%d], cellId[%d]
Line 1130: [NbPhyTxNpuschCtrlr][CalcScrambling] Cinit[0x%x], rntiVal[0x%x], SFN/Subframe/Slot[%d/%d/%d], cellId[%d]
Line 1150: [NbPhyTxNpuschCtrlr][CalcDataBit] dataPerRuSbc[%d], dataPerTti[%d]
Line 1315: [NbPhyTxNpuschCtrlr][CalcNpuschPower] txPower[%d], maxPower[%d], rep[%d], m_Npusch[%d], pathloss[%d], alpha[%d], p0Nominal[%d], p0Ue[%d]
Line 1338: [NbPhyTxNpuschCtrlr][UpdateRrcAckReq] harqId[%d], state[%d]
Line 1351: [NbPhyTxNpuschCtrlr][ManageLastRep] L1C_PHY_NBIOT_RRC_ACK_CNF
Line 1410: [NbPhyTxNpuschCtrlr][ConfigMtmParam] repeatNum[%d], period[%d], targetTime[%d/%d/%d], subcrSpacing[%d], maxPower[%d]
Line 1430: [NbPhyTxNpuschCtrlr][CalcMtmParam] Invalid period in subcrSpacint 3.75kHz
Line 1440: [NbPhyTxNpuschCtrlr][CalcMtmParam] Invalid Subcarrier Index Value[%d]
Line 1466: [NbPhyTxNpuschCtrlr][CalcMtmParam] Invalid Subcarrier Index Value[%d]
Line 1487: [NbPhyTxNpuschCtrlr][CalcMtmParam] Invalid Modulation Order[%d], subcrNum[%d]
Line 1505: [NbPhyTxNpuschCtrlr][CalcMtmParam] subcrSpacing[%d], i_sc[%d], subcrIdx[%d], subcrNum[%d], slotNum[%d], mcs[%d], mod[%d], ruIdx[%d], ruNum[%d], repetition[%d]
Line 1524: [NbPhyTxNpuschCtrlr][CalcNpuschScheduleInfo] Invalid MTM offset offset[%d], period[%d], txLength[%d], subcrSpacint[%d]
Line 1547: [NbPhyTxNpuschCtrlr][CalcNpuschScheduleInfo] Schedule NPUSCH. TotalTTINum[%d], TotalIdtTTINum[%d], currentTime[%d], curTime[%d/%d/%d], targetTime[%d/%d/%d]
Line 1563: [NbPhyTxNpuschCtrlr][ConfigNpuschMtm] (F) Repetition Count Mismatch with TimeCtrlr crtUlTtiNum[%d], repCnt[%d]
Line 1652: [NbPhyTxNpuschCtrlr][RequestTxDevMtm] format[%d], harqId[%d], NB_TX_CODEBK_LEN[%d], RM_OFFSET[%d], rv_val[%d], TTI_CNT[%d]
Line 1684: [NbPhyTxNpuschCtrlr][UpdateMetric] numPUSCHSarLimit[%d],numPUSCHPmaxLimit[%d],numPUSCHs[%d],sarMode[%d]
