Line 44: [DVFS_CPU_LOG] [SetMinLockFreqScenario] Fail Owner(%d) Scenario(%d) Filename(%s) Linenum(%d)
Line 52: [DVFS_CPU_LOG] [SetMinLockFreqScenario(FIQ>IRQ)] Owner(%d,%s) Scenario(%d,%s) Filename(%s) Linenum(%d)
Line 60: [DVFS_CPU_LOG] [SetMinLockFreqScenario] Owner(%d,%s) Scenario(%d,%s) Filename(%s) Linenum(%d)
Line 70: [DVFS_CPU_LOG] [RemoveMinLockFreqScenario] Fail Owner(%d) Filename(%s) Linenum(%d)
Line 78: [DVFS_CPU_LOG] [RemoveMinLockFreqScenario(FIQ>IRQ)] Owner(%d,%s) Filename(%s) Linenum(%d)
Line 86: [DVFS_CPU_LOG] [RemoveMinLockFreqScenario] Owner(%d,%s) Filename(%s) Linenum(%d)
Line 96: [DVFS_CPU_LOG] [SetMaxLockFreqScenario] Fail Owner(%d) Scenario(%d) Filename(%s) Linenum(%d)
Line 104: [DVFS_CPU_LOG] [SetMaxLockFreqScenario(FIQ>IRQ)] Owner(%d,%s) Scenario(%d) Filename(%s) Linenum(%d)
Line 112: [DVFS_CPU_LOG] [SetMaxLockFreqScenario] Owner(%d,%s) Scenario(%d) Filename(%s) Linenum(%d)
Line 122: [DVFS_CPU_LOG] [RemoveMaxLockFreqScenario] Fail Owner(%d) Filename(%s) Linenum(%d)
Line 130: [DVFS_CPU_LOG] [RemoveMaxLockFreqScenario(FIQ>IRQ)] Owner(%d,%s) Filename(%s) Linenum(%d)
Line 138: [DVFS_CPU_LOG] [RemoveMaxLockFreqScenario] Owner(%d,%s) Filename(%s) Linenum(%d)
