Line 300: [NR_BWP_PROC] Change detected SSB Idx to %d from %d 
Line 403: [PHYPROC][BWP] NrTargetBwpInfo(%4d), RxfBw(%d), FftStartOffset(%d), ActiveBwpId: Target(UL(%d)/DL(%d) Current(UL(%d)/DL(%d)) BwpSwitch(support/delay)(%d), m_AgapRecoverFlag(%d)
Line 415: [PHYPROC][BWP] NrTargetBwp(%d), NrCurrentBwp(%d), (targetBwp is InitBwp), use_firstPDCCH-MonitoringOccasionOfPO_OfInitbwp(%d) pPcchConfig_present(%d)
Line 429: [BWPPROC][MOD] IsPhyConfigUpdateRequired=%d
Line 447: [PHYPROC][BWP] SCELL UL-BWP UPDATE: m_CcIdx/sCellIndex/arrayIndex/targetUlBwpId = (%d/%d/%d/%d)
Line 466: [PHYPROC][BWP] SCELL DL-BWP UPDATE: m_CcIdx/sCellIndex/arrayIndex/targetUlBwpId = (%d/%d/%d/%d)
Line 487: [PHYPROC][BWP] DefaultDlBwpCfg: (flag(%d)/BwpId(%d)) InactivityTimer(flag(%d)/timer(%d)/timerInslot(%d))
Line 513: [PHYPROC][BWP] (I)Do not handle IPC: CmdInfo(%d) EventInfo(%d)
Line 524: [PHYPROC][BWP] SYS_PARAM_CHG Release, CmdInfo(%d)
Line 528: [PHYPROC][BWP] (I)Do not handle IPC: CmdInfo(%d) EventInfo(%d)
Line 575: [PHYPROC][BWP] Do not copy SCELL config (Cc/Scell/Array/mCc)(%d/%d/%d/%d) 
Line 593: [PHYPROC][BWP] CcIndex(%d), sCellIndex(%d), arrayIndex(%d), ActiveBwp(status/id):UL(%d/%d)/DL(%d/%d) supportBwpSwitch(%d), freqRange(%d)
Line 623: [PHYPROC][BWP][SCELL] DefaultDlBwpCfg: (flag(%d)/BwpId(%d)) InactivityTimer(flag(%d)/timer(%d)/timerInslot(%d))
Line 652: [PHYPROC][BWP] (I)Do not handle IPC: Cmd(%d)
Line 714: [BWP_PROC]valid(Coreset0(1)/SearchSpace0(1))[%02d], Coreset0:(tIdx,val(2/2))[%d], (mPattern,numRb,numSymbol(2/2/2))[%d], OffsetVal[%d], SearchSpace0:(tIdx,val(2/2))[%d], (numSSsetPerSolt,monitoringOccastion)(2/2)[%d], kSSB[%d](pbchPayload(%d), ssbOffset(%d))
Line 755: [BWP_PROC][AGAP] valid(Coreset0(1)/SearchSpace0(1))[%02d], Coreset0:(tIdx,val(2/2))[%d], (mPattern,numRb,numSymbol(2/2/2))[%d], OffsetVal[%d], SearchSpace0:(tIdx,val(2/2))[%d], (numSSsetPerSolt,monitoringOccastion)(2/2)[%d], kSSB[%d](pbchPayload(%d), ssbOffset(%d))
Line 773: [NR IPC] L1C_PHY_MIB_ACQ_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d), cmd(%d), n0(%d)
Line 840: [BWP_PROC]valid(Coreset0(1)/SearchSpace0(1))[%02d], Coreset0:(tIdx,val(2/2))[%d], (mPattern,numRb,numSymbol(2/2/2))[%d], OffsetVal[%d], SearchSpace0:(tIdx,val(2/2))[%d], (numSSsetPerSolt,monitoringOccastion)(2/2)[%d], kSSB[%d](pbchPayload(%d), ssbOffset(%d))
Line 890: [AGAP_SIB1] Set for target cell : cmd(%d), event(%d), chgVal(%d), agapSib1OnFlag(%d)
Line 904: [AGAP_SIB1] Recover for Serving Cell
Line 988: (f) [StoreScellTciState] demod_cc = %d, scell_idex = %d
Line 1001: [PHYPROC][BWP] StoreScellTciState: valid(%d), ServingCellId(%d), CoresetId(%d), TciStateId(%d), SlotIdx(%d), demod_cc(%d)
Line 1024: [PHYPROC][BWP] StorePcellTciState: valid(%d), ServingCellId(%d), CoresetId(%d), TciStateId(%d), SlotIdx(%d), demod_cc(%d)
Line 1049: [PHYPROC][BWP] ConfigPdcchTciState: ServingCellId(%d), CoresetId(%d), TciStateId(%d), IsScellFlag(%d)
Line 1132: [PHYPROC][BWP] PDCCH Active TCI state Info: CoresetId(%d), aslotIdx(%d), tciStateId(%d), qclType0/1:valid/cell/bwp/rstype/rsindex/qcltype(1/2/1/1/3/1):(%d,%d)
Line 1136: (f)[PHYPROC][BWP] ConfigPdcchTciState: CoresetId%d is not configured.!!!
Line 1177: [PHYPROC][BWP] ConfigPdcchTciStateDisable: valid(%d), ServingCellId(%d), CoresetId(%d), TciStateId(%d), SlotIdx(%d), m_CcIdx(%d)
Line 1208: (f)[PHYPROC][BWP] ConfigPdschTciStatesActDeact: BwpId %d is not equal to ActiveDlBwpId %d.!!!
Line 1217: [PHYPROC][BWP] ConfigPdschTciStatesActDeact: ServingCellId(%d), BwpId(%d), ActTciState(0x%x,0x%x,0x%x,0x%x)
Line 1303: [PHYPROC][BWP] ConfigPdschTciStatesActDeact: iOct,iBit(%d), cnt(%d), valid(%d), tciStateId(%d), qclType0:valid(%d), servCellIndex(%d), bwpId(%d), rsType(%d), rsIndex(%d), qclType(%d)
Line 1441: [GetUeCapaInfo] maxNumberMIMO_LayersPDSCH(%d), numTxAnt(%d)
Line 1444: (F)Error in GetUeCapaInfo: m_CcIdx(%d)
Line 1523: (F)ERROR in type0Scs(%d) SystemBW(%d)for FR1
Line 1531: (F)ERROR in freqRange(%d)
Line 1535: [BWPPROC]GetSystemBandwidth: SystemBW(%d) freqRange(%d) type0Scs(%d) StartPrb(%d) Length(%d)
Line 1537: (F)ERROR in SCS(%d) SystemBW(%d)
Line 1643: [NR IPC][GetRxPathmap]CC(%d) (cc/div_cc/00/RxMode : 0x%08x)(rtg/rfd/rf/rf_div : 0x%08x)
Line 1860: GetPcellBwpCfgForScell: NumOfDlDataToULACK(%d)/harqAckCodebook:flag_valid(%d/%d)/value_sp(%d)/dc(%d)/tx(%d)
Line 1891: (F)ERROR in GetScellActiveBwpCfg: ScellArrayIdx(%d)
Line 2076: (F)ERROR in GetInitialBwpCfg: BwpLinkType(%d)
Line 2103: (F)ERROR in GetInitialBwpCfg: BwpLinkType(%d)
Line 2106: (F)ERROR in GetInitialBwpCfg: sCellIndex(%d)(%d)
Line 2189: (F)ERROR in GetScellAllBwpCfg: BwpLinkType(%d)
Line 2192: (F)ERROR in GetScellAllBwpCfg: sCellIndex(%d)(%d)
Line 2217: (F)Invalid SCell Config for tx - CaProc.status (%d)
Line 2222: (F)Invalid SCell Config for tx - CaProcToBwpProc.status (%d)
Line 2230: [GetScellAllCfgForTx] TxScellCfg ccIndex (%d) array is cleared
Line 2244: (F)ERROR in GetScellAllCfgForTx: ScellArrayIdx(%d)
Line 2269: [GetScellAllCfgForTx] TxScellCfg ccIndex (%d) index (%d) bwpId (%d) bwp_Common.present_flag (0x%08X) BwpDownlink.present_flag (0x%08X)
Line 2275: (F)Invalid SCell Config for tx - ActiveBwpInfoDl.status (%d)
Line 2301: [BWPPROC][MOD] GetActiveBwpUlCfg_BwpCommon: flag(%d)/update(%d)
Line 2337: [BWPPROC][MOD] GetActiveBwpUlCfg_BwpDedi: flag(%d)/update(%d)
Line 2381: [BWPPROC][MOD] GetActiveBwpDlCfg_BwpCommon: flag(%d)/update(%d)
Line 2413: [BWPPROC][MOD] GetActiveBwpDlCfg_BwpDedi: flag(%d)/update(%d)
Line 2528: [PHY_PROC][BWP][UL] locationandbandwidth(%d), SCS_BWP/CARRIER(%d/%d), offsetToCarrier(%d), RB_start(%d), m_BwpProcDb.m_StartPrbUl(%d)/CrbUl(%d), m_BwpProcDb.m_LengthDl(%d), status_reg(%d)/(%d)
Line 2631: [PHY_PROC][INIT_BWP][UL] locationandbandwidth(%d), SCS_BWP/CARRIER(%d/%d), offsetToCarrier(%d), RB_start(%d), m_BwpProcDb.m_StartPrbUl(%d)/CrbUl(%d), m_BwpProcDb.m_LengthDl(%d), status_reg(%d)/(%d)
Line 2768: [GetAllBwpCfg] NumBwpList[%d], BwpId[%d], TimeDomainAlloc[%d] - K0.IE[%d], K0[%d], mappingType[%d], startSymbolAndLength[%d]
Line 3051: (F)Error in GetActiveBwpDlCfg_StartPrbAndLen: m_BwpProcDb.m_p_BwpDl is NULL! StartPrbDl(%d), LengthDl(%d) or It is scell(%d)
Line 3134: [PHY_PROC][BWP][DL] locationandbandwidth(%d), SCS_BWP/CARRIER(%d/%d), offsetToCarrier(%d), RB_start(%d), m_BwpProcDb.m_StartPrbDl(%d)/CrbDl(%d), m_BwpProcDb.m_LengthDl(%d), status_reg(%d)/(%d)
Line 3213: [PHY_PROC][BWP][DL][SCELL] locationandbandwidth(%d), SCS_BWP/CARRIER(%d/%d), offsetToCarrier(%d), RB_start(%d), m_BwpProcDb.m_StartPrbDl(%d)/CrbDl(%d), m_BwpProcDb.m_LengthDl(%d)
Line 3289: [PHY_PROC][BWP][UL][SCELL] locationandbandwidth(%d), SCS_BWP/CARRIER(%d/%d), offsetToCarrier(%d), RB_start(%d), m_BwpProcDb.m_StartPrbUl(%d)/CrbUl(%d), m_BwpProcDb.m_LengthUl(%d)
Line 3332: [PHY_PROC][BWP][DL] CoresetZero: valid(%d)/value(%d), SearchSpaceZero: valid(%d)/value(%d)
Line 3434: [PHY_PROC][INIT_BWP][DL] locationandbandwidth(%d), SCS_BWP/CARRIER(%d/%d), offsetToCarrier(%d), RB_start(%d), m_BwpProcDb.m_StartPrbDl(%d)/CrbDl(%d), m_BwpProcDb.m_LengthDl(%d), status_reg(%d)/(%d)
Line 3694: [BWP_DLPARAMTYPE_GENERICPARAM] Idx(%d), BwpId(%d), StartPrb(%d), Length(%d), RA Type(%d), RbgSize(%d), pdschCfgMcsTable: cfg(%d), value(%d), R17: cfg(%d), value(%d)
Line 3725: [BWP_ULPARAMTYPE_GENERICPARAM] Idx(%d), BwpId(%d), StartPrb(%d), Length(%d), subcarrierSpacing(%d), cyclicprefix(%d), RA Type(%d), RbgSize(%d)
Line 3764: (F)ERROR in freqRange(%d)/subcarrierSpacingCommon(%d)
Line 3775: [PHY_PROC][SIB1] controlResourceSet0(%d), ssbScs(%d), type0Scs(%d), minChBw(%d), k_ssb(%d), m_SsbTypefor30k(%d), freqRange(%d), subcarrierSpacingCommon(%d)
Line 3791: (F)ERROR in freqRange(%d)/subcarrierSpacingCommon(%d)
Line 3802: [PHY_PROC][SIB1 AGAP] controlResourceSet0(%d), ssbScs(%d), type0Scs(%d), minChBw(%d), k_ssb(%d), m_SsbTypefor30k(%d), freqRange(%d), subcarrierSpacingCommon(%d)
Line 3818: (F)ERROR in freqRange(%d)/subcarrierSpacingCommon(%d)
Line 3829: [PHY_PROC][SIB1] controlResourceSet0(%d), ssbScs(%d), type0Scs(%d), minChBw(%d), k_ssb(%d), m_SsbTypefor30k(%d), freqRange(%d), subcarrierSpacingCommon(%d)
Line 3850: (F) Invalid CoresetZero parameters: ssbScs(%d), type0Scs(%d), minChBw(%d)
Line 3863: (F) Invalid CoresetZero parameters: ssbScs(%d), type0Scs(%d), minChBw(%d)
Line 3926: (F) Invalid CoresetZero parameters: ssbScs(%d), type0Scs(%d), minChBw(%d)
Line 3939: (F) Invalid CoresetZero parameters: ssbScs(%d), type0Scs(%d), minChBw(%d)
Line 4724: [PHYPROC][BWP] RestoreScellTciState: valid(%d), ServingCellId(%d), CoresetId(%d), TciStateId(%d), SlotIdx(%d), m_CcIdx(%d)
Line 4759: [GetScellAllCfgForTx] TxScellCfg ccIndex (%d) array is cleared
Line 4856: [NrPhyBwpProc] UpdateDormancyIndicationBitLength  NumOfScell(%d)
Line 4865: [NrPhyBwpProc] NrScellConfig.present_flag(0x%x), sCellConfigDedicated.present_flag(0x%x), dormantBWP_Config.present_flag(0x%x), dormantBWP_Config.withinActiveTimeConfig_r16.present_flag(0x%x)
Line 4876: [NrPhyBwpProc] OutsideDormancyGroupExist[%d] = TRUE 
Line 4884: [NrPhyBwpProc] WithinDormancyGroupExist[%d] = TRUE 
Line 4898: [NrPhyBwpProc] NumOfDormancyGroup of OutsideActiveTime(%d), WithinActiveTime(%d) 
