Line 37: [D :SM,%d]       (constructor) NrSmStateBase()
Line 42: [D :SM,%d]       (distructor) ~NrSmStateBase()
Line 63: [E :SM,%d]   *** %s (%s) ***
Line 63: [N :SM,%d]     %s - Ignore %s
Line 68: [E :SM,%d]   *** %s (%s) ***
Line 68: [N :SM,%d]     %s - Ignore %s
Line 73: [E :SM,%d]   *** %s (%s) ***
Line 73: [N :SM,%d]     %s - Ignore %s
Line 78: [E :SM,%d]   *** %s (%s) ***
Line 78: [N :SM,%d]     %s - Ignore %s
Line 83: [E :SM,%d]   *** %s (%s) ***
Line 83: [N :SM,%d]     %s - Ignore %s
Line 88: [E :SM,%d]   *** %s (%s) ***
Line 88: [N :SM,%d]     %s - Ignore %s
Line 93: [E :SM,%d]   *** %s (%s) ***
Line 93: [N :SM,%d]     %s - Ignore %s
Line 98: [E :SM,%d]   *** %s (%s) ***
Line 98: [N :SM,%d]     %s - Ignore %s
Line 103: [E :SM,%d]   *** %s (%s) ***
Line 103: [N :SM,%d]     %s - Ignore %s
Line 108: [E :SM,%d]   *** %s (%s) ***
Line 108: [N :SM,%d]     %s - Ignore %s
Line 113: [E :SM,%d]   *** %s (%s) ***
Line 113: [N :SM,%d]     %s - Ignore %s
Line 118: [E :SM,%d]   *** %s (%s) ***
Line 118: [N :SM,%d]     %s - Ignore %s
Line 123: [E :SM,%d]   *** %s (%s) ***
Line 123: [N :SM,%d]     %s - Ignore %s
Line 128: [E :SM,%d]   *** %s (%s) ***
Line 128: [N :SM,%d]     %s - Ignore %s
Line 133: [E :SM,%d]   *** %s (%s) ***
Line 133: [N :SM,%d]     %s - Ignore %s
Line 138: [E :SM,%d]   *** %s (%s) ***
Line 138: [N :SM,%d]     %s - Ignore %s
Line 143: [E :SM,%d]   *** %s (%s) ***
Line 143: [N :SM,%d]     %s - Ignore %s
Line 148: [E :SM,%d]   *** %s (%s) ***
Line 148: [N :SM,%d]     %s - Ignore %s
Line 153: [E :SM,%d]   *** %s (%s) ***
Line 153: [N :SM,%d]     %s - Ignore %s
Line 158: [E :SM,%d]   *** %s (%s) ***
Line 158: [N :SM,%d]     %s - Ignore %s
Line 163: [E :SM,%d]   *** %s (%s) ***
Line 163: [N :SM,%d]     %s - Ignore %s
Line 168: [E :SM,%d]   *** %s (%s) ***
Line 168: [N :SM,%d]     %s - Ignore %s
Line 173: [E :SM,%d]   *** %s (%s) ***
Line 173: [N :SM,%d]     %s - Ignore %s
