Line 114: [DCCCH] ERROR: controlResourceSetId(%d)
Line 139: [DCCCH] ERROR: controlResourceSetId(%d)
Line 159: [DCCCH][SetCInitvalue] presentflag(common/dedi)(%d)/(%d), css_yinit(0x%x), uss_yinit(0x%x/0x%x/0x%x/0x%x/0x%x) NrDcDevBgTask_CchReconfig: done(%d), bitmapOfCoresetYinitIsCellId(%d)
Line 196: [DCCCH]hashY ssId(%d) 0[%d]1[%d]2[%d]3[%d]4[%d]5[%d]
Line 225: [DCCCH][CalNumCCE] Coreset Id is mismatched! present_flag(0x%x), coresetId(%d), Indicated CoresetId(%d)
Line 238: [DCCCH][CalNumCCE] ssId(%d) rrcSSId(%d), coresetId(%d), rrcCoresetId(%d),coresetlength(%d), assigned_cchrbnum(%d), m_NumCCE(%d) totalCCHRE(%d) NumREperCCE(%d)
Line 314: [DCCCH] searchSpaceId(%d), XRSconfig_enableFlag(%d), MAX_CAND_NUM AL1/2/4/8/16(%d/%d/%d/%d/%d)
Line 333: [DCCCH] searchSpaceId(%d), CC_CAND_NUM AL1/2/4/8/16(%d/%d/%d/%d/%d)
Line 425: [DCCCH] Wrong Coreset Index :coresetId(%d), csIdx(%d), searchSpaceId(%d), ssId(%d)
Line 731: [DCCCH][SetCoresetDemappingBmp]Xrs_flag(%d) mappedCoresetID(%d), mappedCcIdx(%d), demapBmp0(0x%x), demapBmp1(%d)
Line 859: [DCCCH][SetCoresetInfoforDD]coresetId(%d), ra_info(0x%x), ra_info1(0x%x), first_prg_offset(%d), bwpStartCrb(%d), bundle_info(0x%x), RBoffset_FFT(%d)
Line 1010: [DCCCH] DCI format 0_1 is not expected when txConfig is not configured. txConfig(%d)
Line 1167: [DCCCH]CalDCILength,lengthofFMT0/1/2/3(2/2/2/2)(%d),carrierInd(%d),FDRAULT0/T1/InitUL(2/2/2)(%d),fmt01BWP/UL_SUL/TDRA/frhop/DLaIdx1/DLaIdx2/TPC/SRS(%d), fmt01PrecInfo/antPorts/CSI/cbg/asso_PTRS_DMRS/beta/DmrsSeq/UL_SCH_indi(%d),FDRADLT0/T1/C0_Init(2/2/2)(%d), fmt11BWP/TDRA/vrb2prb/prbB/rateM/zpCsi/DLaIdx/Pdsch2HarqF(%d),antPorts/transC/srsReq/cbgT/cbgFl/DmrsS/dormancyInd(%d), NrCaState(%d), DciAlignInfo(0x%08x)
Line 1564: [DCCCH]Set Forced PUSCH maxRank 1 when NR_TRANSFORM_PRECODER is ENABLED, rrc PUSCH maxRank(%d)
Line 1587: [DCCCH]CalFormat0_1, Fail to set the size of PrecodingInfo(Table 7.3.1.2-3/3A). antennaPorts(%d), transformPrecoder(%d), maxRank(%d), fullPowerTransmission_configured(%d), ul_FullPowerTransmission_r16(%d)
Line 1598: [DCCCH]CalFormat0_1, Fail to set the size of PrecodingInfo(Table 7.3.1.2-4/4A). antennaPorts(%d), transformPrecoder(%d), maxRank(%d), fullPowerTransmission_configured(%d), ul_FullPowerTransmission_r16(%d)
Line 1609: [DCCCH]CalFormat0_1, Fail to set the size of PrecodingInfo(Table 7.3.1.2-5/5A). antennaPorts(%d), transformPrecoder(%d), maxRank(%d), fullPowerTransmission_configured(%d), ul_FullPowerTransmission_r16(%d)
Line 1653: [DCCCH] AntPortsFail! dmrs_UplinkForPusch_presentflag(%d), 
Line 1709: [DCCCH]CalFormat0_1 numOfDormancyGroupWithinActiveTime(%d)
Line 2348: [DCCCH]CalFAMetric TH_pm00/10(4/4)(%d), TH_pm20/30(4/4)(%d), TH_pm01/02(4/4)(%d), TH_pm03/04(4/4)(%d), TH_pm11/12(4/4)(%d), TH_pm13/14(4/4)(%d), TH_pm21/22(4/4)(%d), TH_pm23/24(4/4)(%d),TH_pm31/32(4/4)(%d), TH_pm33/34(4/4)(%d)
Line 2361: [DCCCH]CalFAMetric TH_ser00/10(4/4)(%d), TH_ser20/30(4/4)(%d),TH_ser01/02(4/4)(%d), TH_ser03/04(4/4)(%d), TH_ser11/12(4/4)(%d), TH_ser13/14(4/4)(%d), TH_ser21/22(4/4)(%d), TH_ser23/24(4/4)(%d),TH_ser31/32(4/4)(%d), TH_ser33/34(4/4)(%d)
Line 2364: [BACKGROUND TASK] NrDcDevBgTask_CchReconfig: done(%d)
Line 2421: [DCCCH][CalRAsize] Invalid nRB(%d), typeRA(%d), LinkType(%d)
Line 2427: [DCCCH][CalRAsize]nRB(%d), typeRA (%d) raSize(%d), rbgConfig(%d), LinkType(%d), bwpStartPrb(%d)
Line 2492: [DCCCH] CalAntPortsFail! Check MappingType(%d),transformPrecoder(%d), maxLength(%d) 
Line 2495: [DCCCH] CalAntPortSize(%d), MappingType(%d),transformPrecoder(%d), dmrs_TypeUL(%d), maxLength(%d) 
Line 2645: [BACKGROUND TASK] NrDcDevBgTask_CchReconfig: done(%d)
Line 2709: dci_tdra_k2_idx_bitmap(0x%x), CC0_DCI_COMMON_CTR_1(0x%x), k2DediCfg(%d), k2CommCfg(%d)
Line 2787: [DCCCH] Coresets of USS Type0 is overlapped with that of Ra-SearchSpace , CoresetBitmapOfUssOverlappedWithRaSs(%x)
Line 2830: [DCCCH] UE is not expected to monitor Type1Pdcch with C-RNTI when there's Type3Pdcch or USS. type3PdcchExist(%d), bitmapOfUssCoresetOverlappedWithRaSs(0x%x), bitmapOfCoresetYinitIsCellId(0x%x)
