Line 113: ##[NR_RRC_INTF] CalcFddUlFreqFromDlFreq: dl_freq(%d), band(%d), spacing(%d), ul_freq(%d)
Line 143: ##[NR_RRC_INTF] CalcTxDcScOffset:: Outside the carrier, ABS(%d), bwp_bw_khz/2(%d)
Line 147: ##[NR_RRC_INTF] CalcTxDcScOffset:: rf_ul_freq(%d), bwp_freq(%d), sys_bw_khz(%d), bwp_bw_khz(%d),  bwp_scs(%d)=> offset(%d)
Line 168: ##[NR_RRC_INTF] GetTxDcListInfo(PCELL) : num_of_cell(%d), scell_idx(%d), dl_bwp_mask(0x%x), ul_bwp_mask(0x%x), duplex_mode(%d)
Line 186: ##[NR_RRC_INTF] GetTxDcListInfo(PCELL) : point_a(%d), sys_scs(%d), offset_to_carr(%d), carr_bw(%d), prb_lowest_freq(%d), sys_center_freq(%d), act_idx(%d)
Line 197: ##[NR_RRC_INTF] GetTxDcListInfo(PCELL) : bwp_idx(%d) for UplinkTxDirectCurrentBWP is out of range(%d)
Line 222: ##[NR_RRC_INTF] GetTxDcListInfo(PCELL): ********* id(%d), loc_and_bw(U=%d, D=%d), start_crb(%d), len_crb(%d)
Line 252: ##[NR_RRC_INTF] GetTxDcListInfo(PCELL) : bwp_idx(%d) for UplinkTxDirectCurrentBWP is out of range(%d)
Line 257: ##[NR_RRC_INTF] GetTxDcListInfo(PCELL): id[%d], bwp_freq(%d), bwp_bw_khz(%d), rf_ul_freq(%d), sys_bw_khz(%d)
Line 264: ##[NR_RRC_INTF] GetTxDcListInfo(PCELL-RRC_Val): scell_idx(%d), id(%d), num_ul_bwp(%d), shift_7_dot_5(%d), offset(%d)
Line 287: ##[NR_RRC_INTF] GetTxDcListInfo(SCELL) : scell_idx(%d), dl_bwp_mask(0x%x), ul_bwp_mask(0x%x)
Line 298: ##[NR_RRC_INTF] GetTxDcListInfo(SCELL) : point_a(%d), sys_scs(%d), offset_to_carr(%d), carr_bw(%d), prb_lowest_freq(%d), sys_center_freq(%d)
Line 334: ##[NR_RRC_INTF] GetTxDcListInfo(SCELL): ********* id(%d), loc_and_bw(D=%d), start_crb(%d), len_crb(%d), bwp_freq(%d), bwp_bw(%d)
Line 346: ##[NR_RRC_INTF] GetTxDcListInfo(SCELL) : tx_dc_list_num(%d), num_of_cell(%d)
Line 390: ##[NR_RRC_INTF] GetTxDcListInfo(PCELL-RRC_Val) : bwp_idx(%d) for UplinkTxDirectCurrentBWP is out of range(%d)
Line 398: ##[NR_RRC_INTF] GetTxDcListInfo(PCELL-RRC_Val): scell_idx(%d), id(%d), num_ul_bwp(%d), shift_7_dot_5(%d), offset(%d)
Line 432: ##[NRDB] SimulateSlo : CellIdx(%d) min_freq(%d), max_freq(%d) - min_Cell_idx(%d) max_Cell_idx(%d)
Line 438: ##[NRDB] SimulateSlo : IsSloSupport(%d) max_aggr_bw(%d) aggr_bw(%d)
Line 446: ##[NRDB] SimulateSlo : centerRfFreq(%d) rf_bw(%d) RfBwIdx(%d)
Line 481: ##[NRDB] ConvertBwIdx: BW %dkHz is abnormal!!!
