Line 74: ###[TSIC][RSLT] L1C_L1TUNNEL_LTE_TSIC_CONFIG_IND_Handler, stack_id(%d) dr_flag(%d) num_cell(%d)
Line 87: ###[TSIC][RSLT] L1C_L1TUNNEL_LTE_TSIC_RELEASE_IND_Handler:: stack_id(%d) cc(%d)
Line 100: ###[TSIC][RSLT] L1C_L1TUNNEL_LTE_TSIC_SLEEP_IND_Handler:: stackId(%d)
Line 111: ###[TSIC][RSLT] L1C_L1TUNNEL_LTE_TSIC_WAKEUP_IND_Handler:: stackId(%d)
Line 123: ###[TSIC][RSLT] L1C_L1C_TSICCTRLR_TSIC_NR_CONFIG_IND_Handler, stack_id(%d) dr_flag(%d) num_tsic_cell(%d)
Line 136: ###[TSIC][RSLT] L1C_L1C_TSICCTRLR_TSIC_NR_RELEASE_IND_Handler:: stack_id(%d)
Line 150: ###[TSIC][RSLT] L1C_L1C_TSICCTRLR_TSIC_NR_SLEEP_IND_Handler:: stackId(%d)
Line 162: ###[TSIC][RSLT] L1C_L1C_TSICCTRLR_TSIC_NR_WAKEUP_IND_Handler:: stackId(%d)
Line 225: ###[TSIC][RSLT] CHANGE:: cc(%d) Band(%d) UlBwX10(%d) DlBwX10(%d) UlRfFreqkHz(%d) UlFreqkHz(%d) DlFreqkHz(%d) rfPath(%d, %d) demodCc(%d)
Line 231: ###[TSIC][RSLT] UPDATE:: cc(%d) Band(%d) UlBwX10(%d) DlBwX10(%d) UlRfFreqkHz(%d) UlFreqkHz(%d) DlFreqkHz(%d) rfPath(%d, %d) demodCc(%d)
Line 225: ###[TSIC][RSLT] CHANGE:: cc(%d) Band(%d) UlBwX10(%d) DlBwX10(%d) UlRfFreqkHz(%d) UlFreqkHz(%d) DlFreqkHz(%d) rfPath(%d, %d) demodCc(%d)
Line 231: ###[TSIC][RSLT] UPDATE:: cc(%d) Band(%d) UlBwX10(%d) DlBwX10(%d) UlRfFreqkHz(%d) UlFreqkHz(%d) DlFreqkHz(%d) rfPath(%d, %d) demodCc(%d)
