Line 71: [PHY_SI_PROC] PHY_L1C_SIB1_ACQ_REQ: cmd(%d)
Line 91: [SI_PROC] Invalid m_osiScs(%d)
Line 97: [PHY_SI_PROC] PHY_L1C_SIBX_ACQ_REQ: cmd(%d)
Line 109: [PHY_SI_PROC] PHY_PHY_SIBX_SCHED_CHG: sibxSchedState(%d)
Line 126: NrPhySiProc: Handle MAC reset procedure
Line 134: [NR_BWP_PROC] PHY_PHY_AGAP_SIB1CFG_IND (AgapFalg=%d, siRnti=0x%x)
Line 207: [SIB1 DM] cellGroup(%d)
Line 271: [SI_PROC]sibxWindowLength(%d)
Line 281: [SI_PROC]siIdx[%d] : sibxSchedulingInfoListIdx(%d), sibxBroadcastStatus(%d), sibxPeriod(%d)
Line 419: [SI_PROC] Reset SIBX param: cmdInfo(%d), cSibxState(%d->False)
Line 461: [SI_PROC](F) invalid m_osiScs(%d) or windowlen(%d)
Line 477: [SI_PROC](F) index(siListIdx(2)/validNum(2))[%d] : sibxPeriod(%d), sibxSchedulingInfoListIdx(%d)
Line 491: [SI_PROC] index(siListIdx(2)/validNum(2))[%d] : slotInfo(Start(%d)->End(%d) / Period(%d)) : sibxSchedulingInfoListIdx(%d)
Line 582: [SI-DRX] SI doens't have sleep time : numOsiIdx(%d), numSlotShortestPeriod(%d), sibxWindowSize(%d)
Line 599: [SI-DRX] check the wake up slot : nextOsiModIdx(%d), candiWakeUpSlot(%d), modiCandiWakeUpSlot(%d)
Line 604: [SI-DRX] touch the wake up slot : diffOsiIdx(%d), startSlot(%d), endSlot(%d)
Line 618: [SI-DRX] cAlsot(%d), cOsiIdx(%d), nOsiIdx(%d), nOsiModIdx(%d), nextOsiWakeUpSlot(%d)[OsiWindowSize(%d), numSlotShortestPeriod(%d), m_shortestPeriodIdx(%d), m_osiScs(%d), diffOsiIdx(%d)]
Line 679: [SI-DRX] nextWakeUpSlot(%d), ssbTrsWakeUpSlot(%d), current_aslot(%d)
Line 709: [SI_PROC] drx_type(%d), sleep_duration_slots(%d)
Line 742: [SI_PROC] NrSiReadInd(%d)
