Line 64: [MTI_1_CALL] Tx NS_CONNECT_REQ (SId=%d)
Line 64: [MTI_0_CALL] Tx NS_CONNECT_REQ (SId=%d)
Line 89: [MTI_1_CALL] Tx NS_ECT_REQ (SId=%d)
Line 89: [MTI_0_CALL] Tx NS_ECT_REQ (SId=%d)
Line 120: [MTI_1_CALL] Tx NS_REJ_REQ (SId=%d, Cause=0x%X)
Line 120: [MTI_0_CALL] Tx NS_REJ_REQ (SId=%d, Cause=0x%X)
Line 147: [MTI_1_CALL] Tx NS_REL_REQ (SId=%d)
Line 147: [MTI_0_CALL] Tx NS_REL_REQ (SId=%d)
Line 174: [MTI_1_CALL] Tx NS_START_DTMF_REQ (SId=%d, Key=0x%X)
Line 174: [MTI_0_CALL] Tx NS_START_DTMF_REQ (SId=%d, Key=0x%X)
Line 199: [MTI_1_CALL] Tx NS_STOP_DTMF_REQ (SId=%d)
Line 199: [MTI_0_CALL] Tx NS_STOP_DTMF_REQ (SId=%d)
Line 224: [MTI_1_CALL] Tx NS_HOLD_REQ (SId=%d)
Line 224: [MTI_0_CALL] Tx NS_HOLD_REQ (SId=%d)
Line 251: [MTI_1_CALL] Tx NS_MULTI_PARTY_REQ (SId=%d, Command=0x%X)
Line 251: [MTI_0_CALL] Tx NS_MULTI_PARTY_REQ (SId=%d, Command=0x%X)
Line 276: [MTI_1_CALL] Tx NS_RETRIEVE_REQ (SId=%d)
Line 276: [MTI_0_CALL] Tx NS_RETRIEVE_REQ (SId=%d)
Line 327: [MTI_1_SS] Tx NS_CALL_WAITING_STATUS_REQ (SId=%d, Basic Service Code=%d)
Line 327: [MTI_0_SS] Tx NS_CALL_WAITING_STATUS_REQ (SId=%d, Basic Service Code=%d)
Line 354: [MTI_1_SS] Tx NS_CALL_WAITING_ACTIVATE_REQ (SId=%d, Basic Service Code=%d)
Line 354: [MTI_0_SS] Tx NS_CALL_WAITING_ACTIVATE_REQ (SId=%d, Basic Service Code=%d)
Line 381: [MTI_1_SS] Tx NS_CALL_WAITING_DEACTIVATE_REQ (SId=%d, Basic Service Code=%d)
Line 381: [MTI_0_SS] Tx NS_CALL_WAITING_DEACTIVATE_REQ (SId=%d, Basic Service Code=%d)
Line 407: [MTI_1_SS] Tx NS_USSD_TERMINATE_REQ (SId=%d)
Line 407: [MTI_0_SS] Tx NS_USSD_TERMINATE_REQ (SId=%d)
Line 435: [MTI_1_SS] Tx NS_USSD_NOTIFY_RSP (SId=%d)
Line 435: [MTI_0_SS] Tx NS_USSD_NOTIFY_RSP (SId=%d)
Line 462: [MTI_1_SS] Tx NS_BEARER_CAP_SET_REQ (CTM enable=%d)
Line 462: [MTI_0_SS] Tx NS_BEARER_CAP_SET_REQ (CTM enable=%d)
Line 487: [MTI_1_SND] Tx NS_SOUND_MIC_MUTE_REQ (ucMuteStatus=%d)
Line 487: [MTI_0_SND] Tx NS_SOUND_MIC_MUTE_REQ (ucMuteStatus=%d)
Line 512: [MTI_1_SND] Tx NS_SOUND_VOLUME_REQ (usVolumeLevel=%d)
Line 512: [MTI_0_SND] Tx NS_SOUND_VOLUME_REQ (usVolumeLevel=%d)
Line 539: [MTI_1_SND] Tx NS_SOUND_PATH_REQ (ucPath=%d)
Line 539: [MTI_0_SND] Tx NS_SOUND_PATH_REQ (ucPath=%d)
Line 564: [MTI_1_SND] Tx NS_SOUND_TWO_MIC_SOL_CON_REQ (ucMode=%d)
Line 564: [MTI_0_SND] Tx NS_SOUND_TWO_MIC_SOL_CON_REQ (ucMode=%d)
Line 589: [MTI_1_SND] Tx NS_SOUND_CLOCK_REQ (ucStatus=%d)
Line 589: [MTI_0_SND] Tx NS_SOUND_CLOCK_REQ (ucStatus=%d)
Line 616: [MTI_1_SND] Tx NS_SOUND_LOOPBACK_REQ (ucStatus=%d, ucPath=%d)
Line 616: [MTI_0_SND] Tx NS_SOUND_LOOPBACK_REQ (ucStatus=%d, ucPath=%d)
