Line 2300: [SYSTEM] DebugForSystimeIntr(MCG): INT_ENABLE_CPU(0x%x) INT_COMMON_ENABLE_CPU(0x%x) INT_STATUS_CPU(0x%x) INT_PENDING_CPU(0x%x) INT_CLEAR_CPU(0x%x)
Line 3704: [HALSYST_4G] SetHenbBW : bw(%d)
Line 3720: [HALSYST_4G] Invalid RTG idx(%d)
Line 3730: [HALSYST_4G] SetLaaSystime CC0_QUICKSLEEP_ON_CTRL(0x%X), CC0_QUICKSLEEP_ON_TTI(0x%X)
Line 3737: [HALSYST_4G] SetLaaSystime CC1_QUICKSLEEP_ON_CTRL(0x%X), CC1_QUICKSLEEP_ON_TTI(0x%X)
Line 3744: [HALSYST_4G] SetLaaSystime CC2_QUICKSLEEP_ON_CTRL(0x%X), CC2_QUICKSLEEP_ON_TTI(0x%X)
Line 3751: [HALSYST_4G] SetLaaSystime CC3_QUICKSLEEP_ON_CTRL(0x%X), CC3_QUICKSLEEP_ON_TTI(0x%X)
Line 3758: [HALSYST_4G] SetLaaSystime CC4_QUICKSLEEP_ON_CTRL(0x%X), CC4_QUICKSLEEP_ON_TTI(0x%X)
Line 3765: [HALSYST_4G] SetLaaSystime CC5_QUICKSLEEP_ON_CTRL(0x%X), CC5_QUICKSLEEP_ON_TTI(0x%X)
Line 3772: [HALSYST_4G] SetLaaSystime CC6_QUICKSLEEP_ON_CTRL(0x%X), CC6_QUICKSLEEP_ON_TTI(0x%X)
Line 3779: [HALSYST_4G] SetLaaSystime CC7_QUICKSLEEP_ON_CTRL(0x%X), CC7_QUICKSLEEP_ON_TTI(0x%X)
Line 424: [SYSTEM] InitSystemTime: RTG offset(%d), rfd_marsync_config0_prv 0x%08X/0x%08X
Line 552: [SYSTEM] SetDlSystemInfo(MXR%d, RTG%d): sys_info(%08x -> %08x)
Line 594: [SYSTEM] SetDlSystemInfo(MXR%d RTG%d RFD%d CC0_HENB): HENB_SYSTEM_INFO(%08x -> %08x) HENB_RXF_DELAY(0x%x)
Line 615: [SYSTEM] SetDlSystemInfo(MXR%d RTG%d RF%d): sys_info(%08x -> %08x)
Line 2949: [SYSTEM] SetTrxSwitch(RF%d): rtg(%d), sys_info(%08x) dlul_BB(%08x) uldl_BB(%08x) dlul_RFD(%08x) uldl_RFD(%08x)
Line 2959: [SYSTEM] SetTrxSwitch(RF%d): rtg(%d), sys_info(%08x)
Line 740: [SYSTEM] SetDrxMode(RX%d): mode(%d)
Line 781: [SYSTEM] SetDrxStartPos: mode(%d), time(0x%x), drx_counter(0x%x), SFN(%d), TTI(%d), Offset(%d)
Line 832: [SYSTEM] SetIratTriggerSignal: enable(%d), time(%08x), len(%d)
Line 884: [SYSTEM] SetRtgLoad : not workaround for AGAP
Line 995: [SYSTEM] SetRtgLoad [WR](BB_RTG:%d, RFD_RTG:%d): RTG(%x %x) diff(%d) rfd_path_enable(%x %x)
Line 1007: [SYSTEM] SetRtgLoad(BB_RTG:%d, RFD_RTG:%d): offset(%d), RFD_CLK_CONFIG(%x)
Line 1211: [SYSTEM] ConfigRtg(DEBUG): rtg_idx(%d), rtg value too high (%d)
Line 1223: [SYSTEM] ConfigRtg(DEBUG): loop_idx(%d), rtg_counter(%d)...
Line 1232: [SYSTEM] ConfigRtg(DEBUG): loop_idx(%d), rtg_counter(%d) found last symbol
Line 1246: [SYSTEM] ConfigRtg(DEBUG): skip the rtg setting.. rtg_counter(%d, %d, %d, %d, %d, %d, %d) 
Line 1280: [SYSTEM] ConfigRtg(DEBUG): rtg_counter(%d), gen_counter(%d), general_snap(%d), cur_sfn(%d)
Line 1304: [SYSTEM] ConfigRtg(BB_RTG:%d, RFD_RTG:%d): offset(%d), copy(%x), bw(%d), diff(%d), rtg(%d -> %d)
Line 3687: [HALSYST_4G] GetHenbBW : bw(%d)
Line 3383: [SYSTEM] NR RTG counter out of Range(%d)
Line 3427: [L2N_GAP] cur_rtg_counter(%d) gap_rtg_counter(%d) diff_to_gap(%d) nr_rtg_counter(read)(%u)
Line 3466: [L2N_HO] LteRtgCounter(%d) LteGenCounter(%d) LteRtgOffset(%d) SFN(%d) SUBFRAME(%d) OFFSET(%d)
Line 1540: [SYSTEM] RTG%d: bw(%d), diff(%d), rtg(%d -> %d)
Line 1608: [SYSTEM] AlignRtg(BB_RTG:%d, RFD_RTG:%d) : bb_path_enable(%x %x), rfd_path_enable(%x %x)
Line 1699: [SYSTEM] CopyRtg(%d)(RTG%d -> RTG%d)[shift %d]
Line 1792: [SYSTEM] SetSfn(RTG%d): sfn(%d)
Line 2092: [SYSTEM] EnableSysTimeIntr(%d): SYNC_INT_CFG_x[0](0x%x), SYNC_INT_TIME_x[%d](0x%x)
Line 2099: [SYSTEM] EnableSysTimeIntr(%d): frame(%d), tti(%d), offset(%d)
Line 2125: [SYSTEM] EnableSysTimeIntr(%d): SYNC_INT_CFG_x[1](0x%x), SYNC_INT_TIME_x[%d](0x%x)
Line 2132: [SYSTEM] EnableSysTimeIntr(%d): frame(%d), tti(%d), offset(%d)
Line 2188: [SYSTEM] EnableSysTimeIntr(%d): mode(0x%x), time(0x%x)
Line 2240: [SYSTEM] DisableSysTimeIntr(%d)
Line 2269: [SYSTEM] CheckSysTimeCommonIntr: en(0x%08x), pend(0x%08x)
Line 2578: [SYSTEM] SetGapMode(CC%d): mode(%d), bw(%d), length(%d), sfn_tti(%d), offset(%d,%d)
Line 2652: [SYSTEM] SetCaMode(CC%d): on(%d, 0x%x), time(%d), tti_config(0x%x)
Line 2707: [SYSTEM] SetSloOn(CC%d): on(%d) 
Line 2776: [SYSTEM] SetAgcAntSel: path off rf(%d), mxr(%d), rtg(%d), latch_tick_rtg(%d), mxr_list[0](%d), slo_num(%d)
Line 2818: [SYSTEM] SetAgcAntSel(RF%d): rtg(%d), LATCH_TIME(%x) path_enable(%x, %x), path_enable_rfd(%x, %x)
Line 2823: [SYSTEM] SetAgcAntSel[WARNING] : AGC antenna selection update fail, abnormal rtg index(%d)
Line 3143: [SYSTEM] HALSYST_4G_CheckCcGroupingInfo(0x%x): RTG0(%d), RTG1(%d), RTG2(%d), RTG3(%d), RTG4(%d), RTG5(%d)
Line 3144: [SYSTEM] HALSYST_4G_CheckCcGroupingInfo(0x%x): RTG6(%d), RTG7(%d)
Line 3145: [SYSTEM] HALSYST_4G_CheckCcGroupingInfo : CC0(%d), CC1(%d), CC2(%d), CC3(%d), CC4(%d), CC5(%d)
Line 3146: [SYSTEM] HALSYST_4G_CheckCcGroupingInfo : CC6(%d), CC7(%d), CC8(%d), CC9(%d)
Line 3172: [RXF] SetTrxOverrideMode(%d):(0x%08x)
Line 3229: [RXF] HALSYST_4G_SetTrxModeToDl(%d): rf(%d), TRX_CFG_ON(0x%08x), TRX_CFG_OFF(0x%08x)
Line 3275: [SYSTEM] PATH_ENABLE_4G : mxr_sel(%d), rtg(%d), This seems to be a 4RX path index, path enabled is not needed
Line 3338: [SYSTEM] PATH_ENABLE_4G : mxr_sel(%d), BB_RTG(%d), RFD_RTG(%d), PATH_CC_SEL(%d, %d), MPLL_CFG(0x%x), enable(%d)
Line 3345: [SYSTEM] PATH_ENABLE_4G : BB path_enable(4G: %x, 5G: %x), RFD path_enable(4G: %x, 5G: %x) 
Line 3670: [SYSTEM] SetRtgLoad [WR](RTG%d, RFD_RTG%d): RTG(%x %x) diff(%d) rfd_path_enable(%x %x)
Line 3518: [RACH] HALSYST_4G_RestoreTrxSwitchAfterSaDrds
Line 449: [SYSTEM] SetPathRxDelay[WARNING] : Path Rx Delay update fail, abnormal cc index(%d)
