Line 190: ###[TSIC][PHY] UpdateTsicCfgInfo:: type(%d) TsicOption(%d) IsTxfConfigured(%d,%d)
Line 216: ###[TSIC][PHY] TXF:: SmallRbSize(%d) PwrThreshold(%d) DmrsSymCtrlFlag(%d)
Line 223: ###[TSIC][PHY] CMN:: StackId(%d) CellGroup(%d)
Line 226: ###[TSIC][PHY] CONFIG:: aggr0Rat(%d) aggr1Rat(%d) victimRat(%d) aggrChBw0(%d) aggrChBw1(%d) victimChBw(%d) aggr0FreqkHz(%d) aggr1FreqkHz(%d) victimFreqkHz(%d)
Line 228: ###[TSIC][PHY] CONFIG:: intfType(%d) CoarseRange(%d) CorrSize(%d) TcOption(0x%x) IsSyncRxmemDumpOn(%d) IsSyncKernelmemDumpOn(%d) IsSyncCorrmemDumpOn(%d)  syncPos(%d) relDelay(%d) TsicOption(%d)
Line 230: ###[TSIC][PHY] CONFIG:: icOnThr(%d) icOffThr(%d) icOnThrSinr(%d) icOffThrSinr(%d) rlsOnThrRsrp(%d) rlsOffThrRsrp(%d) rlsOnThrSinr(%d) rlsOffThrSinr(%d) SyncThr(%d)
Line 233: ###[TSIC][PHY] KER:: KER_GEN_VSM_THR(%d) KER_GEN_RLS_MUX_SEL(%d) KER_GEN_MAIN_DELAY_VAL(%d) || SYNC:: SYNC_CORR_KERNEL_SIZE(%d) SYNC_RX_PATH_SEL(%d)
Line 236: ###[TSIC][PHY] RLS:: RXx_RLS_IC_OUT_MUX(0x%x) RX0_RLS_WEIGHTx_INIT(0x%x) RX0_RLS_FORGET_VAL(%d) RX0_RLS_RESIDUAL_BITSEL(%d) RX0_RLS_REGEN_BITSEL(%d) RX0_RLS_RMAT_BITSEL(%d) RX0_RLS_STEP_SIZE_VAL(%d)
Line 238: ###[TSIC][PHY] RLS:: RX0_RLS_REGULAR_RESI_VAL(%d) RX0_RLS_XDC(%d) RLS_RMAT_READ_SEL(%d) RLS_PHASE_EN(%d) RLS_PHASE_LEN(0x%x)
Line 240: ###[TSIC][PHY] RLS:: RX0_RLS_VSM_MODE(%d) RX_RLS_2SFF_ENABLE(0x%x) RX0_RLS_2SFF_FORGET_MAX_CNT(0x%x) RX0_RLS_2SFF_FORGET_VAL(0x%x) RX0_RLS_2SFF_REGULAR_RESI_VAL(0x%x)
Line 371: ###[TSIC][PHY] UpdateTsicReleaseInfo:: type(%d) TsicOption(%d) IsTxfConfigured(%d,%d)
Line 434: ###[TSIC][PHY] SetNrTxfCfg:: cc_idx(%d) NrTxTsicCfg_t(0x%x)
Line 465: ###[TSIC][RSLT] CheckTsicConfigured:: [2TX] m_IsTxfConfigured(%d,%d) intfType(%d)
Line 475: ###[TSIC][RSLT] CheckTsicConfigured:: [1TX] m_IsTxfConfigured(%d) intfType(%d)
Line 516: ###[TSIC][RSLT] ConfigTxFilter:: [REQ_RESULT] aggr0Rat(%d) aggr1Rat(%d) PendingTxfCfg[0](%d) PendingTxfCfg[1](%d)
Line 536: ###[TSIC][RSLT] ConfigNrTxf:: [WARNING] aggr_idx(%d) is already configured!!!
Line 554: ###[TSIC][RSLT] ConfigNrTxf:: demod_cc_idx(%d) status_reg(0x%x) TsicNrTxfFlag(%d) SmallRbSize(%d) PwrThreshold(%d) TxfNum(%d) DmrsSymCtrlFlag(%d)
Line 571: ###[TSIC][RSLT] ConfigLteTxf:: [WARNING] aggr_idx(%d) is already configured!!!
Line 591: ###[TSIC][RSLT] ConfigLteTxf:: demod_cc_idx(%d) status_reg(0x%x) TsicLteTxfFlag(%d) SmallRbSize(%d) PwrThreshold(%d) TxfNum(%d)
Line 644: ###[TSIC][RSLT] ReleaseNrTxf:: [WARNING] aggr_idx(%d) is already released!!!
Line 655: ###[TSIC][RSLT] ReleaseNrTxf:: aggr_idx(%d) demod_cc_idx(%d) status_reg(0x%x) TsicNrTxfFlag(%d) VictimEn(%d)
Line 677: ###[TSIC][RSLT] ReleaseLteTxf:: [WARNING] aggr_idx(%d) is already released!!!
Line 687: ###[TSIC][RSLT] ReleaseLteTxf:: aggr_idx(%d) demod_cc_idx(%d) status_reg(0x%x) TsicLteTxfFlag(%d) VictimEn(%d)
Line 708: ###[TSIC][RSLT] TxfCallback:: [CONFIG] aggr_idx(%d) m_IsTxfConfigured(%d,%d)
Line 715: ###[TSIC][RSLT] TxfCallback:: [RELEASE] aggr_idx(%d) m_IsTxfConfigured(%d,%d)
Line 718: ###[TSIC][RSLT] TxfCallback:: [RELEASE_DONE] m_TsicStatus(%d)
Line 741: ###[TSIC] Operate:: rat(%d) demod_cc_idx(%d) sync_status(%d)
Line 790: ###[TSIC][RSLT] ResetOpMode:: m_TsicOpMode(%d) m_TsicOpFlag(0x%x) m_TsicSyncStatus(%d)
Line 808: ###[TSIC][MODE] m_TsicOpFlag(0b%03d:RLS|IC|SYNC), icOnThr(%d), icOffThr(%d), icOnThrSinr(%d), icOffThrSinr(%d), rlsOnThrRsrp(%d), rlsOffThrRsrp(%d), rlsOnThrSinr(%d), rlsOffThrSinr(%d)
Line 810: ###[TSIC][RSLT] [MODE_OPERATION] m_TsicOpMode(%d)[0:NONE 1:MANUAL 2:INIT 3:SYNC 4:RLS_TR 5:TSIC_OFF 6:IC 7:EX]
Line 881: ###[TSIC][RSLT] ProcTsicOpMode:: [Warning] m_TsicOpMode(%d)
Line 914: ###[TSIC][INFO] Victim SINR(dB) :: Rx0~3(%d, %d, %d, %d), Victim RSRP(dBm) :: Rx0~3(%d, %d, %d, %d), Aggr TxPower(dBm) :: UL0~1(%d, %d)
Line 1006: ###[TSIC][MON] CheckTsicOpFlag:: rx0_pm_pre_value(%d) rx0_pm_post_value(%d) rx1_pm_pre_value(%d) rx1_pm_post_value(%d) rx2_pm_pre_value(%d) rx2_pm_post_value(%d) rx3_pm_pre_value(%d) rx3_pm_post_value(%d)
Line 1058: ###[TSIC][RSLT] CheckTsicOpMode:: [UNDEFINED] m_TsicOpMode(%d)
Line 1089: ###[TSIC][MODE] CheckInitialMode:: sync_mode_flag(0x4:0x%x), rls_tracking_mode_flag(0x5:0x%x) tsic_off_mode_flag(0x0:0x%x)
Line 1117: ###[TSIC][MODE] CheckSyncMode:: sync_mode_flag(0x4:0x%x), rls_tracking_mode_flag(0x5:0x%x)
Line 1150: ###[TSIC][MODE] CheckRlsTrackingMode:: sync_mode_flag(0x4:0x%x), rls_tracking_mode_flag(0x5:0x%x) tsic_off_mode_flag(0x0:0x%x) ic_mode_flag(0x7:0x%x)
Line 1178: ###[TSIC][MODE] CheckTsicOffMode:: sync_mode_flag(0x4:0x%x), rls_tracking_mode_flag(0x5:0x%x) tsic_off_mode_flag(0x0:0x%x)
Line 1211: ###[TSIC][MODE] CheckIcMode:: sync_mode_flag(0x4:0x%x), rls_tracking_mode_flag(0x5:0x%x) tsic_off_mode_flag(0x0:0x%x) ic_mode_flag(0x7:0x%x)
Line 1245: ###[TSIC][RSLT] ProcSyncStart:: [2TX CONFIG] intfType(%d)
Line 1249: ###[TSIC][RSLT] Proc2TxConfig:: Error m_DelayStart(%d), This case was skipped.
Line 1262: ###[TSIC][RSLT] Proc2TxConfig:: Cannot find feasible relative delay.
Line 1268: ###[TSIC][RSLT] ProcSyncStart:: [1TX CONFIG] intfType(%d)
Line 1288: ###[TSIC] ProcSyncDone:: SYNC ISR after Release!!
Line 1342: ###[TSIC][1TX] Proc1TxConfig:: [TSIC_SYNC_TIMEOUT]
Line 1351: ###[TSIC][RSLT] Proc1TxConfig:: [SYNC RETRY] m_MaxMetric(%d) < SyncThr(%d) / m_BestPeakPos(%d)
Line 1363: ###[TSIC][RSLT] Proc1TxConfig::	[1TX CONFIG DONE] intfType(%d) m_MaxMetric(%d) SyncThr(%d) m_BestPeakPos(%d)
Line 1382: ###[TSIC][2TX] Proc2TxConfig:: [TSIC_SYNC_TIMEOUT] Retry m_CoarseCnt(%d) m_FineCnt(%d)
Line 1400: ###[TSIC][2TX] Proc2TxConfig:: New MaxMetric, m_MaxMetric(%d) m_BestCoarseDelay(%d) m_BestPeakPos(%d)
Line 1406: ###[TSIC][2TX] Proc2TxConfig:: New MaxMetric, m_MaxMetric(%d) m_BestFineDelay(%d) m_BestPeakPos(%d)
Line 1419: ###[TSIC][RSLT] Proc2TxConfig:: [SYNC RETRY] m_MaxMetric(%d) < SyncThr(%d) / m_BestFineDelay(%d) m_BestPeakPos(%d)
Line 1430: ###[TSIC][RSLT] Proc2TxConfig:: [2TX CONFIG DONE] intfType(%d) m_MaxMetric(%d) SyncThr(%d) m_BestFineDelay(%d) m_BestPeakPos(%d)
Line 1439: ###[TSIC][2TX] Proc2TxConfig:: m_CoarseCnt(%d) m_FineCnt(%d) CoarseRange(%d)
Line 1482: ###[TSIC][2TX] Init2TxParam:: m_UpSplLvl(%d, %d) frac_delay_min(%d) m_DelayPathIdx(%d, %d) m_DelayStart(%d) CoarseRange(%d)
Line 1502: ###[TSIC][2TX] Proc2TxConfig:: Coarse search finished. m_MaxMetric(%d) m_BestCoarseDelay(%d) m_BestPeakPos(%d)
Line 1554: ###[TSIC][2TX] ConfigCoarseSearch:: this candidate is not feasible. ul_pre_timing_offset(%d, %d) ul_post_timing_offset(%d, %d)
Line 1566: ###[TSIC][2TX] ConfigCoarseSearch:: curr_frac_delay(%d) pre0(%d) post0(%d) pre1(%d) post1(%d)
Line 1608: ###[TSIC][2TX] ConfigCoarseSearch:: this candidate is not feasible. ul_pre_timing_offset(%d, %d) ul_post_timing_offset(%d, %d)
Line 1620: ###[TSIC][2TX] ConfigFineSearch:: pre0(%d) post0(%d) pre1(%d) post1(%d)
Line 1656: ###[TSIC][RSLT] [2TX RESULT] UL0:%d/%d / UL1:%d/%d	(PRE/POST TIMING OFFSET)
Line 1657: ###[TSIC][RSLT] [2TX RESULT] peak sync corr position = %d, max metric = %d
Line 1695: ###[TSIC][TC] ProcTimeCorr:: (SWEEP) SYNC_RX_PATH_SEL(%d) RxSweepIdx(%d)
Line 1723: ###[TSIC][TC] InitSyncParam::
Line 1746: ###[TSIC][TC] InitTimeCorrParam:: ALL_TC_PARAMs(0), etc:: m_FreqOffsetBtwTxIntfAndRx(%d) m_RxSweepIdx(%d)
Line 1774: ###[TSIC][SYNC] MonitorTc:: <TC> RX_path(%d) CUR_CORR_I/Q ( %d / %d ) PREV_CORR_I/Q ( %d / %d )
Line 1793: ###[TSIC][TC] CalcTimeCorr:: First setting. PREV_CORR_I/Q ( %d / %d ) CUR_CORR_I/Q ( %d / %d )
Line 1806: ###[TSIC][TC] CalcTimeCorr:: ERROR case. 1 == m_TimeCorrOverflow(%d), m_SampleDiff(%d) > wait_sample_thres(%d)
Line 1992: ###[TSIC][KER] CalcKerGenMixerFreqOffset:: intf_dmixer_val(0x%x) intf_freq_ofs(%d) aggr0_freq_ofs(%d) aggr1_freq_ofs(%d) intf_spl_rate(0x%x)
Line 2064: ###[TSIC][KER] CalcFreqOffsetBtwTxIntfAndRx:: freq_ofs_tx_intf_rx(%d) aggr0_freq(%d) aggr1_freq(%d) victim_freq(%d)
Line 2100: ###[TSIC][KER] GetUpSplLvl:: aggr_idx(%d) aggr_spl_rate(%d) aggr_intf_bw(%d) victim_spl_rate(%d) aggr_intf_sum(%d) ratio(%d) up_spl_rate(%d)
Line 2108: ###[TSIC][RSLT] SetTsicSyncOpStatus:: m_TsicSyncStatus(%d)
Line 2174: ###[TSIC][DEBUG] UpdateKernelSize:: victim_spl_rate_idx(%d) aggr0Rat(%d), aggr0_scs(%d kHz) aggr0Rat(%d), aggr1_scs(%d kHz)
Line 2275: ###[TSIC] GetNrShmIdx:: Wrong NR stack_id(%d) or cellGroup(%d)
Line 2298: ELA_DEBUG, SetLoggerEn:: m_LoggerEn(%d)
Line 2455: ###[TSIC][SYNC] FindMedian:: Iterated %d times. IntfType(%d) RxPath(%d) Sync Position(%d), Relative Delay(%d) Hit Ratio[(%d/%d), (%d/%d)] MaxMetric(%d)
Line 2461: ###[TSIC][DEBUG] FindMedian:: SyncPos[val(%d), cnt(%d)]
Line 2467: ###[TSIC][DEBUG] FindMedian:: RelDelay[val(%d), cnt(%d)]
Line 2499: ###[TSIC][RSLT] FindMedian:: IntfType(%d) BestRxPath(%d) Sync Position(%d), Relative Delay(%d)
Line 2505: ###[TSIC][RSLT] FindMedian:: Couldn't find valid delay, Hit Ratio[(%d/%d), (%d/%d)] Threshold[%d%%, %d%%]
