Line 85: ##[NR_CHANNEL] SEND_MSG(BCH_CONFIG_CNF): res(%d)
Line 110: ##[NR_CHANNEL] SEND_MSG(BCH_RELEASE_CNF): res(%d)
Line 123: ##[NR_CHANNEL] SEND_MSG(L2_BWP_CHANGE_CNF): res(%d), ctrlr_state(%d), on_going_proc(0x%x)
Line 130: ##[NR_CHANNEL] SEND_MSG(L2_BWP_CHANGE_DONE_IND): demod_cc(%d), scell_idx(%d), ul_bwp_id(%d), dl_bwp_id(%d)
Line 149: ##[NR_CHANNEL] SEND_MSG(L2_DORMANT_BWP_CHANGE_DONE_IND): dormant_bwp_change_flag(%d), num_of_scell_idx(%d)
Line 196: ##[NR_CHANNEL] SEND_MSG(PBCH_DECODE_CNF): sfn(%d), lteRtgCounter(0x%x) frameBoundaryOffset(%d) SsbTimingOffset(%d)
Line 232: ##[NR_CHANNEL] SEND_MSG(PBCH_DECODE_CNF): frameBoundaryOffset(%d) SsbTimingOffset(%d) 
Line 243: ##[NR_CHANNEL] SEND_MSG(PBCH_DECODE_CNF/Failure): srcRat %d
Line 290: ##[NR_CHANNEL] SEND_MSG(NCELL_PBCH_DECODE_CNF): frameBoundaryOffset(%d) SsbTimingOffset[0](%d) SsbTimingOffset[63](%d) lteRtgCounter(0x%x)
Line 305: ##[NR_CHANNEL] SEND_MSG(PHY_CHANGE_INFO_CNF): res(%d), on_going_proc(0x%x)
Line 319: ##[NR_CHANNEL] SEND_MSG(PHY_CONFIG_CNF): result(%d), ctrlr_state(%d), on_going_proc(0x%x), report_rf_ul_dc(%d), GapInfoRequired(%d)
Line 368: ##[NR_CHANNEL][ULCA] No need to check Pcell TX swap is need. (scell_ul_band: %d)
Line 377: ##[NR_CHANNEL][ULCA] No need to check Pcell TX swap is need. (pcell_ul_band: %d)
Line 410: [NR_CHANNEL] SEND_MSG(RESTRICTION_CONFIG_CNF): Rat(%d) Level(%d) Result(%d)
Line 420: [NR_CHANNEL] SEND_MSG(RESTIRCTION_RELEASE_CNF): Rat(%d) Level(%d) Result(%d)
Line 443: ##[NR_CHANNEL] SEND_MSG(SERVING_CELL_CHANGE_CNF): ctrlr_state(%d), result(%d), on_going_proc(0x%x)
Line 464: ##{NR_CHANNEL] SEND_MSG(SERVING_CELL_CHANGE_CNF/FAIL): ctrlr_state(%d), on_going_proc(0x%x)
Line 471: ##{NR_CHANNEL] SEND_MSG(SERVING_CELL_CHANGE_CNF/CELL_TIME_CHANGE): ctrlr_state(%d), on_going_proc(0x%x)
Line 525: ##[NR_CHANNEL] SIB1:: TableIdx is not found in FR1
Line 541: ##[NR_CHANNEL] SIB1:: TableIdx is not found in FR2
Line 549: ##[NR_CHANNEL] SIB1:: SsbStartFreq(%d), Sib1StartFreq(%d), Sib1Center(%d, %d), Sib1_Bw4/Scs4(0x%x), Sib1_NumRb(%d)
Line 588: ##[NR_CHANNEL] ServCell Info Update -ARFCN(%d) CELLID(%d) SSBIDX(%d) TimingOffsetForIndex(0) (%d)
Line 599: ##[NR_CHANNEL] SEND_MSG(SERVING_CELL_RELEASE_CNF): ctrlr_state(%d)
Line 606: ##[NR_CHANNEL] SEND_MSG(BPLMN_RECOVERY_DONE_IND): ctrlr_state(%d)
Line 613: ##[NR_CHANNEL] SEND_MSG(BPLMN_RECOVERY_START_IND): ctrlr_state(%d)
Line 630: ##[NR_CHANNEL] SEND_MSG(CDRX_CONFIG_IND): DrxConfig.Choice(%d), scell_idx(%d), fr(%d), num_of_scell(%d), bwp_scs(%d)
Line 638: ##[NR_CHANNEL] SEND_MSG(CELL_TIME_RESTORE_REQ): rx_path(%d)
Line 645: ##[NR_CHANNEL] SEND_MSG(PCH_CONFIG_IND): scell_idx(%d), on_going_proc(0x%x), bitmap(0x%x%08x))
Line 657: ##[NR_CHANNEL] SEND_MSG(PCH_CONFIG_IND): scell_idx(%d), on_going_proc(0x%x), bwp_scs(%d), bitmap(0x%x%08x))
Line 670: ##[NR_CHANNEL] SEND_MSG(PHY_CHANGE_INFO_REQ): ctrlr_state(%d), new_ul_rank(%d)
Line 678: ##[NR_CHANNEL] SEND_MSG(BCH_CONFIG_IND): ctrlr_state(%d)
Line 687: ##[NR_CHANNEL] SEND_MSG(DRX_RESTORE_CNF): result(%d), type(%d), ctrlr_state(%d)
Line 701: ##[NR_CHANNEL] SEND_MSG(DRX_LPM_INFO_REQ): Cause(%d)
Line 710: ##[NR_CHANNEL] SEND_MSG(ALL_STOP_CNF): ctrlr_state(%d)
Line 719: ##[NR_CHANNEL] SEND_MSG(RELEASE_ALL_CNF): ctrlr_state(%d)
Line 730: ##[NR_CHANNEL] SEND_MSG(BEAM_LOCK_IND): Beamlock_Info(%d)
Line 749: ##[NR_CHANNEL] SEND_MSG(SERVING_INFO_UPDATE_IND): freq(%d), arfcn(%d), band(%d), ssb_idx8/ssb_scs8(0x%x), period(%d), pattern(%d), cell_id(%d))
Line 760: ##[NR_CHANNEL][Error:%s] can not find the arfcn(%d)
Line 777: ##[NR_CHANNEL] SEND_MSG(SERVING_INFO_UPDATE_IND): freq(%d), ssb_idx8/ssb_scs8(0x%x), period(%d), pattern(%d), cell_id(%d), hfi(%d), sfn(%d))
Line 798: ##[NR_CHANNEL] SEND_MSG(MEAS_STOP_REQ): meas_stop_id(%d), cause(%d))
Line 811: ##[NR_CHANNEL] SEND_MSG(MEAS_CONFIG_IND)
Line 828: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ): req_type[SERV/SRCH/MEAS/PBCH/MODI](0x%x) num_of_req_cell(%d), num_of_rel_cell(%d), CfgPurpose(%d)
Line 847: ##[NR_CHANNEL] Invalid num_of_req/rel_cell (%d, %d)
Line 888: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/CFG): [%d] serv_cell_info(0x%4x-scell_idx8/scell_buf4), dl_freq_info(%d %d %d), req_bw(0x%4x, dl8ch8), dl_scs4/layer4(0x%x), channel_freq(%d)
Line 894: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/CFG) Param:: [%d] ul_freq_info(%d %d %d), ul_bw(%d) agc_gain(%d %d) dmrs_config(%d)
Line 897: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/CFG) Param:: [%d] l2n_srchmeas(%d), frame_boundary_offset(%d), ssb_scs(%d), ssb_freq(%d)
Line 903: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/REL) Param:: [%d] cell_info_idx(%d)
Line 917: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/REL): type(%d) num_of_rel_cell(%d) RelPurpose(%d)
Line 931: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/REL) Param:: [%d] cell_info_idx(%d)
Line 938: ##[NR_CHANNEL] num_of_cfg_cell in L1C_BCH is 0
Line 973: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/REL): CfgPurpose(%d), path_idr(PATH_DIR_TX), (arfcn/freq/band)(%d/%d/%d), max_mimo_layer_nw/max_mimo_layer_ue(%d/%d)
Line 996: ##[NR_CHANNEL] SEND_MSG(DRX_SCELL_STATUS_UPDATE_IND): num_of_config_scell(%d), num_of_act_scell(%d), fr(%d)
Line 1006: [NR_CHANNEL] SEND_MSG(SCELL_STATUS_IND/L2): Rat(%d), NumRedCc(%d)
Line 1011: [NR_CHANNEL] NumActivatedSCell < NumRedCc, Rat(%d), NumRedCc(%d)
Line 1020: [NR_CHANNEL] SEND_MSG(NS_RESTRICTION_START_CNF): Result(%d)
Line 1028: [NR_CHANNEL] SEND_MSG(NS_RESTRICTION_STOP_CNF): Result(%d)
Line 1044: ##[NR_CHANNEL] SEND_MSG(DRX_TX_CAPA_UPD_IND): max_ul_layer(%d), freq_range(%d)
Line 1054: ##[NR_CHANNEL] Send Send_L1C_L1C_DRXCTRLR_TX_ONOFF_REQ: TxOnType - TX_ON_INIT_RACH
Line 1060: ##[NR_CHANNEL] SEND_MSG(DRX_TX_ONOFF_REQ): scell_idx(%d), bwp_idx(%d) with INIT_RACH
Line 1068: ##[NR_CHANNEL] SEND_MSG(L2_TX_PAUSE_REQ): ctrlr_state(%d), on_going_proc(0x%x), type(%d)
Line 1077: ##[NR_CHANNEL] SEND_MSG(L2_TX_RESUME_REQ): ctrlr_state(%d), on_going_proc(0x%x), type(%d)
Line 1087: ##[NR_CHANNEL] SEND_MSG(SCG_RESUME_CNF)
Line 1097: ##[NR_CHANNEL] SEND_MSG(SCG_SUSPEND_CNF)
Line 1174: ##[NR_CHANNEL] CreateTxDcScList:: pTxDcList[%d] (%d %d %d %d %d %d)
Line 1180: ##[NR_CHANNEL] CreateTxDcScList:: rf_ul_freq(%d) NumOfUplinkTxDirectCurrentCell(%d)
Line 1207: [NR_CHANNEL] CreateIntraGapInfoRequiredList::NR_GAPIND_GAP - ssb_freq(%d), ssb_scs(%d), bwp_idx(%d), bwp_center_freq(%d), bwp_bw(%d)
Line 1216: [NR_CHANNEL] CreateIntraGapInfoRequiredList:: numCell(%d)
Line 1229: [GAP_INFO] CreateInterGapInfoRequiredList:: iCell(%d) scell_idx(%d)
Line 1235: [GAP_INFO] CreateInterGapInfoRequiredList:: iBand(%d) band(%d)
Line 1243: [GAP_INFO] CreateInterGapInfoRequiredList:: iBand(%d) band(%d)
Line 1287: [GAP_INFO] CreateInterGapInfoRequiredList:: bandListIndex(%d) band(%d) rat(%d) is_4Rx_Path(%d)
Line 1300: [GAP_INFO] CreateInterGapInfoRequiredList:: targetBandInfo.band(%d) targetBandInfo.rat(%d) targetBandInfo.is_4Rx_path(%d)
Line 1304: [NR_CHANNEL] CreateInterGapInfoRequiredList:: iBand(%d) targetBand(%d), GapIndicator(%d)
Line 1327: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/AddModScell): total_num_cell(%d), num_of_add_scell(%d), num_of_rel_scell(%d)
Line 1336: ##[NR_CHANNEL] Invalid num of total(%d)/config(%d)/release(%d) scell
Line 1348: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/AddModScell): path_rel_array[%d] = %d 
Line 1361: ##[NR_CHANNEL][ULCA] ProcessScellRelAndDeact: No need to check Pcell TX swap is need. (scell_ul_band: %d)
Line 1381: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/AddModScell): Wrong serv_cell_info_idx! [%d]
Line 1438: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/AddModScell): cfg_param[%d] dl_info(%d, %d, %d), ul_info(%d, %d), req_scell_idx(0x%4x->layer4/scell8/buf4)
Line 1450: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/AddModScell): None of SCELL Sys Param is changed.
Line 1491: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/AddModScellRecovery): ScellBitMask(0x%x), num_of_ca_scell(%d)
Line 1498: ##[NR_CHANNEL][RECOV] Invalid total_num_of_scell(%d)
Line 1509: ##[NR_CHANNEL][RECOV] recov_scell_idx(%d) is not found
Line 1523: ##[NR_CHANNEL][RECOV] target recpvered scell idx(%d) is not found
Line 1578: ##[NR_CHANNEL] SEND_MSG(PATH_CONFIG_REQ/AddModScellRecovery): cfg_param[%d] dl_info(%d, %d, %d), ul_info(%d, %d), req_scell_idx(0x%4x->layer4/scell8/buf4)
Line 1582: ##[NR_CHANNEL][RECOV] Recovered Num Cell Error (DB=%d, Calc=%d)
Line 1589: ##[NR_CHANNEL][RECOV] ServCell CA Recovery with ABNL param
Line 1596: [NR_CHANNEL] CreatePathCfgReqForScellActRecovery: num_of_act_deact_scell(%d)
Line 1607: ##[NR_CHANNEL] CreatePathCfgReqForScellActRecovery: scell_index(%d) is not found in serv_cell_info
Line 1667: ##[NR_CHANNEL] CreatePathCfgReqForScellActRecovery: Act Scell List [%d] DL{freq(%d), band(%d), dl_bw(%d)}, UL{freq(%d), ul_bw(%d)}, req_scell_idx4/dl_layer4(0x%x)
Line 1672: ##[NR_CHANNEL] CreatePathCfgReqForActDeactScell:: num_of_act_scell(%d), num_of_deact_scell(%d)
Line 1678: ##[NR_CHANNEL][RECOV] CompleteServCellRecovery(%d)
Line 1712: ##[NR_CHANNEL][NR_TX] UpdatePathCfgReqTxInfo: scell_idx(%d) spcell_idx(%d)
Line 1774: ##[NR_CHANNEL][NR_TX] UpdatePathCfgReqTxInfo: path_dir(%d-0:PATH_DIR_RX 1:PATH_DIR_TX, 2:PATH_DIR_RX_TX), cell_info_idx(%d), act_bwp_idx(%d), max_mimo_layer_nw/max_mimo_layer_ue(0x%x), ul_bw(prev:%d/cur:%d), is_rank_update_only/IsUlRankChangByMra(0x%x)
