Line 189: (F)Fail DCI det, CCH_DM_TRANSFER_MODE (%x, MCG_EPDCCH_CC_BITMAP (%x, SCC_STATE:0x%08x, SCC_PARAM_FAIL:0x%08x, SCH_OBUF_CHK:0x%08x, TURBO_STATUS:0x%08x, SCH_OBUF_MODE_SETTING:0x%08x, SCH_OBUF_INT_MODE_SETTING_4G:0x%08x, EHARQ_CTRL_STATE:0x%08x, HARQ_EXT_BUS_ERR:0x%08x
Line 203: (F)Fail DCI det, CCH_DM_TRANSFER_MODE (%x, MCG_EPDCCH_CC_BITMAP (%x, SCC_STATE:0x%08x, SCC_PARAM_FAIL:0x%08x, SCH_OBUF_CHK:0x%08x, TURBO_STATUS:0x%08x, SCH_OBUF_MODE_SETTING:0x%08x, SCH_OBUF_INT_MODE_SETTING_4G:0x%08x, EHARQ_CTRL_STATE:0x%08x, HARQ_EXT_BUS_ERR:0x%08x
Line 270: Core(%d) gCTLCH_MON_CCH_FAIL_COUNT(%d)
Line 296: Core(%d) pdcch_count has a problem!red_ctlch_mon_prev(0x%x) red_ctlch_mon(0x%x)
