Line 846: L1CfgMonitorRSSI sniff startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 881: L1CfgMonitorRSSI no sniff startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 978: L1CfgMonitorRSSI_RFCAL startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 1066: L1CfgMonitorRSSI_Irat startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 1337: L1CfgStartFbAcquire sniff startOffset [%d] startdsp [%d]
Line 1360: L1CfgStartFbAcquire no sniff startOffset [%d] startdsp [%d]
Line 1415: ###L1CfgStartIRATFbAcquire endoffset Org[%d] Modified[%d]
Line 1430: L1CfgStartFbAcquire no sniff startOffset [%d] startdsp [%d]
Line 1700: L1CfgSbAcquire no sniff startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 1799: L1CfgPtmSbAcquire startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 1911: L1CfgSbAcquire sniff startOffset [%d] startdsp [%d] stopdsp [%d] 
Line 1936: L1CfgSbAcquire no sniff startOffset [%d] startdsp [%d] stopdsp [%d] 
