Line 113: [SIT_1_NET] [5GPM_SA][Metrics] SA DISABLE Period %d
Line 113: [SIT_0_NET] [5GPM_SA][Metrics] SA DISABLE Period %d
Line 164: [SIT_1_NET] [5GPM_SA][Metrics] No memory allocated
Line 164: [SIT_0_NET] [5GPM_SA][Metrics] No memory allocated
Line 173: [SIT_1_NET] [5GPM_SA][Metrics] Report metrics_id %d, value %d
Line 173: [SIT_0_NET] [5GPM_SA][Metrics] Report metrics_id %d, value %d
Line 203: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_TOTAL_COUNT : 1
Line 203: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_TOTAL_COUNT : 1
Line 209: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_TOTAL_COUNT : 1
Line 209: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_TOTAL_COUNT : 1
Line 231: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_NO_COUNT : 1
Line 231: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_NO_COUNT : 1
Line 234: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_NO_COUNT : 1
Line 234: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_NO_COUNT : 1
Line 266: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_RRC_DRATION : %d
Line 266: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_RRC_DRATION : %d
Line 271: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_RRC_DURATION : %d
Line 271: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_RRC_DURATION : %d
Line 302: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_MODE_UPDATE_DURATION : %d
Line 302: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_MODE_UPDATE_DURATION : %d
Line 307: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_MODE_UPDATE_DURATION : %d
Line 307: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_MODE_UPDATE_DURATION : %d
Line 338: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_NOSIB24_DURATION : %d
Line 338: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_NOSIB24_DURATION : %d
Line 369: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_ACTIVE_CALL_DURATION : %d
Line 369: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_ACTIVE_CALL_DURATION : %d
Line 374: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_ACTIVE_CALL_DURATION : %d
Line 374: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_ACTIVE_CALL_DURATION : %d
Line 405: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_E911_DURATION : %d
Line 405: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_E911_DURATION : %d
Line 410: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_E911_DURATION : %d
Line 410: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_E911_DURATION : %d
Line 418: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_E911_10SEC_COUNT : 1
Line 418: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_E911_10SEC_COUNT : 1
Line 423: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_E911_30SEC_COUNT : 1
Line 423: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_E911_30SEC_COUNT : 1
Line 428: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_E911_60SEC_COUNT : 1
Line 428: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_E911_60SEC_COUNT : 1
Line 433: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_E911_90SEC_COUNT : 1
Line 433: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_E911_90SEC_COUNT : 1
Line 437: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_E911_150SEC_COUNT : 1
Line 437: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_E911_150SEC_COUNT : 1
Line 443: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_E911_10SEC_COUNT : 1
Line 443: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_E911_10SEC_COUNT : 1
Line 448: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_E911_30SEC_COUNT : 1
Line 448: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_E911_30SEC_COUNT : 1
Line 453: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_E911_60SEC_COUNT : 1
Line 453: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_E911_60SEC_COUNT : 1
Line 458: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_E911_90SEC_COUNT : 1
Line 458: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_E911_90SEC_COUNT : 1
Line 462: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_E911_150SEC_COUNT : 1
Line 462: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_E911_150SEC_COUNT : 1
Line 535: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_RRC_COUNT : 1
Line 535: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_RRC_COUNT : 1
Line 538: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_RRC_COUNT : 1
Line 538: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_RRC_COUNT : 1
Line 547: [SIT_1_NET] [5GPM_SA][Metrics] RRC acvite Start time %d
Line 547: [SIT_0_NET] [5GPM_SA][Metrics] RRC acvite Start time %d
Line 563: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_MODE_UPDATE_COUNT : 1
Line 563: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_MODE_UPDATE_COUNT : 1
Line 567: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_MODE_UPDATE_COUNT : 1
Line 567: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_MODE_UPDATE_COUNT : 1
Line 577: [SIT_1_NET] [5GPM_SA][Metrics] ModeUpdate Start time %d
Line 577: [SIT_0_NET] [5GPM_SA][Metrics] ModeUpdate Start time %d
Line 593: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_BLOCKED_NO_SIB24_AND_LTE_COUNT : 1
Line 593: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_BLOCKED_NO_SIB24_AND_LTE_COUNT : 1
Line 602: [SIT_1_NET] [5GPM_SA][Metrics] No SIB24 Start time %d
Line 602: [SIT_0_NET] [5GPM_SA][Metrics] No SIB24 Start time %d
Line 618: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_ACTIVE_CALL_COUNT : 1
Line 618: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_DELAY_ACTIVE_CALL_COUNT : 1
Line 622: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_ACTIVE_CALL_COUNT : 1
Line 622: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_DELAY_ACTIVE_CALL_COUNT : 1
Line 631: [SIT_1_NET] [5GPM_SA][Metrics] VoiceCall Start time %d
Line 631: [SIT_0_NET] [5GPM_SA][Metrics] VoiceCall Start time %d
Line 649: [SIT_1_NET] [5GPM_SA][Metrics] E911 Start time %d
Line 649: [SIT_0_NET] [5GPM_SA][Metrics] E911 Start time %d
Line 659: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_BLOCKED_SENT_AFTER_NEW_CELL_WITH_SIB24_COUNT : 1
Line 659: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_BLOCKED_SENT_AFTER_NEW_CELL_WITH_SIB24_COUNT : 1
Line 663: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_BLOCKED_NO_SIB24_THEN_RAT_TO_NR_COUNT : 1
Line 663: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_BLOCKED_NO_SIB24_THEN_RAT_TO_NR_COUNT : 1
Line 696: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_QRB_SKIP_TRIGGER_COUNT : 1
Line 696: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_QRB_SKIP_TRIGGER_COUNT : 1
Line 699: [SIT_1_NET] [5GPM_SA][Metrics] SA_ENABLE_QRB_TRIGGER_COUNT : 1
Line 699: [SIT_0_NET] [5GPM_SA][Metrics] SA_ENABLE_QRB_TRIGGER_COUNT : 1
Line 702: [SIT_1_NET] [5GPM_SA][Metrics] MRU_L2N_COUNT : 1
Line 702: [SIT_0_NET] [5GPM_SA][Metrics] MRU_L2N_COUNT : 1
Line 731: [SIT_1_NET] [5GPM_SA][Metrics] RRC state %d, lock mode %d
Line 731: [SIT_0_NET] [5GPM_SA][Metrics] RRC state %d, lock mode %d
Line 739: [SIT_1_NET] [5GPM_SA][Metrics] RRC active Start time %d
Line 739: [SIT_0_NET] [5GPM_SA][Metrics] RRC active Start time %d
Line 763: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_RRC_CONN_DURATION : %d
Line 763: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_RRC_CONN_DURATION : %d
Line 768: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_RRC_CONN_15SEC_COUNT : 1
Line 768: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_RRC_CONN_15SEC_COUNT : 1
Line 772: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_RRC_CONN_30SEC_COUNT : 1
Line 772: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_RRC_CONN_30SEC_COUNT : 1
Line 776: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_RRC_CONN_50SEC_COUNT : 1
Line 776: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_RRC_CONN_50SEC_COUNT : 1
Line 780: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_RRC_CONN_80SEC_COUNT : 1
Line 780: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_RRC_CONN_80SEC_COUNT : 1
Line 784: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_RRC_CONN_120SEC_COUNT : 1
Line 784: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_RRC_CONN_120SEC_COUNT : 1
Line 803: [SIT_1_NET] [5GPM_SA][Metrics] MRU_L2N_COUNT : 1
Line 803: [SIT_0_NET] [5GPM_SA][Metrics] MRU_L2N_COUNT : 1
Line 822: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_ENDC_ENABLE_DROPPING_COUNT : 1
Line 822: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_ENDC_ENABLE_DROPPING_COUNT : 1
Line 830: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_ENDC_DISABLE_DROPPING_COUNT : 1
Line 830: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_ENDC_DISABLE_DROPPING_COUNT : 1
Line 855: [SIT_1_NET] [5GPM_SA][Metrics] SA_DISABLE_ENDC_CONNECTION_DURING_SA_ENABLE_COUNT : 1
Line 855: [SIT_0_NET] [5GPM_SA][Metrics] SA_DISABLE_ENDC_CONNECTION_DURING_SA_ENABLE_COUNT : 1
Line 868: [SIT_1_NET] [5GPM_SA][Metrics] Timer Expiry for ID %d
Line 868: [SIT_0_NET] [5GPM_SA][Metrics] Timer Expiry for ID %d
Line 881: [SIT_1_NET] [5GPM_SA][Metrics] Unknown TimerId %d
Line 881: [SIT_0_NET] [5GPM_SA][Metrics] Unknown TimerId %d
