Line 49: [SIT_1_DEBUG] RX DM_STATE_IND is NULL
Line 49: [SIT_0_DEBUG] RX DM_STATE_IND is NULL
Line 55: [SIT_1_DEBUG] RX DM_STATE_IND (%d), send SIT_IND_SELFLOG_STATUS to AP
Line 55: [SIT_0_DEBUG] RX DM_STATE_IND (%d), send SIT_IND_SELFLOG_STATUS to AP
Line 67: [SIT_1_DEBUG] RX DM_MIMO_STATUS_REPORT is NULL
Line 67: [SIT_0_DEBUG] RX DM_MIMO_STATUS_REPORT is NULL
