Line 286: [SIT_1_SIM] sitTxStkOpenChannelReqInd: Incorrect Iptype(%d)
Line 286: [SIT_0_SIM] sitTxStkOpenChannelReqInd: Incorrect Iptype(%d)
Line 290: [SIT_1_SIM] sitTxStkOpenChannelReqInd:TransportType(%d),PortNum(%d),Iptype(%d),bufferSize(%d)
Line 290: [SIT_0_SIM] sitTxStkOpenChannelReqInd:TransportType(%d),PortNum(%d),Iptype(%d),bufferSize(%d)
Line 342: [SIT_1_SIM] sitTxSendWifiDataInd:datalen exceed 1500.Truncate to max len(%d)
Line 342: [SIT_0_SIM] sitTxSendWifiDataInd:datalen exceed 1500.Truncate to max len(%d)
Line 349: [SIT_1_SIM] sitTxSendWifiDataInd:datalen(%d),CID(%d)
Line 349: [SIT_0_SIM] sitTxSendWifiDataInd:datalen(%d),CID(%d)
Line 372: [SIT_1_SIM] sitTxReceiveDataFromWifi:CID(%d)
Line 372: [SIT_0_SIM] sitTxReceiveDataFromWifi:CID(%d)
Line 394: [SIT_1_SAT] sitTxStkCloseChannelReq:CID(%d)
Line 394: [SIT_0_SAT] sitTxStkCloseChannelReq:CID(%d)
