Line 48: [OEM][SUPPORTED_BAND] Unexpected OEM_GRF_LTE_POR_BAND[%d] value[%d]
Line 59: [OEM][SUPPORTED_BAND] OEM_GRF_LTE_POR_BAND[%d] : %d
Line 73: [OEM][SUPPORTED_BAND] OEM_GRF_LTE_POR_BAND skip NTN bands
Line 95: [OEM][SUPPORTED_BAND] Unexpected OEM_GRF_FR1_POR_BAND[%d] value[%d]
Line 106: [OEM][SUPPORTED_BAND] OEM_GRF_FR1_POR_BAND[%d] : %d
Line 126: [OEM][SUPPORTED_BAND] OEM_GRF_FR2_POR_BAND[%d] : %d
Line 134: [OEM][SUPPORTED_BAND] Exception, OEM_GRF_FR2_POR_BAND[%d] : %d
