Line 67: [IRATFDB] Update Recevied for STACK (%d) from Rat (%d)
Line 68: [IRATFDB] IratFreqUpdate_t->UpdateProc(%d) 
Line 70: [IRATFDB] IratFreqUpdate_t->PlmnId(%d, %d, %d) 
Line 72: [IRATFDB]IratFreqUpdate_t->TargetRat 2G(%d), 3G(%d), 4G(%d) , 5G(%d) 
Line 96: [IRATFDB] Update STACK_1 RAT(%d) 
Line 101: [IRATFDB] IratFreqUpdate_t->Freq(%d) 
Line 167: [IRATFDB] StackCommon_RrcCmn_AddNewFreqIRATFreqDbForStack  Freq(%d) 
Line 198: [IRATFDB][Error]  Get freq for Rat(%d) invoked while update ongoing for same rat in PeerStack(%d)
Line 210: [IRATFDB] StackCommon_RrcCmn_GetIratFreqDb  Freq(%d) 
