Line 78: [Proc Rxmode] SetThreshold rxd_1rx_disable(%d) DL_Grant_TH(%d) SINR_1RX_H_L(%d %d) SINR_2RX_H_L(%d %d) RrcState(%d)
Line 153: [Proc Rxmode] CC:%d Operate: PHY_L1C_RXMODE_CHANGE_REQ Rxmode(0x%x) Pos_4rx(%d)
Line 158: [Proc Rxmode] CC:%d Operate: PHY_L1C_MIB_ACQ_REQ Pos_4rx(%d) rxmode_bitmap(%d) isAbove6GHz(%d)
Line 163: [Proc Rxmode] CC:%d Operate: PHY_L1C_DRX_WAKEUP_INIT_REQ Pos_4rx(%d) rxmode_bitmap(%d) isAbove6GHz(%d)
Line 168: [Proc Rxmode] CC:%d Operate: SysParam End rxmode_bitmap Mismatch!!! cur_rxmode(%d), Config_rxmode(%d)
Line 173: [Proc Rxmode] CC:%d Operate: PHY_L1C_SYS_PARAM_CHANGE_REQ Pos_4rx(%d) NTM_MODE(%d) rxmode_bitmap(%d)
Line 179: [Proc Rxmode] SysParam Cnf done MtmCheck(%d) sysparamCfg_eventInfo(%d) rxd_1rx_disable(%d) DL_Grant_TH(%d) SINR_1RX_H_L(%d %d) SINR_2RX_H_L(%d %d) ditimer_th(%d %d)
Line 184: [Proc Rxmode] CC:%d Operate: PHY_L1C_TMU_CTRL_IND controlOn(%d) RI(%d)
Line 189: [Proc Rxmode] CC:%d Operate: PHY_L1C_SCELL_ACTDEACT_REQ Pos_4rx(%d) rxmode_bitmap(%d) isAbove6GHz(%d) MtmCheck(%d)
Line 433: [Proc Rxmode][VoNR] CC:%d VoNrStatus(%d)
Line 439: [Proc Rxmode][Lpm] CC:%d NrLpmStatus(%d)
Line 466: [Proc Rxmode][SCELL] m_CcIdx(%d) Exception 1rx mode for Scell next_rxmode(%d)
Line 555: [Proc Rxmode][VoNR] CC(%d) next_rxmode(%d) num_layer(%d) highRankMarginTimer(%d) pdschBler(%d) Trs_flag(%d) valid_Sinr(%d) Dlgrant_Ratio(%d) Vonr_flag(%d)
Line 565: [Proc Rxmode][VoNR] CC(%d) current_rxmode(%d) num_layer(%d) highRankMarginTimer(%d) pdschBler(%d) Trs_flag(%d) valid_Sinr(%d) Dlgrant_Ratio(%d) Vonr_flag(%d)
Line 651: [Proc Rxmode][DA] CC(%d) next_rxmode(%d) num_layer(%d) DlBler(%d) blerCnt(%d) CQI/mcsTable/curMcs(2/1/2)(%d) SINR(%d) Dlgrant(%d) Cnt(%d)
Line 662: [Proc Rxmode][DA] CC(%d) current_rxmode(%d) num_layer(%d) DlBler(%d) blerCnt(%d) CQI/mcsTable/curMcs(2/1/2)(%d) SINR(%d) Dlgrant(%d) Cnt(%d)
Line 694: [Proc Rxmode][DI] CC(%d) next_rxmode(%x) num_layer(%d)
Line 745: [Proc Rxmode][DI] CC(%d) next_rxmode(%x) Dlgrant(%d) valid_trs/sinr(%d) Sinr_ssb(%d) Sinr_trs(%d) DLbler(%d) Timer:DI(%d), dataInact(%d), Cdrx(%d)
Line 790: [NR IPC][Proc Rxmode] L1C_PHY_RXMODE_CHANGE_IND, BM_SrcCcForCnfMsg(%d), ind_Rxpath(%d), dataInactivity_Flag(%d), ulInd(%d)
Line 820: [NR IPC][Proc Rxmode] L1C_PHY_RXMODE_CHANGE_CNF, BM_SrcCcForCnfMsg(%d), demod_cc(%d)
Line 840: [Proc Rxmode] Ignore REQ IPC curRxmode(%d) nextRxmode(%d)
Line 857: [Proc Rxmode] CC:%d Configure: Rx ant num(%d) (cc/div_cc/00/RxMode : 0x%08x)(rtg/rfd/rf/rf_div : 0x%08x)
Line 1130: [Proc Rxmode] NrRxmodeChangeTxCfg  indFlag(%d) RxMode(%d)
