Line 306: Classify_ScellList: groupType(%d)
Line 372: [PROC][CA][MCG] CaScellInfo: NumofScell(%d)/ScellIndex(%d,%d,%d,%d,%d,%d,%d,...)/CcIdxBitMap(0x%X)/UlCcIdxBitMap(0x%X)
Line 377: [PROC][CA][SCG] CaScellInfo: NumofScell(%d)/ScellIndex(%d,%d,%d,%d,%d,%d,%d,...)/CcIdxBitMap(0x%X)/UlCcIdxBitMap(0x%X)
Line 430: [PROC][CA] ERROR: NumofScell(%d)
Line 505: [PROC][CA][CC_%d] CaScellInfo: NumofScell(%d)/CcIdxBitMap(0x%X)/UlCcIdxBitMap(0x%X)/ScellIndex(%d)/MyArrayIndex(%d), PcellCc(%d), band(%d)
Line 513: [PROC][CA][CC_%d] CaScellInfo: NumofScell(%d)/ScellIndex(%d)/ArrayIndex(%d)/CcIdxBitMap(0x%X)/UlCcIdxBitMap(0x%X)/PcellCc(%d), band(%d)
Line 528: (I)Skip DB update: m_CcIdx(%d) MyScellIndex(%d)
Line 534: (I)Skip DB update: MyScellIndex(%d) MyArrayIndex(%d)
Line 562: [CellGroup DM] CA(cc_idx %d) scellIdx(%d) cellGroup(%d) servCellIdx(%d)
Line 607: (I)Skip State Chage: m_CcIdx(%d) MyScellIndex(%d)
Line 711: (F)ERROR in Update_CaDlConfigInfo: state(%d)
Line 733: [NR_CA_PROC] Set NR_DC_CCH_RECONFIG_DCI_LENG: status_reg(%d), NumofScell(%d), CellGroup(%d), DC_state(%d)
Line 753: (F)ERROR in Update_CaUlConfigInfo: state(%d)
Line 783: (F)ERROR in Cmd(%d)
Line 820: (F)ERROR in ActCcIdx(%d)
Line 833: (F)ERROR in NumOfTotalDlActCC(%d)
Line 837: (F)ERROR in Cmd(%d)
Line 847: Update_CaDlActDeactInfo: m_CcIdx(%d), Cmd(%d), NumOfTotalDlActCC(%d) ActCcIdx(%d) Valid(%d)/isAbove6GHz(%d)
Line 1103: (F)Check in Update_CaScellFreqDlInfo: NumOfScell(%d)
Line 1115: [CA proc] Scell Cc Info: CcIdxBitMap(0x%x), PcellCc(%d)
Line 1135: [CA proc] NumOfScell(%d), ccIdx(%d)/ArrayIndex(%d)/ScellIdxInSHM(%d), IsConditionTrue(%d)/present_flag(0x%X/0x%X/0x%X/0x%X)
Line 1148: (F)Check in Update_CaScellFreqDlInfo: Index(%d) NumOfScsSpecificCarrier(%d)
Line 1173: (F)Error in NumOfScsSpecificCarrierList(%d)
Line 1195: [CA proc]PhyCellGroupCfg: carrierBandwidth(%d)(%d) subcarrierSpacing(%d)(%d) NumOfScsSpecificCarrier (%d)(%d)
Line 1372: [PROC][CA] CaCfgState(%d), ccidx(%d), event(%d)
Line 1395: (F)ERROR in Control_CaCfgState: state(%d)
Line 1535: Check_ScellDeactTimerExpiry
Line 1566: [NR IPC] L2_PHY_SCELL_DEACT_IND , BM_SrcCc/StackId(%d/%d) m_CcIdx(%d) ServingCellId(%d)
Line 1577: (F)Error in SendScellDeactInd: m_CcIdx(%d)
Line 1701: (F)ERROR in CaActDeActState: state(%d)
Line 1817: (F)Error in Update_ScellStatus: m_CcIdx(%d)
Line 1826: (F)Error in Update_ScellStatus: Cmd(%d)
Line 1862: (I) [STRDSE] Update_ScellStatus, m_CcIdx:%d, Cmd:%d, RTG idx:%d, MasterRtgIdx:%d, prevMasterRtgIdx:%d
Line 1878: PHY_PHY_SCELL_STATUS_UPDATE_IND m_CcIdx(%d), ActDeact(%d), NrActFlag(0x%x) Ssb_Detected_Scs(%d), isAbove6GHz(%d)
Line 1893: [NR IPC] PHY_PHY_SCELL_STATUS_UPDATE_IND, BM_SrcCc(0x%X), BM_DstCc(0x%X) Config. CcBitMap(0x%x)
Line 1958: [NR IPC] IPC_NR_DEMOD_SUBCORE_STATUS_IND, BM_SrcCcForCnfMsg(%d)
Line 2013: NrCC Info each CORE = %d 
Line 2033: Error in Update_SCellConfig: sCellIndex(%d)
Line 2039: Error in Update_SCellConfig: ArrayIndex(%d)
Line 2048: Error in Update_SCellConfig: sCellIndex(%d)/ArrayIndex(%d)/sCellIndex_inSHM(%d)
Line 2081: Update_SCellConfig: CcIdx(%d)/sCellIndexInIpc(%d)/ArrayIndex(%d)/sCellIndexInSHM(%d)/present_flag(0x%X)/physCellId(%d)/cell_id(%d), rxPathMap(td_buf_idx:%d/td_buf_idx_div:%d)
Line 2114: [PROC][CA] n(%d)/k(%d)/current(%d)/target(%d)/act_cnt(%d)/isAbove6GHz(%d)/ca_state(%d), scs(%d)
Line 2178: (F)Error in Config: m_CcOffsetIdx(%d)
Line 2259: (F)Error in Set_ScellDeactTimerTarget: timer(%d)
Line 2264: Set_ScellDeactTimerTarget: timer(%d)
Line 2451: [NR IPC] L1C_PHY_CELLGROUP_SCELL_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), demod_cc(%d) Cmd(%d)
Line 2495: [NR IPC] L2_PHY_SCELL_INFO_IND, BM_SrcCcForCnfMsg(%d)
Line 2537: [NR IPC] L1C_PHY_SCELL_ACTDEACT_CNF (ACT), BM_SrcCcForCnfMsg(%d), ipc(%d)
Line 2541: [NR IPC] L1C_PHY_SCELL_ACTDEACT_CNF (DEACT), BM_SrcCcForCnfMsg(%d), ipc(%d)
Line 2544: (I) Check State: %d
Line 2561: [DEBUG] before report: PHY_PHY_RA_CrStateReport_REQ, cellGroup(%d), SpCell(%d)
