Line 155: ConvertPaltimeDomain - invalid RatType(%u)
Line 176: ConvertPaltimeDomain - DiffSystimeSfn(%u, Last: %u, Curr: %u), DiffPalimeSfn(%u, Last: %u, Curr: %u)
Line 186: ConvertPaltimeDomain - Last Paltime(%u) error, DiffTime(%u), DiffSystimeSfn(%u)
Line 227: ConvertPaltimeDomain - CurFrame(%u) FrameNum(%u) RemainFrame(%u) RemainPaltimeUs(%d)
Line 271: ConvertPaltimeDomain - invalid RatType(%u)
Line 291: ConvertPaltimeDomainUsingValue - InputFrame(%u) TargetFrameNum(%u) InputPaltime(%u) RemainPaltimeUs(%d)
