Line 203: Rnti_SetAgapRnti_CSS_ON Pcell org(0x%x) USS ON org(0x%x)
Line 246: Rnti_RestoreServRntiHal Pcell CSS ON backup(0x%x) USS ON backup(0x%x)  CSS_RNTI_ON(0x%x) USS_RNTI_ON(0x%x)
Line 270: Rnti_UnregiCDRXRnti_USS_ON corek(%d),cck(%d),org(0x%x)
Line 296: Rnti_RestoreCDRXRntiHal corek(%d),cck(%d),rnti_uss_on_backup(0x%x)
Line 384: (F) Support FORMAT1, 1A for Temp C-RNTI TM(%d)
Line 397: (F) Remove T-CRNTI cause by C-RNTI(0x%x)
Line 403: (F) Set T-CRNTI only CSS, C-RNTI(0x%x)
Line 459: Rnti_RegisterRnti coreidx(%d),ccidx(%d),CSS(0x%x)(0x%x)(0x%x)(0x%x)(0x%x)(0x%x)(0x%x)
Line 469: Rnti_RegisterRnti USS(0x%x)(0x%x)
Line 484: CC(%d) Rnti_RegisterRnti_on: CSS(0x%x) USS(0x%x)/ dl_ind (0x%x)
Line 579: Rnti_Init: mode(%d) cell_group(%d)
