Line 84: [RF Drv MM] RF_Modem_Get_RxpathState: [%d][%d][%d][%d], channel=0x%x, ifPort=0x%x
Line 112: [RF Drv MM] RF_Modem_Set_Hispeedy_TrigMask: swOnly=0x%x, ccindex=%d, maskEnable[0]=0x%x, maskEnable[1]=0x%x, maskEnable[2]=0x%x
Line 119: [RF Drv MM] need to check rxagc/trxsw for phase array chip: swOnly=%d  hiSpeedyPath=0x%x
Line 125: [RF Drv MM] need to check rxagc/trxsw for phase array chip: cc=%d  hiSpeedyPath=0x%x
Line 140: Need to check hi-speedy path(0x%x)
Line 147: [RF MODEM] RF_Modem_Get_Hispeedy_MemMap: path %d, isGL %d, addr_Mem %d
Line 195: [RF MODEM] RF_Modem_Get_Hispeedy_MemMap: path %d, isGain %d, num_Symbol %d, addr_Mem %d
Line 203: [RF MODEM] RF_Modem_Set_Hispeedy_FormatgenRD:  channel 0x%x, useMCU: %d
Line 206: Need to check hi-speedy path(0x%x)
Line 238: [RF MODEM] RF_Modem_Write_MemRxCCLatch: Latch Tick generated by S5720/S5730 itself
Line 243: [RF MODEM] RF_Modem_Write_MemTRX: TRX switching will done by S5720/S5730 itself
Line 249: [RF MODEM] RF_Modem_Write_MemAxLx: Tickgen at G/L point will be done by S5720/S5730 itself
Line 268: Need to check hi-speedy path(0x%x)
Line 296: [RF MODEM] RF_Modem_Get_QS_Hispeedy_MemMap : path: %d, baseAddr: %d, axgxlx: %d, qsWordNum: %d, qsTrigNum: %d
Line 297: [RF MODEM] RF_Modem_Get_QS_Hispeedy_MemMap : path: %d, QS_ON Addr : %d, QS_OFF Addr : %d 
Line 316: RF_Modem_Write_MemQSleep_Data : Do Nothing, path(0x%x)
Line 329: [RF MODEM] RF_Modem_Quick_Sleep_MM: path[%d] [MemAddr: %d] Addr:0x%x Data:0x%x
Line 340: [RF MODEM] RF_Modem_Quick_Sleep_MM: path[%d] [MemAddr: %d] Addr:0x%x Data:0x%x
Line 350: [RF MODEM] RF_Modem_Quick_Sleep_MM: path[%d] [MemAddr: %d] Addr:0x%x Data:0x%x
Line 360: [RF MODEM] RF_Modem_Quick_Sleep_MM: path[%d] [MemAddr: %d] Addr:0x%x Data:0x%x
Line 395: [RF MODEM] RF_Modem_Set_CfrClippingLimt regvalue 0x%x UL0_CFR 0x%x, UL1_CFR 0x%x
Line 423: [RF Modem] %s: %s compen(%d, %d)
Line 451: [RF Modem] RF_Modem_Set_DPD_AMAM_Gain_MM: CC%d amam_gain[0x%X]
Line 459: [RF MODEM] RF_Modem_Set_IFFTgain_NR|| RB size over : %d
Line 500: [RF MODEM] RF_Modem_Set_IFFTgain_NR ifft_gain 0x%x
Line 530: RF_Modem_Set_TX_Cal_Mode : PHA index errer
Line 556: [RF Modem] RF_Modem_Ready_Direct_Dump_MM: dumprate[%d] bw[%d] adc_no[%d]
Line 940: [RF Modem] RF_Modem_TX_One_Tone_Generate_NR: freq(%d), freqCode(0x%x) level(0x%x)
Line 1025: [RF Modem] RF_Modem_TX_One_Tone_Generate_NR: freq(%d), freqCode(0x%x) level(0x%x)
Line 1037: [RF Modem] RF_Modem_Set_Tone_Gain_MM: CC%d amp[0x%X]
Line 1112: [RF Modem] RF_Modem_Read_DPD_LUT: rd UL0 LUT_index(%d) element_idx(%d) ul0_val 0x%X amam %d ampm %d
Line 1122: [RF Modem] RF_Modem_Read_DPD_LUT: rd UL0 LUT_index(%d) element_idx(%d) ul0_val 0x%X amam %d ampm %d
Line 1173: [RF Modem] RF_Modem_Set_DPD_LUT: DPD sel Id %d 0x%x 0x%x
Line 1180: [RF Modem] RF_Modem_Get_DPD_LUT: DPD sel Id 0x%x 0x%x
Line 1201: [RF Modem] %s: Invalid argument tx_type[%d] LUT_index[%d]
Line 1241: [RF Modem] RF_Modem_Set_DPD_LUT: tx_type(%d) LUT_index(%d) amam(%d) ampm(%d) element_idx(%d)
Line 1248: [RF Modem] RF_Modem_Set_DPD_LUT done
