Line 39: [CMD LOG] : [CpuCoreAllocator] Init(m_Support_DL10CC:%d, m_Support_UL4CC:%d)
Line 101: [CMD LOG] : [CpuCoreAllocator] Select_2.Find Empty CPU Core(TargetCore:%d)
Line 140: [CMD LOG] : [CpuCoreAllocator] Select_3_1.Find 1CC CPU Core to same BandType(TargetCore:%d)
Line 157: [CMD LOG] : [CpuCoreAllocator] Select_3.Find 1CC CPU Core to same BandType(TargetCore:%d)
Line 197: [CMD LOG] : [CpuCoreAllocator] Select_4_1.Find 1CC CPU Core to same BandType(TargetCore:%d)
Line 210: [CMD LOG] : [CpuCoreAllocator] Select_4.Find 1CC CPU Core to same BandType(TargetCore:%d)
Line 247: [CMD LOG] : [CpuCoreAllocator] Select_5_1.AllocToOneCcCoreDiffBandOneUlCc(TargetCore:%d)
Line 259: [CMD LOG] : [CpuCoreAllocator] Select_5.AllocToOneCcCoreDiffBandOneUlCc(TargetCore:%d)
Line 298: [CMD LOG] : [CpuCoreAllocator] Select_6_1.AllocToOneCcCoreDiffBandNoUlCc(TargetCore:%d)
Line 310: [CMD LOG] : [CpuCoreAllocator] Select_6.AllocToOneCcCoreDiffBandNoUlCc(TargetCore:%d)
Line 357: [CMD LOG] : [CpuCoreAllocator] Select_9_1.Find 2CC CPU Core(TargetCore:%d)
Line 368: [CMD LOG] : [CpuCoreAllocator] Select_9.Find 2CC CPU Core(TargetCore:%d)
Line 399: [CMD LOG] : [CpuCoreAllocator] Select_8.Use Other Domain Pcell Area(TargetCore:%d)
Line 428: [CMD LOG] : [CpuCoreAllocator] Select_8_1.Use Other Domain Pcell Area(TargetCore:%d)
Line 442: [CMD LOG] : [CpuCoreAllocator] Select_8_2.Find 1CC CPU Core to Other Domain Pcell Area(TargetCore:%d)
Line 473: [CMD LOG] : [CpuCoreAllocator] Select_8_3.Use Other Domain Pcell Area(TargetCore:%d)
Line 486: [CMD LOG] : [CpuCoreAllocator] Select_8_4.Find 1CC CPU Core to Other Domain Pcell Area(TargetCore:%d)
Line 509: [CMD LOG] : [CpuCoreAllocator] Select_10.Use Other CG Pcell Area(TargetCore:%d)
Line 529: [CMD LOG] : [CpuCoreAllocator] Select_10_1.Use Other CG Pcell Area(TargetCore:%d)
Line 542: [CMD LOG] : [CpuCoreAllocator] Select_10_2.Find 1CC CPU Core to Other CG Pcell Area(TargetCore:%d)
Line 565: [CMD LOG] : [CpuCoreAllocator] Select_10_3.Use Other CG Pcell Area(TargetCore:%d)
Line 577: [CMD LOG] : [CpuCoreAllocator] Select_10_4.Find 1CC CPU Core to Other CG Pcell Area(TargetCore:%d)
Line 596: [CMD LOG] : [CpuCoreAllocator] CleanAllocTable: TargetCore(%d), StackId(%d), CellGroup(%d), DemodCc(%d), PcellCc(%d)
Line 602: [CMD LOG] : [CpuCoreAllocator] CleanAllocTable: TargetCore(%d), StackId(%d), CellGroup(%d), DemodCc(%d), PcellCc(%d)
Line 617: [CMD LOG] : [CpuCoreAllocator] Alloc fail due to max NumAlloc: TargetCore(%d), NumAlloc(%d)
Line 624: [CMD LOG] : [CpuCoreAllocator] Alloc success: TargetCore(%d), NumAlloc(%d)
Line 630: [CMD LOG] : [CpuCoreAllocator] Error!! CheckValidCcInfo Failure!!!(StackId:%d, CellGroup:%d)
Line 635: [CMD LOG] : [CpuCoreAllocator] Warning!! CheckValidCcInfo Failure!!!(DemodCore:%d, BandType:%d, IsUlCc:%d)
Line 643: [CMD LOG] : [CpuCoreAllocator] Alloc (m_Support_DL10CC:%d, m_Support_UL4CC:%d)
Line 645: [CMD LOG] : [CpuCoreAllocator] Alloc CcInfo:StackId(%d), CellGroup(%d), DemodCc(%d), DemodCore(%d), PcellCc(%d), BandType(%d), IsUlCc(%d)
Line 650: [CMD LOG] : [CpuCoreAllocator] Error!!! - CPU Core Alloc Fail dueto validation check failure!!!
Line 656: [CMD LOG] : [CpuCoreAllocator] Warning!! Same CC(%d) is allocated!!
Line 671: [CMD LOG] : [CpuCoreAllocator] Select_1.Pcell Allocation(TargetCore:%d)
Line 798: [CMD LOG] : [CpuCoreAllocator] Warning - CPU Core Alloc Fail!!!
Line 805: [CMD LOG] : [CpuCoreAllocator] Free CcInfo:StackId(%d), CellGroup(%d), DemodCc(%d), DemodCore(%d), PcellCc(%d), BandType(%d)
Line 818: [CMD LOG] : [CpuCoreAllocator] Free Success: TargetCore(%d), NumAlloc(%d)
Line 833: [CMD LOG] : [CpuCoreAllocator] Warning - CPU Core Free Fail!!!
Line 840: [CMD LOG] : [CpuCoreAllocator] FindCpuCore CcInfo:StackId(%d), CellGroup(%d), DemodCc(%d), DemodCore(%d), PcellCc(%d), BandType(%d)
Line 847: [CMD LOG] : [CpuCoreAllocator] Find Success: TargetCore(%d), NumAlloc(%d)
Line 852: [CMD LOG] : [CpuCoreAllocator] Not Found
Line 858: [CMD LOG] : [CpuCoreAllocator] FindCcInfo: DemodCc(%d)
Line 865: [CMD LOG] : [CpuCoreAllocator] Find Success: TargetCore(%d), NumAlloc(%d)
Line 871: [CMD LOG] : [CpuCoreAllocator] Not Found
Line 889: [CMD LOG] : [CpuCoreAllocator] PrintStatus: CPU_CORE(%d), NumAlloc(%d)
Line 894: [CMD LOG] : [CpuCoreAllocator] PrintStatus: [%d] StackId(%d) CellGroup(%d) DemodCc(%d) DemodCore(%d) PcellCc(%d) BandType(%d) IsUlCc(%d)
Line 900: [CMD LOG] : [CpuCoreAllocator] GetMcgPcellCc: StackId(%d)
Line 913: [CMD LOG] : [CpuCoreAllocator] GetMcgPcellCc: StackId(%d), CellGroup(%d) PcellCc(%d)
Line 918: [CMD LOG] : [CpuCoreAllocator] Not Found McgPcellCc
